// ===========================================================================
// FIELD FAILURE REGISTER — the shape of the record, kept out of the screen.
//
// The column order and the headings are the Field_Failure_Register workbook's
// 2026 tab, so somebody who has used the sheet for years reads the same
// register here. The AutoCrat columns (Add Attachments, EO, Raise CAPA, Merged
// Doc ID, Document Merge Status …) are not carried: they exist to make a
// spreadsheet behave like an application, and the document is generated by the
// application now.
// ===========================================================================
import type { FfrDocFields } from './ffrdoc';

/** The sheet's headings, in the sheet's order, against the column that holds
 *  each one. The register table is drawn from this, so the two cannot drift. */
export const FFR_COLUMNS: { key: string; header: string; width?: number }[] = [
  { key: 'ffr_no', header: 'FFR NO: (No/Yr)', width: 120 },
  { key: 'ffr_date', header: 'FFR Date', width: 110 },
  { key: 'source', header: 'Source', width: 80 },
  { key: 'ucn', header: 'CRN NO', width: 130 },
  { key: 'crn_date', header: 'CRN Date', width: 110 },
  { key: 'customer_name', header: 'Customer Name', width: 230 },
  { key: 'place', header: 'Place', width: 120 },
  { key: 'product_name', header: 'Product Name', width: 140 },
  { key: 'cover', header: 'WGP/ OGP/ AMC', width: 110 },
  { key: 'item_code', header: 'Item Code', width: 110 },
  { key: 'product_serial', header: 'Product S. No', width: 120 },
  { key: 'installation_date', header: 'Installation Date', width: 120 },
  { key: 'problem_reported', header: 'Problem reported by customer', width: 240 },
  { key: 'service_observation', header: 'Service Dept Observation', width: 260 },
  { key: 'problem_status', header: 'Problem Status', width: 240 },
  { key: 'capa_responsibility', header: 'CAPA(if Reqd) Responsibility', width: 160 },
  { key: 'capa_no', header: 'CAPA NO: F<No>/Yr', width: 130 },
  { key: 'capa_status', header: 'CAPA Status', width: 130 },
  { key: 'verified_by', header: 'Verified By', width: 130 },
  { key: 'remarks', header: 'Remarks', width: 180 },
  { key: 'current_call_status', header: 'CURRENT CALL STATUS', width: 150 },
  { key: 'call_solved_at', header: 'Call Solved Date & Time', width: 150 },
  { key: 'visit_remarks', header: 'VISIT REMARKS', width: 240 },
  { key: 'spares_consumed', header: 'SPARES CONSUMED', width: 240 },
  { key: 'call_type', header: 'Call Type', width: 100 },
  { key: 'additional_problem', header: 'Additional Problem Description', width: 220 },
  { key: 'ffr_status', header: 'FFR STATUS', width: 110 },
];

/**
 * THE LIVE CALL, BESIDE THE RECORD (the user: "all the Live data should show in
 * the field failure register as well for analysis and decisions").
 *
 * The columns above are the RECORD — what was true when the report was raised,
 * and what the document prints. These are the same call as it stands NOW. Both
 * are shown because they answer different questions: the record says what was
 * reported, the live columns say whether it still holds.
 *
 * The most useful of them is the effect: an FFR raised on
 * `any_potential_effect = YES` whose review now reads NO is not deleted (a
 * quality record is not removed because somebody revised an opinion), so this
 * is how a reader sees that happened.
 */
export const FFR_LIVE_COLUMNS: { key: string; header: string; width?: number }[] = [
  { key: 'live_any_potential_effect', header: 'Any Potential Effect (now)', width: 150 },
  { key: 'live_call_status', header: 'Call Status (now)', width: 140 },
  { key: 'live_engineer', header: 'Engineer (now)', width: 140 },
  { key: 'live_visit_count', header: 'Visits (now)', width: 100 },
  { key: 'live_spares_consumed', header: 'Spares (now)', width: 220 },
  { key: 'live_risk_to_patient', header: 'Risk to Patient', width: 120 },
  { key: 'live_warranty_failure', header: 'Warranty Failure', width: 130 },
  { key: 'live_frequent_failure', header: 'Frequent Failure', width: 130 },
  { key: 'live_complaint_grouping', header: 'Complaint Grouping', width: 170 },
  { key: 'live_root_cause_keyword', header: 'Root Cause Key Word', width: 170 },
  { key: 'live_spare_category', header: 'Spare / Consumable', width: 150 },
];

/**
 * THE WEEKLY REVIEW'S OWN FIELDS, and only those.
 *
 * The Google Form this replaces updates exactly these, keyed on the UCN and the
 * FFR number: the two long texts, the three CAPA columns, the FFR status and an
 * attachment. The rest of the register is not on it — a weekly review is not a
 * chance to rewrite the machine or the customer, and a form that offered those
 * would invite it.
 *
 * "Generate FFR Word Copy?" is on the form because a spreadsheet needed telling.
 * Here the document is a button on the row, so the question does not arise.
 */
export const FFR_REVIEW_FIELDS = [
  'additional_problem', 'problem_status', 'service_observation',
  'capa_responsibility', 'capa_no', 'capa_status',
  'ffr_status', 'attachment_url', 'attachment_name',
] as const;

/**
 * WHAT MAY BE WRITTEN TO `field_failure_reports`.
 *
 * THE REGISTER READS A VIEW AND THE FORM SAVES A TABLE, and that is the whole
 * reason this list exists. `field_failure_register` carries the record PLUS the
 * live call beside it (`live_call_status`, `live_any_potential_effect`, …);
 * clicking a row seeds the edit form with that row, and saving it sent every
 * one of those columns back to the table, which does not have them. PostgREST
 * answers "Could not find the 'live_any_potential_effect' column of
 * 'field_failure_reports' in the schema cache" and the edit is lost — reported
 * from use, 2026-09-12.
 *
 * A WHITELIST, NOT A BLACKLIST. Stripping `live_%` would work today and fail
 * the first time the view gains a column that is not prefixed — and the failure
 * would again be a save that looks like it worked until the error appears.
 * `check:ui` compares this list against the table's own definition in the
 * migrations, so a column added to one and not the other is caught.
 *
 * The columns the DATABASE owns are deliberately absent: `id`, `ffr_no` (issued
 * once, never edited — 0168's stamp puts the old value back anyway),
 * `raised_by`, `created_at` and `updated_at`.
 */
export const FFR_WRITABLE = [
  'ffr_date', 'source', 'ucn', 'crn_date',
  'customer_name', 'place', 'product_name', 'cover', 'item_code', 'product_serial',
  'installation_date',
  'problem_reported', 'additional_problem', 'service_observation', 'problem_status',
  'capa_responsibility', 'capa_no', 'capa_status',
  'verified_by', 'remarks', 'current_call_status', 'call_solved_at',
  'visit_remarks', 'spares_consumed', 'call_type', 'ffr_status', 'doc_url',
  'extra', 'raised_by_name',
  // The weekly review's own columns (0168).
  'attachment_url', 'attachment_name', 'reviewed_at', 'reviewed_by_name',
] as const;

/** A row reduced to what the table will accept. Keys it does not know are
 *  dropped rather than sent — including every live_* column the view added. */
export function ffrWritable(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const k of FFR_WRITABLE) if (k in row) out[k] = row[k];
  return out;
}

/** Reports not looked at since `since`. The point of a weekly cycle is knowing
 *  which ones those are, and `updated_at` cannot answer it — any edit moves
 *  that, so a report corrected on Tuesday would read as reviewed. */
export function ffrDueForReview(r: Record<string, unknown>, since: Date): boolean {
  if (String(r.ffr_status ?? '') !== 'Open') return false;
  const at = String(r.reviewed_at ?? '').trim();
  if (!at) return true;
  const d = new Date(`${at.slice(0, 10)}T00:00:00`);
  return Number.isNaN(d.getTime()) ? true : d < since;
}

/** An FFR whose review no longer says YES. Not an error — the record stands —
 *  but the one thing on this register somebody should be able to see at a
 *  glance, because it means the finding was revised after the report was made. */
export function ffrEffectWithdrawn(r: Record<string, unknown>): boolean {
  const rule = String((r.extra as Record<string, unknown>)?.raised_by_rule ?? '');
  const now = String(r.live_any_potential_effect ?? '').trim().toUpperCase();
  return rule === 'any_potential_effect=YES' && now !== '' && now !== 'YES';
}

/** The vocabularies the sheet actually uses. */
export const FFR_SOURCES = ['PC'];
export const FFR_COVER = ['WGP', 'OGP', 'AMC', 'CMC'];
// The sheet's own LookupValues tab, in full. 'In-Progress' and 'NA' were
// missing from the first draft — a status a register already uses and a picker
// will not offer is a value somebody has to work around.
export const FFR_CAPA_STATUS = ['Not required', 'Open', 'In-Progress', 'Closed', 'TBD'];
// The update form's own list (2026-09-12). It takes free text as well — the
// form has an "Other" line, and a responsibility is a PERSON: the list will
// always be behind by whoever joined last, and refusing a name is worse than
// carrying one the list has not caught up with.
export const FFR_CAPA_RESPONSIBILITY =
  ['No closed in FFR', 'Shyam', 'NRCK', 'ALMS-FRANCE', 'DILIP', 'PK'];
// Likewise: NA / Not Required, or a real CAPA number typed in.
export const FFR_CAPA_NO = ['NA', 'Not Required'];
// 'Cancelled' is on the update form beside Open and Closed. A cancelled report
// is still a record — marked, never deleted (0049).
export const FFR_STATUS = ['Open', 'Closed', 'Cancelled'];

/** A number this register issued, or one carried in from the sheet. Used to
 *  tell a reader that a row predates the application. */
export const FFR_NO_SHAPE = /^FFR\s*-\s*\d+\/\d{2}$/;

/**
 * The document's fields, from a register row.
 *
 * ONE MAPPING, so the register and the report cannot disagree about what a box
 * contains — the sheet kept the two in separate places and the report is what
 * leaves the building.
 */
export function ffrDocFrom(r: Record<string, unknown>, raisedBy: string): FfrDocFields {
  const g = (k: string) => String(r[k] ?? '');
  return {
    ffrNo: g('ffr_no'),
    ffrDate: g('ffr_date'),
    customerName: g('customer_name'),
    place: g('place'),
    crnNo: g('ucn'),
    crnDate: g('crn_date'),
    productName: g('product_name'),
    itemCode: g('item_code'),
    productSerial: g('product_serial'),
    cover: g('cover'),
    problemReported: g('problem_reported'),
    additionalProblem: g('additional_problem'),
    serviceObservation: g('service_observation'),
    problemStatus: g('problem_status'),
    capaNo: g('capa_no') || 'NA',
    raisedBy: raisedBy || g('raised_by_name'),
  };
}

/**
 * WHAT THE DAILY CALL REVIEW FILLS IN.
 *
 * The review already holds nearly the whole report, and that is not a
 * coincidence — both exist to say what failed and what was done about it. Its
 * Review 3 field is HEADED "Service Dept Observation", which is the FFR column
 * of that name; `visit_details` is already "date : what was done", newest
 * first, which is the sheet's VISIT REMARKS format; and `spares_consumed` is
 * already the joined list the sheet carries.
 *
 * So the report is filled FROM THE REVIEW ROW rather than by re-reading the
 * visits and the consumption. Fewer requests, and — the point — the register,
 * the review and the report cannot then disagree about the same failure.
 *
 * CHECKED AGAINST THE 35 ROWS ALREADY IN THE 2026 TAB. Every one is a SOLVED
 * FIELD call; Item Code is empty in all 35; Verified By, Sign and Remarks are
 * empty in all 35; and Additional Problem Description is the spreadsheet's own
 * `#N/A` in 33 of them, which is a lookup failure rather than a value and is
 * deliberately not reproduced here.
 */
export interface ReviewSource {
  ucn?: unknown; call_number?: unknown; reg_date?: unknown; complaint_date?: unknown;
  party_name?: unknown; city?: unknown; product_name?: unknown; serial?: unknown;
  item_status?: unknown; call_type?: unknown; warranty_start?: unknown;
  standard_complaint?: unknown; complaint_reported?: unknown;
  service_observation?: unknown; observation?: unknown; job_done?: unknown;
  visit_details?: unknown; spares_consumed?: unknown;
  open_state?: unknown; last_status?: unknown; last_visit_at?: unknown;
}

export function ffrFromReview(r: ReviewSource): Record<string, unknown> {
  const s = (v: unknown) => String(v ?? '').trim();
  const day = (v: unknown) => (s(v) ? s(v).slice(0, 10) : null);
  return {
    source: 'PC',                       // the only Source in the 2026 tab
    ucn: s(r.ucn),
    crn_date: day(r.reg_date) ?? day(r.complaint_date),
    customer_name: s(r.party_name),
    place: s(r.city),
    product_name: s(r.product_name),
    product_serial: s(r.serial),
    cover: s(r.item_status),
    // The machine's installation date — filled in all 35 rows of the sheet, and
    // the warranty start is where the register keeps it.
    installation_date: day(r.warranty_start),
    problem_reported: s(r.complaint_reported) || s(r.standard_complaint),
    // REVIEW 3's OWN FIELD, which is headed "Service Dept Observation". The
    // visit's Complaint Observation is the fallback for a call reviewed before
    // that field was answered.
    service_observation: s(r.service_observation) || s(r.observation),
    problem_status: s(r.job_done),
    visit_remarks: s(r.visit_details),
    spares_consumed: s(r.spares_consumed),
    current_call_status: s(r.open_state) || s(r.last_status),
    call_solved_at: s(r.last_visit_at) || null,
    call_type: s(r.call_type),
    // The sheet's defaults, from its LookupValues tab.
    capa_responsibility: 'No closed in FFR',
    capa_no: 'NA',
    capa_status: 'Not required',
    ffr_status: 'Open',
  };
}

/** Every one of the 35 rows in the 2026 tab is a SOLVED call, and that is the
 *  rule rather than a coincidence: an FFR describes a failure that has been
 *  diagnosed. Raising one on an open call is allowed — somebody may have to —
 *  but the screen says so rather than letting it pass unremarked. */
export function ffrCallNotSolved(state: string): boolean {
  return !/^solved/i.test(String(state ?? '').trim());
}
