// ===========================================================================
// FIELD FAILURE REGISTER — the shape of the record, kept out of the screen.
//
// The column order and the headings are the Field_Failure_Register workbook's
// 2026 tab, so somebody who has used the sheet for years reads the same
// register here. The AutoCrat columns (Add Attachments, EO, Raise CAPA, Merged
// Doc ID, Document Merge Status …) are not carried: they exist to make a
// spreadsheet behave like an application, and the document is generated by the
// application now.
// ===========================================================================
import type { FfrDocFields } from './ffrdoc';

/** The sheet's headings, in the sheet's order, against the column that holds
 *  each one. The register table is drawn from this, so the two cannot drift. */
export const FFR_COLUMNS: { key: string; header: string; width?: number }[] = [
  { key: 'ffr_no', header: 'FFR NO: (No/Yr)', width: 120 },
  { key: 'ffr_date', header: 'FFR Date', width: 110 },
  { key: 'source', header: 'Source', width: 80 },
  { key: 'ucn', header: 'CRN NO', width: 130 },
  { key: 'crn_date', header: 'CRN Date', width: 110 },
  { key: 'customer_name', header: 'Customer Name', width: 230 },
  { key: 'place', header: 'Place', width: 120 },
  { key: 'product_name', header: 'Product Name', width: 140 },
  { key: 'cover', header: 'WGP/ OGP/ AMC', width: 110 },
  { key: 'item_code', header: 'Item Code', width: 110 },
  { key: 'product_serial', header: 'Product S. No', width: 120 },
  { key: 'installation_date', header: 'Installation Date', width: 120 },
  { key: 'problem_reported', header: 'Problem reported by customer', width: 240 },
  { key: 'service_observation', header: 'Service Dept Observation', width: 260 },
  { key: 'problem_status', header: 'Problem Status', width: 240 },
  { key: 'capa_responsibility', header: 'CAPA(if Reqd) Responsibility', width: 160 },
  { key: 'capa_no', header: 'CAPA NO: F<No>/Yr', width: 130 },
  { key: 'capa_status', header: 'CAPA Status', width: 130 },
  { key: 'verified_by', header: 'Verified By', width: 130 },
  { key: 'remarks', header: 'Remarks', width: 180 },
  { key: 'current_call_status', header: 'CURRENT CALL STATUS', width: 150 },
  { key: 'call_solved_at', header: 'Call Solved Date & Time', width: 150 },
  { key: 'visit_remarks', header: 'VISIT REMARKS', width: 240 },
  { key: 'spares_consumed', header: 'SPARES CONSUMED', width: 240 },
  { key: 'call_type', header: 'Call Type', width: 100 },
  { key: 'additional_problem', header: 'Additional Problem Description', width: 220 },
  { key: 'ffr_status', header: 'FFR STATUS', width: 110 },
];

/** The vocabularies the sheet actually uses. */
export const FFR_SOURCES = ['PC'];
export const FFR_COVER = ['WGP', 'OGP', 'AMC', 'CMC'];
export const FFR_CAPA_STATUS = ['Not required', 'Open', 'TBD', 'Closed'];
export const FFR_STATUS = ['Open', 'Closed'];

/** A number this register issued, or one carried in from the sheet. Used to
 *  tell a reader that a row predates the application. */
export const FFR_NO_SHAPE = /^FFR\s*-\s*\d+\/\d{2}$/;

/**
 * The document's fields, from a register row.
 *
 * ONE MAPPING, so the register and the report cannot disagree about what a box
 * contains — the sheet kept the two in separate places and the report is what
 * leaves the building.
 */
export function ffrDocFrom(r: Record<string, unknown>, raisedBy: string): FfrDocFields {
  const g = (k: string) => String(r[k] ?? '');
  return {
    ffrNo: g('ffr_no'),
    ffrDate: g('ffr_date'),
    customerName: g('customer_name'),
    place: g('place'),
    crnNo: g('ucn'),
    crnDate: g('crn_date'),
    productName: g('product_name'),
    itemCode: g('item_code'),
    productSerial: g('product_serial'),
    cover: g('cover'),
    problemReported: g('problem_reported'),
    additionalProblem: g('additional_problem'),
    serviceObservation: g('service_observation'),
    problemStatus: g('problem_status'),
    capaNo: g('capa_no') || 'NA',
    raisedBy: raisedBy || g('raised_by_name'),
  };
}

/** What a call fills in when an FFR is raised from the Daily Call Review. The
 *  rest is the reviewer's to write — an observation nobody wrote is not one. */
export interface CallPrefill {
  ucn?: unknown; call_number?: unknown; reg_date?: unknown;
  party_name?: unknown; city?: unknown; product_name?: unknown; serial?: unknown;
  item_status?: unknown; complaint_reported?: unknown; standard_complaint?: unknown;
  open_state?: unknown; last_status?: unknown; call_type?: unknown;
}

export function ffrFromCall(c: CallPrefill): Record<string, unknown> {
  const s = (v: unknown) => String(v ?? '').trim();
  return {
    source: 'PC',
    ucn: s(c.ucn),
    crn_date: s(c.reg_date) || null,
    customer_name: s(c.party_name),
    place: s(c.city),
    product_name: s(c.product_name),
    product_serial: s(c.serial),
    cover: s(c.item_status),
    problem_reported: s(c.complaint_reported) || s(c.standard_complaint),
    current_call_status: s(c.open_state) || s(c.last_status),
    call_type: s(c.call_type),
    capa_no: 'NA',
    capa_status: 'Not required',
    ffr_status: 'Open',
  };
}
