// ---------------------------------------------------------------------------
// Pending dispatch — the Stores queue, grouped by engineer.
//
// Approval is per spare, but DISPATCH is a batch: Stores picks everything
// waiting for one engineer and books it out under a single stock out. So the
// queue is grouped by engineer, the selection is per spare, and a batch may
// never span two engineers — a DC is one delivery to one person.
//
// The numbers (SO / DC) are generated by Postgres, not here: dispatch_spare_lines()
// (0027_spare_dispatch.sql) creates the stock out and stamps every line in it,
// so a batch either lands whole or not at all.
// ---------------------------------------------------------------------------

export interface PendingLine {
  line_id: number;
  line_uid: string;
  request_uid: string;
  or_no: string;
  or_req_date: string | null;
  row_no: number;
  part: string;
  part_code: string;
  qty: number;             // units STILL to send (requested minus dispatched)
  requested_qty: number;   // what the engineer originally asked for
  dispatched_qty: number;  // what has already gone out on earlier stock outs
  req_type: string;
  item_status: string;
  engineer: string;
  engineer_key: string;
  engineer_email: string;
  ucn: string;
  call_number: string;
  party_name: string;
  product_name: string;
  serial: string;
  handstock_reason: string;
  remarks: string;
  raised_at: string | null;
  waiting_since: string | null;
}

export interface EngineerQueue {
  engineer_key: string;
  engineer: string;
  engineer_email: string;
  lines: PendingLine[];
  spares: number;   // distinct spare lines waiting
  qty: number;      // units waiting
  orders: number;   // distinct ORs they span
  oldest: string;   // waiting_since of the longest-waiting spare
}

const s = (v: unknown) => String(v ?? '').trim();
const n = (v: unknown) => { const x = Number(v); return Number.isFinite(x) ? x : 0; };

// Rows arrive from the view untyped; normalise once so the screen and the
// tests agree on the shape.
export function toPendingLine(r: Record<string, unknown>): PendingLine {
  return {
    line_id: n(r.line_id), line_uid: s(r.line_uid), request_uid: s(r.request_uid),
    or_no: s(r.or_no), or_req_date: r.or_req_date ? s(r.or_req_date) : null, row_no: n(r.row_no),
    part: s(r.part), part_code: s(r.part_code), qty: n(r.qty),
    requested_qty: n(r.requested_qty ?? r.qty), dispatched_qty: n(r.dispatched_qty),
    req_type: s(r.req_type), item_status: s(r.item_status),
    engineer: s(r.engineer), engineer_key: s(r.engineer_key), engineer_email: s(r.engineer_email),
    ucn: s(r.ucn), call_number: s(r.call_number), party_name: s(r.party_name),
    product_name: s(r.product_name), serial: s(r.serial),
    handstock_reason: s(r.handstock_reason), remarks: s(r.remarks),
    raised_at: r.raised_at ? s(r.raised_at) : null,
    waiting_since: r.waiting_since ? s(r.waiting_since) : null,
  };
}

// The queue, one group per engineer. Longest-waiting engineer first: that is
// the order Stores works in, not alphabetical.
export function groupByEngineer(lines: PendingLine[]): EngineerQueue[] {
  const map = new Map<string, EngineerQueue>();
  for (const l of lines) {
    const key = l.engineer_key || l.engineer.toLowerCase();
    const g = map.get(key) ?? {
      engineer_key: key, engineer: l.engineer || '(unnamed)', engineer_email: l.engineer_email,
      lines: [], spares: 0, qty: 0, orders: 0, oldest: '',
    };
    g.lines.push(l);
    if (!g.engineer_email && l.engineer_email) g.engineer_email = l.engineer_email;
    map.set(key, g);
  }
  for (const g of map.values()) {
    g.lines.sort((a, b) => a.or_no.localeCompare(b.or_no) || a.row_no - b.row_no);
    g.spares = g.lines.length;
    g.qty = g.lines.reduce((t, l) => t + l.qty, 0);
    g.orders = new Set(g.lines.map((l) => l.request_uid)).size;
    g.oldest = g.lines.map((l) => l.waiting_since ?? '').filter(Boolean).sort()[0] ?? '';
  }
  return [...map.values()].sort((a, b) =>
    (a.oldest || '9999').localeCompare(b.oldest || '9999') || b.qty - a.qty || a.engineer.localeCompare(b.engineer));
}

// How long the oldest spare in a queue has been waiting, in whole days. Stores
// works the queue by age, so this is what the group is sorted and flagged on.
export function daysWaiting(iso: string, now = Date.now()): number {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return 0;
  return Math.max(0, Math.floor((now - t) / 86_400_000));
}
export const ageTone = (days: number): 'danger' | 'warning' | 'neutral' =>
  days >= 14 ? 'danger' : days >= 7 ? 'warning' : 'neutral';

// A selection is only dispatchable while it is non-empty and belongs to ONE
// engineer — the same rule dispatch_spare_lines() enforces, checked here so the
// button can say why instead of the database having to.
export function selectionProblem(selected: PendingLine[]): string | null {
  if (!selected.length) return 'Tick the spares to send.';
  const engineers = new Set(selected.map((l) => l.engineer_key));
  if (engineers.size > 1) return 'A stock out goes to one engineer — the selection spans ' + engineers.size + '.';
  return null;
}

export const selectedFrom = (lines: PendingLine[], ids: ReadonlySet<number>): PendingLine[] =>
  lines.filter((l) => ids.has(l.line_id));

export interface QueueSummary { engineers: number; spares: number; qty: number; orders: number; ageing: number }

// Ageing = spares that have been waiting a week or more. It is the number
// Stores is judged on, so it is a tile of its own.
export function summarise(lines: PendingLine[], now = Date.now()): QueueSummary {
  return {
    engineers: new Set(lines.map((l) => l.engineer_key)).size,
    spares: lines.length,
    qty: lines.reduce((t, l) => t + l.qty, 0),
    orders: new Set(lines.map((l) => l.request_uid)).size,
    ageing: lines.filter((l) => daysWaiting(l.waiting_since ?? '', now) >= 7).length,
  };
}

// The result of a batch, as the database reports it back.
export interface DispatchResult {
  uid: string;            // stock out number
  dc_number: string;
  engineer: string;
  line_count: number;
  total_qty: number;
  dc_date: string;
  courier: string;
  remarks: string;
  dispatched_at: string;
}
