-- ===========================================================================
-- RITHI CRM — Hand Stock: apply bundle
--
-- The stock level an engineer is carrying, per spare:
-- 
--   Stock Level = Stock Out (Stores) - Consumption
--               - Stock Transfer From + Stock Transfer To
-- 
-- The movement behind every figure (the DC, the call, the other engineer),
-- each term of the formula as its own column, and `engineer_stock` --- what
-- Stock Transfer and its stock guard read --- redefined over the same
-- derivation, so the two screens cannot disagree.
-- 
-- Needs the spare workflow through per-spare approvals and the stock-transfer
-- tables; _status.sql says which of those are missing.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0022_handstock.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.spare_requests') is null then
    missing := array_append(missing, 'the spare_requests table — 0001_init.sql (apply bundle: base)');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.is_admin()') is null then
    missing := array_append(missing, 'is_admin() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.can_approve_spares()') is null then
    missing := array_append(missing, 'can_approve_spares() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.spare_line_stage(text,text,text,text,timestamptz,text)') is null then
    missing := array_append(missing, 'per-spare approvals (spare_request_lines.dispatched_at) — 0016_spare_line_approvals.sql (apply bundle: Spare_X.sql)');
  end if;
  if to_regclass('public.stock_transfer_lines') is null then
    missing := array_append(missing, 'the stock-transfer tables — 0020_stock_transfer.sql (apply bundle: stock_transfer)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0022_handstock.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Hand stock — the stock level an engineer is carrying, per spare.
--
--   Stock Level = Stock Out (from Stores)
--               − Consumption
--               − Stock Transfer From
--               + Stock Transfer To
--
-- 0020_stock_transfer.sql already derives that balance for the Stock Transfer
-- screen (`engineer_stock`), and owns the transfer tables. This migration does
-- not add a second one: it keeps ONE derivation and gives it the detail the
-- Hand Stock register needs.
--
--   handstock_movements — one row per movement, with where it came from:
--                         the DC, the call, or the engineer on the other side.
--   handstock_balance   — the level per engineer + spare, with each term of
--                         the formula kept separately.
--   engineer_stock      — REDEFINED over handstock_balance, so the transfer
--                         screen, its stock guard and this register can never
--                         disagree. Same columns, same meaning.
--
-- Two things the first derivation missed, both of which made a balance wrong:
--
--   • Only `req_type = 'HandStock'` requests counted as stock in. A spare
--     dispatched against a CALL was consumed out of a balance it had never
--     been added to, so the engineer went negative and their transfers were
--     refused. Every spare Stores dispatches is stock in the engineer's hands,
--     whatever the request was raised for.
--   • The status is what makes it a stock out, not the timestamp. Dispatches
--     from the sheet era, from imports, or from before 0009 added
--     dispatched_at carry a DC but no date, and are every bit as much stock.
--
-- The views run with the caller's rights, so the register is scoped exactly
-- like the tables under it: an engineer sees their own stock, an RM their
-- sub-tree, an admin everyone's.
-- ===========================================================================

-- Consumption is keyed by the engineer's NAME (that is all the report form ever
-- wrote). The name is what the movements are matched on; the email is carried
-- alongside so a rename can be untangled later, and so new rows can be matched
-- on it once the field has been filled for a while.
alter table public.spare_consumption
  add column if not exists engineer_email text default '';

create index if not exists spare_consumption_engineer_idx     on public.spare_consumption (lower(btrim(engineer)));
create index if not exists spare_consumption_created_at_idx   on public.spare_consumption (created_at desc);
create index if not exists spare_request_lines_stores_idx     on public.spare_request_lines (lower(coalesce(stores_status, '')));
create index if not exists spare_request_lines_dispatched_idx on public.spare_request_lines (dispatched_at) where dispatched_at is not null;

-- ---------------------------------------------------------------------------
-- The two things a movement is matched on. Names arrive with stray case and
-- spacing from four different screens; a spare is stored as its catalogue
-- string "CODE|Description", and only the CODE identifies it.
-- ---------------------------------------------------------------------------
create or replace function public.handstock_key(p text)
returns text language sql immutable as $$ select lower(btrim(coalesce(p, ''))) $$;

create or replace function public.part_code(p text)
returns text language sql immutable as $$ select upper(btrim(split_part(coalesce(p, ''), '|', 1))) $$;

grant execute on function public.handstock_key(text) to authenticated;
grant execute on function public.part_code(text)     to authenticated;

-- ---------------------------------------------------------------------------
-- Movements — the four terms of the formula, one row each.
--
-- Stock out is dated by the DISPATCH, not the acknowledgement: the spare left
-- Stores and is the engineer's from that moment, whether or not they have got
-- round to acknowledging it. Since 0016_spare_line_approvals.sql dispatch is
-- per SPARE, so a partly dispatched OR moves only what actually went out.
--
-- What makes it a stock out is the STATUS, not the timestamp. Dispatches from
-- before this module — sheet-era history, imports, anything dispatched before
-- 0009 added dispatched_at — carry a DC and a status but no date, and they are
-- every bit as much stock in the engineer's hands. They count, dated by the
-- best timestamp the row has.
-- ---------------------------------------------------------------------------
create or replace view public.handstock_movements as
-- 1. Stock out from Stores (+)
select
  'IN'::text                                        as direction,
  'Stock out'::text                                 as movement,
  public.handstock_key(r.engineer)                  as engineer_key,
  coalesce(r.engineer, '')                          as engineer,
  coalesce(r.engineer_email, '')                    as engineer_email,
  public.part_code(l.part)                          as part_code,
  coalesce(l.part, '')                              as part,
  coalesce(l.qty, 0)                                as qty,
  coalesce(l.dispatched_at, r.dispatched_at, l.created_at, r.created_at)
                                                    as moved_at,
  coalesce(nullif(l.dc_number, ''), r.or_no, '')    as ref,
  'Stores DC'::text                                 as ref_type,
  coalesce(r.uid, '')                               as ref_uid,
  coalesce(r.ucn, '')                               as ucn,
  coalesce(r.call_number, '')                       as call_number,
  coalesce(r.party_name, '')                        as party_name,
  coalesce(nullif(l.dispatch_remarks, ''), '')      as remarks
from public.spare_request_lines l
join public.spare_requests r on r.uid = l.request_uid
where coalesce(l.stores_status, '') ~* 'dispatch'
union all
-- 2. Consumption on a call (−)
select
  'OUT'::text, 'Consumption'::text,
  public.handstock_key(c.engineer),
  coalesce(c.engineer, ''),
  coalesce(c.engineer_email, ''),
  public.part_code(c.part),
  coalesce(c.part, ''),
  coalesce(c.qty, 0),
  c.created_at,
  coalesce(nullif(btrim(c.call_number), ''), coalesce(c.ucn, '')),
  'Call'::text,
  ''::text,
  coalesce(c.ucn, ''),
  coalesce(c.call_number, ''),
  ''::text,
  ''::text
from public.spare_consumption c
union all
-- 3. Stock transfer FROM this engineer (−)
select
  'OUT'::text, 'Transfer out'::text,
  public.handstock_key(t.from_engineer),
  coalesce(t.from_engineer, ''),
  ''::text,
  public.part_code(l.part),
  coalesce(l.part, ''),
  coalesce(l.qty, 0),
  coalesce(t.transfer_date::timestamptz, t.created_at),
  coalesce(t.uid, ''),
  'Transfer'::text,
  ''::text,
  ''::text,
  ''::text,
  coalesce(t.to_engineer, ''),                      -- who it went to
  coalesce(t.remarks, '')
from public.stock_transfer_lines l
join public.stock_transfers t on t.uid = l.transfer_uid
union all
-- 4. Stock transfer TO this engineer (+)
select
  'IN'::text, 'Transfer in'::text,
  public.handstock_key(t.to_engineer),
  coalesce(t.to_engineer, ''),
  ''::text,
  public.part_code(l.part),
  coalesce(l.part, ''),
  coalesce(l.qty, 0),
  coalesce(t.transfer_date::timestamptz, t.created_at),
  coalesce(t.uid, ''),
  'Transfer'::text,
  ''::text,
  ''::text,
  ''::text,
  coalesce(t.from_engineer, ''),                    -- who it came from
  coalesce(t.remarks, '')
from public.stock_transfer_lines l
join public.stock_transfers t on t.uid = l.transfer_uid;

-- ---------------------------------------------------------------------------
-- The stock level, one row per engineer + spare, with each term of the formula
-- kept separate so a figure can be argued with.
--
-- A negative level is not an error to hide: it means more was consumed or
-- handed on than this module has seen issued — stock carried from before the
-- register existed, or a spare taken without a DC.
-- ---------------------------------------------------------------------------
create or replace view public.handstock_balance as
select
  m.engineer_key,
  max(m.engineer)                                                       as engineer,
  max(m.engineer_email)                                                 as engineer_email,
  m.part_code,
  -- the catalogue string as the parts master spells it: prefer a Stores
  -- dispatch's, since a consumption row may carry an older wording.
  coalesce(max(m.part) filter (where m.movement = 'Stock out'), max(m.part))
                                                                        as part,
  sum(case when m.movement = 'Stock out'    then m.qty else 0 end)      as stock_out,
  sum(case when m.movement = 'Consumption'  then m.qty else 0 end)      as consumed,
  sum(case when m.movement = 'Transfer in'  then m.qty else 0 end)      as transferred_in,
  sum(case when m.movement = 'Transfer out' then m.qty else 0 end)      as transferred_out,
  sum(case when m.direction = 'IN' then m.qty else -m.qty end)          as on_hand,
  max(m.moved_at) filter (where m.direction = 'IN')                     as last_in,
  max(m.moved_at) filter (where m.direction = 'OUT')                    as last_out,
  max(m.moved_at)                                                       as last_movement,
  count(*)                                                              as movements
from public.handstock_movements m
where m.engineer_key <> '' and m.part_code <> ''
group by m.engineer_key, m.part_code;

-- ---------------------------------------------------------------------------
-- The Stock Transfer screen (and the guard that stops a transfer overdrawing)
-- read `engineer_stock`. Point it at the balance above rather than leaving a
-- second, differently-wrong derivation behind: same columns, same meaning, one
-- set of rules. `engineer_stock_available()` and both screens follow.
--
-- NB: definer-rights functions read this view, so it stays as 0020 created it
-- — NOT security_invoker.
-- ---------------------------------------------------------------------------
create or replace view public.engineer_stock as
select b.engineer_key as engineer, b.part, b.on_hand as qty
  from public.handstock_balance b;

grant select on public.engineer_stock to authenticated;

alter view public.handstock_movements set (security_invoker = on);
alter view public.handstock_balance   set (security_invoker = on);

grant select on public.handstock_movements to authenticated;
grant select on public.handstock_balance   to authenticated;

-- ---------------------------------------------------------------------------
-- Access. `mod:/handstock` is on no role until granted; append it —
-- additively — to every role that can already open the Spare Requests
-- register, leaving anything an admin has since edited alone.
-- (`stock.transfer` and `mod:/stock-transfer` belong to 0020_stock_transfer.)
-- ---------------------------------------------------------------------------
update public.app_roles
   set permissions = coalesce(permissions, '[]'::jsonb) || '["mod:/handstock"]'::jsonb,
       updated_at  = now()
 where coalesce(permissions, '[]'::jsonb) ? 'mod:/spare-requests'
   and not coalesce(permissions, '[]'::jsonb) ? 'mod:/handstock';

commit;

-- ===========================================================================
-- Reading a stock level back. Uncomment one and run it on its own.
-- ===========================================================================
--
-- 1. What is the field holding right now?
-- select engineer, part_code, part, stock_out, consumed,
--        transferred_in, transferred_out, on_hand
--   from public.handstock_balance
--  where on_hand > 0
--  order by engineer, part_code;
--
-- 2. One engineer's stock — what the report form's consumption picker offers
--    and what Stock Transfer will let them hand over.
-- select part, on_hand from public.handstock_balance
--  where engineer_key = lower(btrim('Engineer Name')) and on_hand > 0
--  order by part_code;
--
-- 3. Where a disputed level came from: every movement behind one line.
-- select moved_at, movement, qty, ref, ref_type, ucn, party_name, remarks
--   from public.handstock_movements
--  where engineer_key = lower(btrim('Engineer Name')) and part_code = 'SP-100'
--  order by moved_at desc;
--
-- 4. Short lines — consumed or handed on more than Stores ever issued.
-- select engineer, part_code, stock_out, consumed, transferred_out, on_hand
--   from public.handstock_balance where on_hand < 0 order by on_hand;
--
-- 5. Transfers, newest first (0020_stock_transfer.sql's tables).
-- select t.uid, t.transfer_date, t.from_engineer, t.to_engineer,
--        l.row_no, l.part, l.qty, t.remarks
--   from public.stock_transfer_lines l
--   join public.stock_transfers t on t.uid = l.transfer_uid
--  order by t.transfer_date desc, t.uid, l.row_no;
--
-- 6. Spares dispatched to an engineer and never consumed or handed on
--    (a spare sitting in a car long after the call closed).
-- select engineer, part_code, part, stock_out, on_hand, last_in
--   from public.handstock_balance
--  where on_hand > 0 and last_in < now() - interval '30 days'
--  order by last_in;
--
-- 7. Do the register and the transfer screen agree? (they read one view now)
-- select b.engineer_key, b.part_code, b.on_hand, e.qty
--   from public.handstock_balance b
--   join public.engineer_stock e on e.engineer = b.engineer_key and e.part = b.part
--  where b.on_hand <> e.qty;   -- expect no rows
