-- ===========================================================================
-- RITHI CRM — Call Requests & Call State: apply bundle
--
-- The Hotline request desk: a request is one row per call (Product + Serial +
-- Complaint + Reported Problem), closed out by mapping it to an existing call,
-- registering a new one, or cancelling it. Plus the call_state / pending_calls
-- views the Call Status column and the Pending Calls module read, and Call
-- Number assignment (the request UniqueID, or CLYY##### for a direct call).
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0008_calls_creator_read.sql
--   0010_call_request_items.sql
--   0011_call_request_actions.sql
--   0012_call_state.sql
--   0014_call_state_denorm.sql
--   0015_call_number.sql
--   0024_call_request_extra.sql
--   0032_call_state_by_entry.sql
--   0040_call_tables_split.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if to_regprocedure('public.visible_engineer_names()') is null then
    missing := array_append(missing, 'visible_engineer_names() — 0004_user_directory.sql (apply bundle: user_directory)');
  end if;
  if to_regclass('public.calls') is null then
    missing := array_append(missing, 'the calls table — 0001_init.sql');
  end if;
  if to_regclass('public.reports') is null then
    missing := array_append(missing, 'the reports table — 0001_init.sql');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0008_calls_creator_read.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Let a creator read back the call they just inserted (so insert...returning
-- works for everyone, not only admins). Fixes "new call saved locally / pending"
-- when the register is on Supabase.
-- ===========================================================================

drop policy if exists calls_scoped_read on public.calls;
create policy calls_scoped_read on public.calls for select
  using (public.can_see_call(allocated_to) or created_by = auth.uid());

drop policy if exists calls_update on public.calls;
create policy calls_update on public.calls for update
  using (public.can_see_call(allocated_to) or created_by = auth.uid())
  with check (public.can_see_call(allocated_to) or created_by = auth.uid());

-- ------------------------------------------------------------------------
-- 0010_call_request_items.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Multi-item call requests. A request is up to 5 calls (Product + Serial No +
-- Standard Complaint + Reported Problem) that SHARE one REQID, so REQID cannot
-- be unique — the per-row identity is UniqueID (REQID-Product-SerialNo).
--
-- Before this, inserting the 2nd..5th item failed with
--   duplicate key value violates unique constraint "call_requests_reqid_key"
-- leaving the request half-saved (item 1 only).
-- ===========================================================================

alter table public.call_requests drop constraint if exists call_requests_reqid_key;
create index if not exists call_requests_reqid_idx on public.call_requests (reqid);

-- The real identity: one row per product/serial within a request.
create unique index if not exists call_requests_unique_key_uidx
  on public.call_requests (unique_key);

-- Mint a REQID up front so the whole request goes in as ONE insert and can
-- never be half-saved. The trigger still assigns one when this isn't used.
create or replace function public.next_call_reqid()
returns text language sql security definer set search_path = public as $$
  select 'R' || nextval('public.call_req_seq')::text;
$$;
grant execute on function public.next_call_reqid() to authenticated;

-- ------------------------------------------------------------------------
-- 0011_call_request_actions.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call request actions (Hotline): a pending request is closed out in one of
-- three ways —
--   • Registered — a new call was created from it (UCN written back)
--   • Mapped     — it belongs to an existing call (that call's UCN written back)
--   • Cancelled  — not a call; reason recorded
-- A request leaves the pending list once it has a UCN or is cancelled.
-- ===========================================================================

alter table public.call_requests
  add column if not exists cancel_reason text default '',
  add column if not exists cancelled_at  timestamptz,
  add column if not exists actioned_by   text default '',
  add column if not exists actioned_at   timestamptz;

create index if not exists call_requests_status_idx on public.call_requests (status);

-- 0003 ships permissive insert/update policies; 0008 (RBAC enforcement)
-- replaces them with permission checks. Re-applying 0003 — which the
-- call_requests apply bundle does — would silently hand them back, so put the
-- RBAC versions back whenever has_perm() is present.
do $$
begin
  if to_regprocedure('public.has_perm(text)') is null then return; end if;

  execute 'drop policy if exists cr_insert on public.call_requests';
  execute $p$create policy cr_insert on public.call_requests for insert
    with check (public.has_perm('request.create'))$p$;

  execute 'drop policy if exists cr_update on public.call_requests';
  execute $p$create policy cr_update on public.call_requests for update
    using (public.has_perm('calls.create') or public.has_perm('pending.register') or created_by = auth.uid())
    with check (public.has_perm('calls.create') or public.has_perm('pending.register') or created_by = auth.uid())$p$;
end $$;

-- ------------------------------------------------------------------------
-- 0012_call_state.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call state = whether a call is still open, derived from its LATEST visit:
--   Unattended     — no visit reported yet
--   Unsolved       — last visit came back unsolved
--   Report pending — visit made, report not completed
--   Solved         — last visit closed it
-- `pending_calls` is every call that is not Solved (the Pending Calls module).
-- Both views run with the caller's rights, so calls/reports RLS still applies.
-- ===========================================================================

create or replace view public.call_state as
select
  c.ucn,
  coalesce(r.call_status, '')                        as last_status,
  r.visit_at                                         as last_visit_at,
  case
    when r.ucn is null                    then 'Unattended'
    when r.call_status ilike 'solved%'     then 'Solved'
    when r.call_status ilike '%unsolved%'  then 'Unsolved'
    else 'Report pending'
  end                                                as state
from public.calls c
left join lateral (
  select rr.ucn, rr.call_status, rr.visit_at
  from public.reports rr
  where rr.ucn = c.ucn
  order by rr.visit_at desc nulls last, rr.id desc
  limit 1
) r on true;

-- NB: `calls` already has a `state` column (the geographic one), so the call's
-- open state is exposed here as `open_state`.
--
-- Skipped once 0014_call_state_denorm.sql has run: that migration denormalises
-- open_state onto `calls` itself and rebuilds this view against it. After that,
-- `c.*` here already carries open_state and aliasing s.state to the same name
-- collides ("column open_state ... already exists"), which broke re-running
-- this file. 0014's definition supersedes this one, so skipping is a no-op.
do $$
begin
  if exists (select 1 from information_schema.columns
              where table_schema = 'public' and table_name = 'calls'
                and column_name = 'open_state') then
    return;
  end if;

  create or replace view public.pending_calls as
  select c.*, s.state as open_state, s.last_status, s.last_visit_at
  from public.calls c
  join public.call_state s on s.ucn = c.ucn
  where s.state <> 'Solved';

  execute 'alter view public.pending_calls set (security_invoker = on)';
  execute 'grant select on public.pending_calls to authenticated';
end $$;

alter view public.call_state set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0014_call_state_denorm.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call state, without re-deriving it on every read.
--
-- 0012 computed a call's state from its latest visit in a view. Correct, but
-- reading it meant scanning `reports` through that table's RLS — a correlated
-- subquery plus can_see_call() per report row. At 11k calls / 17k reports that
-- is ~37ms without RLS and >5s with it: "canceling statement due to statement
-- timeout".
--
-- The latest visit is now kept ON the call, maintained by a trigger on
-- `reports`. Reads touch `calls` only — the register already loads it, so the
-- state comes along for free, and Pending Calls is an indexed filter.
-- ===========================================================================

-- The 0012 views read the columns below, and one of them is recreated with a
-- different shape, so they go first.
drop view if exists public.pending_calls;
drop view if exists public.call_state;

alter table public.calls
  add column if not exists last_status   text default '',
  add column if not exists last_visit_at timestamptz;

-- Derived, so it can never drift from the two columns above.
alter table public.calls drop column if exists open_state;
alter table public.calls add column open_state text
  generated always as (
    case
      when last_visit_at is null and coalesce(last_status, '') = '' then 'Unattended'
      when lower(coalesce(last_status, '')) like 'solved%'          then 'Solved'
      when lower(coalesce(last_status, '')) like '%unsolved%'       then 'Unsolved'
      else 'Report pending'
    end
  ) stored;

create index if not exists calls_open_idx on public.calls (open_state) where open_state <> 'Solved';

-- ---- keep it current -------------------------------------------------------
-- security definer: a visit by one engineer updates the call regardless of who
-- may write `calls`.
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.calls c
     set last_status   = coalesce(r.call_status, ''),
         last_visit_at = r.visit_at
    from (
      select call_status, visit_at
        from public.reports
       where ucn = p_ucn
       order by visit_at desc nulls last, id desc
       limit 1
    ) r
   where c.ucn = p_ucn;

  if not found then  -- no visits left (or none matched): back to Unattended
    update public.calls set last_status = '', last_visit_at = null where ucn = p_ucn;
  end if;
end $$;

create or replace function public.reports_touch_call()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.sync_call_last_visit(coalesce(new.ucn, old.ucn));
  if tg_op = 'UPDATE' and new.ucn is distinct from old.ucn then
    perform public.sync_call_last_visit(old.ucn);
  end if;
  return null;
end $$;

drop trigger if exists reports_touch_call on public.reports;
create trigger reports_touch_call after insert or update or delete on public.reports
  for each row execute function public.reports_touch_call();

-- ---- backfill --------------------------------------------------------------
update public.calls c
   set last_status   = coalesce(r.call_status, ''),
       last_visit_at = r.visit_at
  from (
    select distinct on (ucn) ucn, call_status, visit_at
      from public.reports
     order by ucn, visit_at desc nulls last, id desc
  ) r
 where r.ucn = c.ucn
   and (c.last_status is distinct from coalesce(r.call_status, '')
     or c.last_visit_at is distinct from r.visit_at);

-- ---- views, now trivial ----------------------------------------------------
-- `calls` already carries `state` (the geographic one), so the call's open
-- state stays `open_state` here too.
create view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;

create view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';

alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0015_call_number.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call Number.
--
--   • From a call registration request → the request's UniqueID
--     (REQID-Product-SerialNo), carried over when the Hotline registers it.
--   • Direct customer call (no request) → CLYY + a 5-digit running number,
--     e.g. CL2600001, continuing the existing series for that year
--     (the register already holds CL2300081, CL2300079, …).
--
-- It was a free-text field nobody filled, so a hand-created call could be
-- saved with a blank Call Number — and reports, spare requests, consumption
-- and feedback are all keyed by it.
-- ===========================================================================

create table if not exists public.call_number_seq (
  yy      text primary key,          -- two-digit year
  last_no integer not null default 0
);
alter table public.call_number_seq enable row level security;  -- only the definer function touches it

-- Next CL number for a year. The counter is seeded once, from the numbers
-- already in `calls` — so import historical CL numbers BEFORE this runs (or
-- delete that year's `call_number_seq` row afterwards to re-seed).
-- Next CL number for this year. The year's counter is seeded from the highest
-- CLYY##### already in `calls`, so it continues the series instead of
-- colliding with imported history.
create or replace function public.next_direct_call_number(p_yy text default null)
returns text language plpgsql security definer set search_path = public as $$
declare
  v_yy text := coalesce(nullif(p_yy, ''), to_char(current_date, 'YY'));
  v_no int;
begin
  insert into public.call_number_seq (yy, last_no)
  values (v_yy, coalesce((
    select max(substring(call_number from 5 for 5)::int)
      from public.calls
     where call_number ~ ('^CL' || v_yy || '[0-9]{5}')), 0))
  on conflict (yy) do nothing;

  update public.call_number_seq set last_no = last_no + 1
   where yy = v_yy
   returning last_no into v_no;

  return 'CL' || v_yy || lpad(v_no::text, 5, '0');
end $$;

-- Assign one when the call arrives without a Call Number. A call registered
-- from a request carries the request's UniqueID, so this only fires for direct
-- calls (and for any import row that has none).
create or replace function public.calls_before_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.ucn is null or new.ucn = '' then
    new.ucn := public.next_ucn(new.call_type);
  end if;
  if coalesce(new.call_number, '') = '' then
    new.call_number := public.next_direct_call_number(to_char(coalesce(new.reg_date, current_date), 'YY'));
  end if;
  if new.reg_date is null then new.reg_date := current_date; end if;
  if new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end $$;

drop trigger if exists calls_biu on public.calls;
create trigger calls_biu before insert on public.calls
  for each row execute function public.calls_before_insert();

-- Back-fill calls saved before this with no Call Number, each in its own year's
-- series (a call registered in 2025 gets a CL25 number, not a CL26 one).
do $$
declare r record;
begin
  for r in select id, reg_date from public.calls where coalesce(call_number, '') = '' order by id loop
    update public.calls
       set call_number = public.next_direct_call_number(to_char(coalesce(r.reg_date, current_date), 'YY'))
     where id = r.id;
  end loop;
end $$;

grant execute on function public.next_direct_call_number(text) to authenticated;

-- ------------------------------------------------------------------------
-- 0024_call_request_extra.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- `extra` on call_requests, so the historical CRN Registration export can be
-- imported without losing the columns the table has no home for — "Any Open
-- Call?" (the Hotline's answer at the time, either No or the open call's UCN),
-- Regional Manager, and Comments / Remarks.
-- ===========================================================================

alter table public.call_requests
  add column if not exists extra jsonb not null default '{}'::jsonb;

-- ------------------------------------------------------------------------
-- 0032_call_state_by_entry.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call status: Unattended until a visit is entered, then the status of the
-- LATEST VISIT ENTRY — latest by when the visit was ENTERED, not by the visit
-- date the engineer typed.
--
-- Two fixes:
--
-- 1) `sync_call_last_visit` picked the latest visit by `visit_at` (the Visit
--    Date field). A visit entered today for a call visited last week then lost
--    to an older entry with a later visit date. The entry timestamp is
--    `reports.updated_at` (set when the row is written), so order by that and
--    fall back to `id` — which also orders the sheet-era rows, whose
--    updated_at is their import time. `last_visit_at` still carries the visit
--    DATE; only the choice of row changes.
--
-- 2) `open_state` tested `like 'solved%'` first, so the "Solved - Report
--    Pending" status introduced with the report field spec read as Solved and
--    dropped the call off Pending Calls. Unsolved and report-pending are now
--    tested before solved.
-- ===========================================================================

-- The views read open_state, and it is recreated below.
drop view if exists public.pending_calls;
drop view if exists public.call_state;

alter table public.calls drop column if exists open_state;
alter table public.calls add column open_state text
  generated always as (
    case
      when last_visit_at is null and coalesce(last_status, '') = ''   then 'Unattended'
      when lower(coalesce(last_status, '')) like '%unsolved%'         then 'Unsolved'
      when lower(coalesce(last_status, '')) like '%report pending%'   then 'Report pending'
      when lower(coalesce(last_status, '')) like 'solved%'            then 'Solved'
      else 'Report pending'
    end
  ) stored;

create index if not exists calls_open_idx on public.calls (open_state) where open_state <> 'Solved';

-- ---- latest = latest ENTRY -------------------------------------------------
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.calls c
     set last_status   = coalesce(r.call_status, ''),
         last_visit_at = r.visit_at
    from (
      select call_status, visit_at
        from public.reports
       where ucn = p_ucn
       order by updated_at desc nulls last, id desc
       limit 1
    ) r
   where c.ucn = p_ucn;

  if not found then  -- no visits left (or none matched): back to Unattended
    update public.calls set last_status = '', last_visit_at = null where ucn = p_ucn;
  end if;
end $$;

-- ---- re-backfill on the new rule ------------------------------------------
update public.calls c
   set last_status   = coalesce(r.call_status, ''),
       last_visit_at = r.visit_at
  from (
    select distinct on (ucn) ucn, call_status, visit_at
      from public.reports
     order by ucn, updated_at desc nulls last, id desc
  ) r
 where r.ucn = c.ucn
   and (c.last_status is distinct from coalesce(r.call_status, '')
     or c.last_visit_at is distinct from r.visit_at);

-- A call whose reports have all gone is Unattended again.
update public.calls c
   set last_status = '', last_visit_at = null
 where (coalesce(c.last_status, '') <> '' or c.last_visit_at is not null)
   and not exists (select 1 from public.reports r where r.ucn = c.ucn);

-- ---- views -----------------------------------------------------------------
create view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;

create view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';

alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0040_call_tables_split.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Split `calls` into three physical tables: field_calls, installation_calls,
-- pm_calls — so PM's bulk (15–18k/yr) lives in its own table and never bloats
-- the others. Non-breaking: `calls` becomes a UNION-ALL VIEW over the three,
-- with INSTEAD OF triggers routing every write to the right table, so all
-- existing code (addCall / updateCall / bulkInsert('calls') / the reports
-- last-visit sync / the pending_calls & call_state views) keeps working
-- unchanged. Stage 2 will point the registers at the typed tables directly.
--
-- There are NO foreign keys into calls (associations link by ucn/call_number
-- value only), so replacing the table with a view breaks no constraint.
--
-- Idempotent: the one-time structural split is guarded on field_calls not yet
-- existing; the views / triggers / policies are create-or-replace and re-run
-- safely.
-- ===========================================================================

-- Which physical table a call_type belongs to. Robust to 'P M VISIT' (spaces)
-- and 'INSTALLATION CALL'. Immutable so it can drive routing and checks.
create or replace function public.call_table_for(p_type text)
returns text language sql immutable set search_path = public as $$
  select case
    when upper(coalesce(p_type, '')) like 'INSTALL%'                     then 'installation'
    when upper(replace(coalesce(p_type, ''), ' ', '')) like 'PM%'        then 'pm'
    else 'field'
  end;
$$;

-- Fix next_ucn's PM detection to match (a 'P M VISIT' UCN should start with P).
create or replace function public.next_ucn(p_call_type text)
returns text language plpgsql volatile security definer set search_path = public as $$
declare
  yy      text := to_char(now(), 'YY');
  mon     text := substr('ABCDEFGHIJKL', extract(month from now())::int, 1);
  dd      text := to_char(now(), 'DD');
  tletter text := case public.call_table_for(p_call_type)
                    when 'installation' then 'I'
                    when 'pm'           then 'P'
                    else 'F'
                  end;
  seq     int  := nextval('public.ucn_seq');
begin
  return yy || mon || dd || tletter || lpad(seq::text, 4, '0');
end;
$$;

-- ---- one-time structural split --------------------------------------------
do $$
declare cols text;
begin
  if to_regclass('public.field_calls') is not null then return; end if;      -- already split

  -- A single id space shared across the three tables, so the union view's id
  -- stays unique. Continue past the highest existing id.
  create sequence if not exists public.call_split_id_seq;
  perform setval('public.call_split_id_seq', coalesce((select max(id) from public.calls), 0) + 1, false);

  -- Three tables cloned from the current calls shape (columns, the generated
  -- open_state, defaults, the ucn-unique and allocated/serial/open indexes).
  create table public.field_calls        (like public.calls including all);
  create table public.installation_calls (like public.calls including all);
  create table public.pm_calls           (like public.calls including all);

  -- id: drop the per-table identity LIKE copied, use the shared sequence.
  alter table public.field_calls        alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');
  alter table public.installation_calls alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');
  alter table public.pm_calls           alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');

  -- created_by FK parity (LIKE never copies foreign keys).
  alter table public.field_calls        add constraint field_calls_created_by_fkey        foreign key (created_by) references auth.users(id);
  alter table public.installation_calls add constraint installation_calls_created_by_fkey foreign key (created_by) references auth.users(id);
  alter table public.pm_calls           add constraint pm_calls_created_by_fkey           foreign key (created_by) references auth.users(id);

  -- Copy existing rows into their table by type. All non-generated columns
  -- (this list excludes the generated open_state, which recomputes itself).
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'calls' and is_generated = 'NEVER';

  execute format('insert into public.field_calls (%1$s)        select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'field');
  execute format('insert into public.installation_calls (%1$s) select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'installation');
  execute format('insert into public.pm_calls (%1$s)           select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'pm');

  -- Drop the views and the reports policy that depend on the table, then the
  -- table itself (this also drops its calls_biu trigger and its RLS policies).
  drop view if exists public.pending_calls;
  drop view if exists public.call_state;
  drop policy if exists reports_read on public.reports;   -- references public.calls; recreated below over the view
  drop table public.calls;
end $$;

-- ---- per-table write trigger (ucn / call_number / reg_date / created_by) ---
-- calls_before_insert() already exists (0015); attach it to each base table.
drop trigger if exists calls_biu on public.field_calls;
create trigger calls_biu before insert on public.field_calls        for each row execute function public.calls_before_insert();
drop trigger if exists calls_biu on public.installation_calls;
create trigger calls_biu before insert on public.installation_calls for each row execute function public.calls_before_insert();
drop trigger if exists calls_biu on public.pm_calls;
create trigger calls_biu before insert on public.pm_calls           for each row execute function public.calls_before_insert();

-- ---- the compatibility view ------------------------------------------------
create or replace view public.calls as
  select * from public.field_calls
  union all select * from public.installation_calls
  union all select * from public.pm_calls;
alter view public.calls set (security_invoker = on);
grant select, insert, update, delete on public.calls to authenticated;
grant select, insert, update, delete on public.field_calls, public.installation_calls, public.pm_calls to authenticated;
grant usage on sequence public.call_split_id_seq to authenticated;   -- id default is nextval(); insert needs it

-- INSTEAD OF triggers route writes and (on insert) write the trigger-assigned
-- ucn / call_number / id / open_state back onto NEW so `insert … returning *`
-- gives the caller the real UCN.
do $$
declare ins_cols text; ins_vals text; set_list text;
begin
  -- INSERT omits id (shared-sequence default). For every other column, fall
  -- back to the base-table default when the caller didn't supply it, so an
  -- omitted column (NEW is null on a view insert) still gets '' / '{}' / now()
  -- / 'Registered' rather than a null that breaks NOT NULL or loses the default.
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position),
         string_agg(
           case when column_default is not null
                then format('coalesce(new.%I, %s)', column_name, column_default)
                else 'new.' || quote_ident(column_name) end,
           ', ' order by ordinal_position),
         string_agg(quote_ident(column_name) || ' = new.' || quote_ident(column_name), ', ' order by ordinal_position)
    into ins_cols, ins_vals, set_list
    from information_schema.columns
   where table_schema = 'public' and table_name = 'field_calls'
     and is_generated = 'NEVER' and column_name <> 'id';

  execute format($f$
    create or replace function public.calls_view_insert() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(new.call_type)
        when 'installation' then
          insert into public.installation_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
        when 'pm' then
          insert into public.pm_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
        else
          insert into public.field_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
      end case;
      return new;
    end $b$;
  $f$, ins_cols, ins_vals);

  execute format($f$
    create or replace function public.calls_view_update() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(old.call_type)
        when 'installation' then update public.installation_calls set %1$s where ucn = old.ucn;
        when 'pm'           then update public.pm_calls           set %1$s where ucn = old.ucn;
        else                     update public.field_calls        set %1$s where ucn = old.ucn;
      end case;
      return new;
    end $b$;
  $f$, set_list);
end $$;

create or replace function public.calls_view_delete() returns trigger language plpgsql as $$
begin
  case public.call_table_for(old.call_type)
    when 'installation' then delete from public.installation_calls where ucn = old.ucn;
    when 'pm'           then delete from public.pm_calls           where ucn = old.ucn;
    else                     delete from public.field_calls        where ucn = old.ucn;
  end case;
  return old;
end $$;

drop trigger if exists calls_view_ins on public.calls;
create trigger calls_view_ins instead of insert on public.calls for each row execute function public.calls_view_insert();
drop trigger if exists calls_view_upd on public.calls;
create trigger calls_view_upd instead of update on public.calls for each row execute function public.calls_view_update();
drop trigger if exists calls_view_del on public.calls;
create trigger calls_view_del instead of delete on public.calls for each row execute function public.calls_view_delete();

-- ---- the last-visit sync now targets the base tables -----------------------
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
declare v_status text; v_at timestamptz;
begin
  select call_status, visit_at into v_status, v_at
    from public.reports where ucn = p_ucn
   order by updated_at desc nulls last, id desc limit 1;   -- null when no visits → Unattended
  update public.field_calls        set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
  update public.installation_calls set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
  update public.pm_calls           set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
end $$;

-- ---- rebuild the derived views over the union ------------------------------
create or replace view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;
create or replace view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';
alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);
grant select on public.call_state, public.pending_calls to authenticated;

-- reports_read reads calls (now the view) to scope a visit by its parent call.
drop policy if exists reports_read on public.reports;
create policy reports_read on public.reports for select
  using (
    (select public.is_admin())
    or (
      (select public.has_perm('calls.view'))
      and (
        (select public.can_view_all_calls())
        or exists (
          select 1 from public.calls c
           where c.ucn = reports.ucn
             and (
               coalesce(c.allocated_to, '') = ''
               or lower(trim(c.allocated_to)) in (
                    select lower(trim(n)) from public.visible_engineer_names() as v(n))
             )
        )
      )
    )
  );

-- ---- RLS: the same three policies (0037 read/update, rbac insert) per table -
do $$
declare t text; vis text;
begin
  -- The shared "may I see this call" test, inlined so the reporting-tree set is
  -- an InitPlan built once (the 0037 shape).
  vis := $v$ (select public.can_view_all_calls())
             or created_by = (select auth.uid())
             or coalesce(allocated_to, '') = ''
             or lower(trim(allocated_to)) in (select lower(trim(n)) from public.visible_engineer_names() as v(n)) $v$;
  foreach t in array array['field_calls', 'installation_calls', 'pm_calls'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists calls_scoped_read on public.%I', t);
    execute format('create policy calls_scoped_read on public.%I for select using ((select public.has_perm(''calls.view'')) and (%s))', t, vis);
    execute format('drop policy if exists calls_insert on public.%I', t);
    execute format('create policy calls_insert on public.%I for insert with check (public.has_perm(''calls.create''))', t);
    execute format('drop policy if exists calls_update on public.%I', t);
    execute format('create policy calls_update on public.%1$I for update using ((select (public.has_perm(''calls.edit'') or public.has_perm(''calls.report''))) and (%2$s)) with check ((select (public.has_perm(''calls.edit'') or public.has_perm(''calls.report''))) and (%2$s))', t, vis);
  end loop;
end $$;

commit;
