-- ===========================================================================
-- RITHI CRM — Call Requests & Call State: apply bundle
--
-- The Hotline request desk: a request is one row per call (Product + Serial +
-- Complaint + Reported Problem), closed out by mapping it to an existing call,
-- registering a new one, or cancelling it. Plus the call_state / pending_calls
-- views the Call Status column and the Pending Calls module read, and Call
-- Number assignment (the request UniqueID, or CLYY##### for a direct call).
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0008_calls_creator_read.sql
--   0010_call_request_items.sql
--   0011_call_request_actions.sql
--   0012_call_state.sql
--   0014_call_state_denorm.sql
--   0015_call_number.sql
--   0024_call_request_extra.sql
--   0032_call_state_by_entry.sql
--   0040_call_tables_split.sql
--   0041_call_split_hardening.sql
--   0043_installation_create_gate.sql
--   0050_pm_schedule_fields.sql
--   0053_call_requests_view_all.sql
--   0057_call_reopen.sql
--   0058_close_reopened_call.sql
--   0083_request_status_from_ucn.sql
--   0097_call_reqid_continues.sql
--   0104_complaint_suggestions.sql
--   0105_calls_view_security_invoker.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if to_regprocedure('public.visible_engineer_names()') is null then
    missing := array_append(missing, 'visible_engineer_names() — 0004_user_directory.sql (apply bundle: user_directory)');
  end if;
  if to_regclass('public.calls') is null then
    missing := array_append(missing, 'the calls table — 0001_init.sql');
  end if;
  if to_regclass('public.reports') is null then
    missing := array_append(missing, 'the reports table — 0001_init.sql');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0008_calls_creator_read.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Let a creator read back the call they just inserted (so insert...returning
-- works for everyone, not only admins). Fixes "new call saved locally / pending"
-- when the register is on Supabase.
-- ===========================================================================

do $calls_guard$ begin
-- 0040_call_tables_split.sql replaces public.calls with a VIEW over the three
-- typed call tables. What follows is table-only work, so on a project that has
-- already been split it has to be SKIPPED, not attempted — otherwise replaying
-- this file (which re-running any bundle does) dies with
--   ERROR 42809: cannot create index on relation "calls"
-- or "calls is not a table". On an unsplit project it runs exactly as before.
if (select c.relkind from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relname = 'calls') = 'r' then
execute $calls_sql$
drop policy if exists calls_scoped_read on public.calls;
create policy calls_scoped_read on public.calls for select
  using (public.can_see_call(allocated_to) or created_by = auth.uid());

drop policy if exists calls_update on public.calls;
create policy calls_update on public.calls for update
  using (public.can_see_call(allocated_to) or created_by = auth.uid())
  with check (public.can_see_call(allocated_to) or created_by = auth.uid());
$calls_sql$;
end if;
end $calls_guard$;

-- ------------------------------------------------------------------------
-- 0010_call_request_items.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Multi-item call requests. A request is up to 5 calls (Product + Serial No +
-- Standard Complaint + Reported Problem) that SHARE one REQID, so REQID cannot
-- be unique — the per-row identity is UniqueID (REQID-Product-SerialNo).
--
-- Before this, inserting the 2nd..5th item failed with
--   duplicate key value violates unique constraint "call_requests_reqid_key"
-- leaving the request half-saved (item 1 only).
-- ===========================================================================

alter table public.call_requests drop constraint if exists call_requests_reqid_key;
create index if not exists call_requests_reqid_idx on public.call_requests (reqid);

-- The real identity: one row per product/serial within a request.
create unique index if not exists call_requests_unique_key_uidx
  on public.call_requests (unique_key);

-- Mint a REQID up front so the whole request goes in as ONE insert and can
-- never be half-saved. The trigger still assigns one when this isn't used.
create or replace function public.next_call_reqid()
returns text language sql security definer set search_path = public as $$
  select 'R' || nextval('public.call_req_seq')::text;
$$;
grant execute on function public.next_call_reqid() to authenticated;

-- ------------------------------------------------------------------------
-- 0011_call_request_actions.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call request actions (Hotline): a pending request is closed out in one of
-- three ways —
--   • Registered — a new call was created from it (UCN written back)
--   • Mapped     — it belongs to an existing call (that call's UCN written back)
--   • Cancelled  — not a call; reason recorded
-- A request leaves the pending list once it has a UCN or is cancelled.
-- ===========================================================================

alter table public.call_requests
  add column if not exists cancel_reason text default '',
  add column if not exists cancelled_at  timestamptz,
  add column if not exists actioned_by   text default '',
  add column if not exists actioned_at   timestamptz;

create index if not exists call_requests_status_idx on public.call_requests (status);

-- 0003 ships permissive insert/update policies; 0008 (RBAC enforcement)
-- replaces them with permission checks. Re-applying 0003 — which the
-- call_requests apply bundle does — would silently hand them back, so put the
-- RBAC versions back whenever has_perm() is present.
do $$
begin
  if to_regprocedure('public.has_perm(text)') is null then return; end if;

  execute 'drop policy if exists cr_insert on public.call_requests';
  execute $p$create policy cr_insert on public.call_requests for insert
    with check (public.has_perm('request.create'))$p$;

  execute 'drop policy if exists cr_update on public.call_requests';
  execute $p$create policy cr_update on public.call_requests for update
    using (public.has_perm('calls.create') or public.has_perm('pending.register') or created_by = auth.uid())
    with check (public.has_perm('calls.create') or public.has_perm('pending.register') or created_by = auth.uid())$p$;
end $$;

-- ------------------------------------------------------------------------
-- 0012_call_state.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call state = whether a call is still open, derived from its LATEST visit:
--   Unattended     — no visit reported yet
--   Unsolved       — last visit came back unsolved
--   Report pending — visit made, report not completed
--   Solved         — last visit closed it
-- `pending_calls` is every call that is not Solved (the Pending Calls module).
-- Both views run with the caller's rights, so calls/reports RLS still applies.
-- ===========================================================================

-- Guarded for the same reason the pending_calls block below is: once
-- 0014_call_state_denorm.sql has run, IT owns this view and has since grown
-- columns (reopened_at / reopen_count, 0057). `create or replace view` cannot
-- drop columns, so re-running this file over a fully-migrated project failed
-- with "cannot drop columns from view" and took the rest of all.sql down with
-- it. 0014's definition supersedes this one, so skipping is a no-op.
do $cs$
begin
  if exists (select 1 from information_schema.columns
              where table_schema = 'public' and table_name = 'calls'
                and column_name = 'open_state') then
    return;
  end if;

  execute $view$
    create or replace view public.call_state as
    select
      c.ucn,
      coalesce(r.call_status, '')                        as last_status,
      r.visit_at                                         as last_visit_at,
      case
        when r.ucn is null                    then 'Unattended'
        when r.call_status ilike 'solved%'     then 'Solved'
        when r.call_status ilike '%unsolved%'  then 'Unsolved'
        else 'Report pending'
      end                                                as state
    from public.calls c
    left join lateral (
      select rr.ucn, rr.call_status, rr.visit_at
      from public.reports rr
      where rr.ucn = c.ucn
      order by rr.visit_at desc nulls last, rr.id desc
      limit 1
    ) r on true
  $view$;
end $cs$;

-- NB: `calls` already has a `state` column (the geographic one), so the call's
-- open state is exposed here as `open_state`.
--
-- Skipped once 0014_call_state_denorm.sql has run: that migration denormalises
-- open_state onto `calls` itself and rebuilds this view against it. After that,
-- `c.*` here already carries open_state and aliasing s.state to the same name
-- collides ("column open_state ... already exists"), which broke re-running
-- this file. 0014's definition supersedes this one, so skipping is a no-op.
do $$
begin
  if exists (select 1 from information_schema.columns
              where table_schema = 'public' and table_name = 'calls'
                and column_name = 'open_state') then
    return;
  end if;

  create or replace view public.pending_calls as
  select c.*, s.state as open_state, s.last_status, s.last_visit_at
  from public.calls c
  join public.call_state s on s.ucn = c.ucn
  where s.state <> 'Solved';

  execute 'alter view public.pending_calls set (security_invoker = on)';
  execute 'grant select on public.pending_calls to authenticated';
end $$;

-- Both views exist by now either way (this file's, or 0014's), so these are
-- safe; guarded only against a partial state where pending_calls is absent.
alter view public.call_state set (security_invoker = on);

grant select on public.call_state    to authenticated;
do $g$ begin
  if to_regclass('public.pending_calls') is not null then
    grant select on public.pending_calls to authenticated;
  end if;
end $g$;

-- ------------------------------------------------------------------------
-- 0014_call_state_denorm.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call state, without re-deriving it on every read.
--
-- 0012 computed a call's state from its latest visit in a view. Correct, but
-- reading it meant scanning `reports` through that table's RLS — a correlated
-- subquery plus can_see_call() per report row. At 11k calls / 17k reports that
-- is ~37ms without RLS and >5s with it: "canceling statement due to statement
-- timeout".
--
-- The latest visit is now kept ON the call, maintained by a trigger on
-- `reports`. Reads touch `calls` only — the register already loads it, so the
-- state comes along for free, and Pending Calls is an indexed filter.
-- ===========================================================================

-- The 0012 views read the columns below, and one of them is recreated with a
-- different shape, so they go first.
drop view if exists public.pending_calls;
drop view if exists public.call_state;

do $calls_guard$ begin
-- 0040_call_tables_split.sql replaces public.calls with a VIEW over the three
-- typed call tables. What follows is table-only work, so on a project that has
-- already been split it has to be SKIPPED, not attempted — otherwise replaying
-- this file (which re-running any bundle does) dies with
--   ERROR 42809: cannot create index on relation "calls"
-- or "calls is not a table". On an unsplit project it runs exactly as before.
if (select c.relkind from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relname = 'calls') = 'r' then
execute $calls_sql$
alter table public.calls
  add column if not exists last_status   text default '',
  add column if not exists last_visit_at timestamptz;

-- Derived, so it can never drift from the two columns above.
alter table public.calls drop column if exists open_state;
alter table public.calls add column open_state text
  generated always as (
    case
      when last_visit_at is null and coalesce(last_status, '') = '' then 'Unattended'
      when lower(coalesce(last_status, '')) like 'solved%'          then 'Solved'
      when lower(coalesce(last_status, '')) like '%unsolved%'       then 'Unsolved'
      else 'Report pending'
    end
  ) stored;

create index if not exists calls_open_idx on public.calls (open_state) where open_state <> 'Solved';
$calls_sql$;
end if;
end $calls_guard$;

-- ---- keep it current -------------------------------------------------------
-- security definer: a visit by one engineer updates the call regardless of who
-- may write `calls`.
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.calls c
     set last_status   = coalesce(r.call_status, ''),
         last_visit_at = r.visit_at
    from (
      select call_status, visit_at
        from public.reports
       where ucn = p_ucn
       order by visit_at desc nulls last, id desc
       limit 1
    ) r
   where c.ucn = p_ucn;

  if not found then  -- no visits left (or none matched): back to Unattended
    update public.calls set last_status = '', last_visit_at = null where ucn = p_ucn;
  end if;
end $$;

create or replace function public.reports_touch_call()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.sync_call_last_visit(coalesce(new.ucn, old.ucn));
  if tg_op = 'UPDATE' and new.ucn is distinct from old.ucn then
    perform public.sync_call_last_visit(old.ucn);
  end if;
  return null;
end $$;

drop trigger if exists reports_touch_call on public.reports;
create trigger reports_touch_call after insert or update or delete on public.reports
  for each row execute function public.reports_touch_call();

-- ---- backfill --------------------------------------------------------------
update public.calls c
   set last_status   = coalesce(r.call_status, ''),
       last_visit_at = r.visit_at
  from (
    select distinct on (ucn) ucn, call_status, visit_at
      from public.reports
     order by ucn, visit_at desc nulls last, id desc
  ) r
 where r.ucn = c.ucn
   and (c.last_status is distinct from coalesce(r.call_status, '')
     or c.last_visit_at is distinct from r.visit_at);

-- ---- views, now trivial ----------------------------------------------------
-- `calls` already carries `state` (the geographic one), so the call's open
-- state stays `open_state` here too.
create view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;

create view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';

alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0015_call_number.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call Number.
--
--   • From a call registration request → the request's UniqueID
--     (REQID-Product-SerialNo), carried over when the Hotline registers it.
--   • Direct customer call (no request) → CLYY + a 5-digit running number,
--     e.g. CL2600001, continuing the existing series for that year
--     (the register already holds CL2300081, CL2300079, …).
--
-- It was a free-text field nobody filled, so a hand-created call could be
-- saved with a blank Call Number — and reports, spare requests, consumption
-- and feedback are all keyed by it.
-- ===========================================================================

create table if not exists public.call_number_seq (
  yy      text primary key,          -- two-digit year
  last_no integer not null default 0
);
alter table public.call_number_seq enable row level security;  -- only the definer function touches it

-- Next CL number for a year. The counter is seeded once, from the numbers
-- already in `calls` — so import historical CL numbers BEFORE this runs (or
-- delete that year's `call_number_seq` row afterwards to re-seed).
-- Next CL number for this year. The year's counter is seeded from the highest
-- CLYY##### already in `calls`, so it continues the series instead of
-- colliding with imported history.
create or replace function public.next_direct_call_number(p_yy text default null)
returns text language plpgsql security definer set search_path = public as $$
declare
  v_yy text := coalesce(nullif(p_yy, ''), to_char(current_date, 'YY'));
  v_no int;
begin
  insert into public.call_number_seq (yy, last_no)
  values (v_yy, coalesce((
    select max(substring(call_number from 5 for 5)::int)
      from public.calls
     where call_number ~ ('^CL' || v_yy || '[0-9]{5}')), 0))
  on conflict (yy) do nothing;

  update public.call_number_seq set last_no = last_no + 1
   where yy = v_yy
   returning last_no into v_no;

  return 'CL' || v_yy || lpad(v_no::text, 5, '0');
end $$;

-- Assign one when the call arrives without a Call Number. A call registered
-- from a request carries the request's UniqueID, so this only fires for direct
-- calls (and for any import row that has none).
create or replace function public.calls_before_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.ucn is null or new.ucn = '' then
    new.ucn := public.next_ucn(new.call_type);
  end if;
  if coalesce(new.call_number, '') = '' then
    new.call_number := public.next_direct_call_number(to_char(coalesce(new.reg_date, current_date), 'YY'));
  end if;
  if new.reg_date is null then new.reg_date := current_date; end if;
  if new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end $$;

do $calls_guard$ begin
-- 0040_call_tables_split.sql replaces public.calls with a VIEW over the three
-- typed call tables. What follows is table-only work, so on a project that has
-- already been split it has to be SKIPPED, not attempted — otherwise replaying
-- this file (which re-running any bundle does) dies with
--   ERROR 42809: cannot create index on relation "calls"
-- or "calls is not a table". On an unsplit project it runs exactly as before.
if (select c.relkind from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relname = 'calls') = 'r' then
execute $calls_sql$
drop trigger if exists calls_biu on public.calls;
create trigger calls_biu before insert on public.calls
  for each row execute function public.calls_before_insert();
$calls_sql$;
end if;
end $calls_guard$;

-- Back-fill calls saved before this with no Call Number, each in its own year's
-- series (a call registered in 2025 gets a CL25 number, not a CL26 one).
do $$
declare r record;
begin
  for r in select id, reg_date from public.calls where coalesce(call_number, '') = '' order by id loop
    update public.calls
       set call_number = public.next_direct_call_number(to_char(coalesce(r.reg_date, current_date), 'YY'))
     where id = r.id;
  end loop;
end $$;

grant execute on function public.next_direct_call_number(text) to authenticated;

-- ------------------------------------------------------------------------
-- 0024_call_request_extra.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- `extra` on call_requests, so the historical CRN Registration export can be
-- imported without losing the columns the table has no home for — "Any Open
-- Call?" (the Hotline's answer at the time, either No or the open call's UCN),
-- Regional Manager, and Comments / Remarks.
-- ===========================================================================

alter table public.call_requests
  add column if not exists extra jsonb not null default '{}'::jsonb;

-- ------------------------------------------------------------------------
-- 0032_call_state_by_entry.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Call status: Unattended until a visit is entered, then the status of the
-- LATEST VISIT ENTRY — latest by when the visit was ENTERED, not by the visit
-- date the engineer typed.
--
-- Two fixes:
--
-- 1) `sync_call_last_visit` picked the latest visit by `visit_at` (the Visit
--    Date field). A visit entered today for a call visited last week then lost
--    to an older entry with a later visit date. The entry timestamp is
--    `reports.updated_at` (set when the row is written), so order by that and
--    fall back to `id` — which also orders the sheet-era rows, whose
--    updated_at is their import time. `last_visit_at` still carries the visit
--    DATE; only the choice of row changes.
--
-- 2) `open_state` tested `like 'solved%'` first, so the "Solved - Report
--    Pending" status introduced with the report field spec read as Solved and
--    dropped the call off Pending Calls. Unsolved and report-pending are now
--    tested before solved.
-- ===========================================================================

-- The views read open_state, and it is recreated below.
drop view if exists public.pending_calls;
drop view if exists public.call_state;

do $calls_guard$ begin
-- 0040_call_tables_split.sql replaces public.calls with a VIEW over the three
-- typed call tables. What follows is table-only work, so on a project that has
-- already been split it has to be SKIPPED, not attempted — otherwise replaying
-- this file (which re-running any bundle does) dies with
--   ERROR 42809: cannot create index on relation "calls"
-- or "calls is not a table". On an unsplit project it runs exactly as before.
if (select c.relkind from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relname = 'calls') = 'r' then
execute $calls_sql$
alter table public.calls drop column if exists open_state;
alter table public.calls add column open_state text
  generated always as (
    case
      when last_visit_at is null and coalesce(last_status, '') = ''   then 'Unattended'
      when lower(coalesce(last_status, '')) like '%unsolved%'         then 'Unsolved'
      when lower(coalesce(last_status, '')) like '%report pending%'   then 'Report pending'
      when lower(coalesce(last_status, '')) like 'solved%'            then 'Solved'
      else 'Report pending'
    end
  ) stored;

create index if not exists calls_open_idx on public.calls (open_state) where open_state <> 'Solved';
$calls_sql$;
end if;
end $calls_guard$;

-- ---- latest = latest ENTRY -------------------------------------------------
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.calls c
     set last_status   = coalesce(r.call_status, ''),
         last_visit_at = r.visit_at
    from (
      select call_status, visit_at
        from public.reports
       where ucn = p_ucn
       order by updated_at desc nulls last, id desc
       limit 1
    ) r
   where c.ucn = p_ucn;

  if not found then  -- no visits left (or none matched): back to Unattended
    update public.calls set last_status = '', last_visit_at = null where ucn = p_ucn;
  end if;
end $$;

-- ---- re-backfill on the new rule ------------------------------------------
update public.calls c
   set last_status   = coalesce(r.call_status, ''),
       last_visit_at = r.visit_at
  from (
    select distinct on (ucn) ucn, call_status, visit_at
      from public.reports
     order by ucn, updated_at desc nulls last, id desc
  ) r
 where r.ucn = c.ucn
   and (c.last_status is distinct from coalesce(r.call_status, '')
     or c.last_visit_at is distinct from r.visit_at);

-- A call whose reports have all gone is Unattended again.
update public.calls c
   set last_status = '', last_visit_at = null
 where (coalesce(c.last_status, '') <> '' or c.last_visit_at is not null)
   and not exists (select 1 from public.reports r where r.ucn = c.ucn);

-- ---- views -----------------------------------------------------------------
create view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;

create view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';

alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0040_call_tables_split.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Split `calls` into three physical tables: field_calls, installation_calls,
-- pm_calls — so PM's bulk (15–18k/yr) lives in its own table and never bloats
-- the others. Non-breaking: `calls` becomes a UNION-ALL VIEW over the three,
-- with INSTEAD OF triggers routing every write to the right table, so all
-- existing code (addCall / updateCall / bulkInsert('calls') / the reports
-- last-visit sync / the pending_calls & call_state views) keeps working
-- unchanged. Stage 2 will point the registers at the typed tables directly.
--
-- There are NO foreign keys into calls (associations link by ucn/call_number
-- value only), so replacing the table with a view breaks no constraint.
--
-- Idempotent: the one-time structural split is guarded on field_calls not yet
-- existing; the views / triggers / policies are create-or-replace and re-run
-- safely.
-- ===========================================================================

-- Which physical table a call_type belongs to. Robust to 'P M VISIT' (spaces)
-- and 'INSTALLATION CALL'. Immutable so it can drive routing and checks.
create or replace function public.call_table_for(p_type text)
returns text language sql immutable set search_path = public as $$
  select case
    when upper(coalesce(p_type, '')) like 'INSTALL%'                     then 'installation'
    when upper(replace(coalesce(p_type, ''), ' ', '')) like 'PM%'        then 'pm'
    else 'field'
  end;
$$;

-- Fix next_ucn's PM detection to match (a 'P M VISIT' UCN should start with P).
create or replace function public.next_ucn(p_call_type text)
returns text language plpgsql volatile security definer set search_path = public as $$
declare
  yy      text := to_char(now(), 'YY');
  mon     text := substr('ABCDEFGHIJKL', extract(month from now())::int, 1);
  dd      text := to_char(now(), 'DD');
  tletter text := case public.call_table_for(p_call_type)
                    when 'installation' then 'I'
                    when 'pm'           then 'P'
                    else 'F'
                  end;
  seq     int  := nextval('public.ucn_seq');
begin
  return yy || mon || dd || tletter || lpad(seq::text, 4, '0');
end;
$$;

-- ---- one-time structural split --------------------------------------------
do $$
declare cols text;
begin
  if to_regclass('public.field_calls') is not null then return; end if;      -- already split

  -- A single id space shared across the three tables, so the union view's id
  -- stays unique. Continue past the highest existing id.
  create sequence if not exists public.call_split_id_seq;
  perform setval('public.call_split_id_seq', coalesce((select max(id) from public.calls), 0) + 1, false);

  -- Three tables cloned from the current calls shape (columns, the generated
  -- open_state, defaults, the ucn-unique and allocated/serial/open indexes).
  create table public.field_calls        (like public.calls including all);
  create table public.installation_calls (like public.calls including all);
  create table public.pm_calls           (like public.calls including all);

  -- id: drop the per-table identity LIKE copied, use the shared sequence.
  alter table public.field_calls        alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');
  alter table public.installation_calls alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');
  alter table public.pm_calls           alter column id drop identity if exists, alter column id set default nextval('public.call_split_id_seq');

  -- created_by FK parity (LIKE never copies foreign keys).
  alter table public.field_calls        add constraint field_calls_created_by_fkey        foreign key (created_by) references auth.users(id);
  alter table public.installation_calls add constraint installation_calls_created_by_fkey foreign key (created_by) references auth.users(id);
  alter table public.pm_calls           add constraint pm_calls_created_by_fkey           foreign key (created_by) references auth.users(id);

  -- Copy existing rows into their table by type. All non-generated columns
  -- (this list excludes the generated open_state, which recomputes itself).
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position)
    into cols
    from information_schema.columns
   where table_schema = 'public' and table_name = 'calls' and is_generated = 'NEVER';

  execute format('insert into public.field_calls (%1$s)        select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'field');
  execute format('insert into public.installation_calls (%1$s) select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'installation');
  execute format('insert into public.pm_calls (%1$s)           select %1$s from public.calls where public.call_table_for(call_type) = %2$L', cols, 'pm');

  -- Drop the views and the reports policy that depend on the table, then the
  -- table itself (this also drops its calls_biu trigger and its RLS policies).
  drop view if exists public.pending_calls;
  drop view if exists public.call_state;
  drop policy if exists reports_read on public.reports;   -- references public.calls; recreated below over the view
  drop table public.calls;
end $$;

-- ---- per-table write trigger (ucn / call_number / reg_date / created_by) ---
-- calls_before_insert() already exists (0015); attach it to each base table.
drop trigger if exists calls_biu on public.field_calls;
create trigger calls_biu before insert on public.field_calls        for each row execute function public.calls_before_insert();
drop trigger if exists calls_biu on public.installation_calls;
create trigger calls_biu before insert on public.installation_calls for each row execute function public.calls_before_insert();
drop trigger if exists calls_biu on public.pm_calls;
create trigger calls_biu before insert on public.pm_calls           for each row execute function public.calls_before_insert();

-- ---- the compatibility view ------------------------------------------------
create or replace view public.calls as
  select * from public.field_calls
  union all select * from public.installation_calls
  union all select * from public.pm_calls;
alter view public.calls set (security_invoker = on);
grant select, insert, update, delete on public.calls to authenticated;
grant select, insert, update, delete on public.field_calls, public.installation_calls, public.pm_calls to authenticated;
grant usage on sequence public.call_split_id_seq to authenticated;   -- id default is nextval(); insert needs it

-- INSTEAD OF triggers route writes and (on insert) write the trigger-assigned
-- ucn / call_number / id / open_state back onto NEW so `insert … returning *`
-- gives the caller the real UCN.
do $$
declare ins_cols text; ins_vals text; set_list text;
begin
  -- INSERT omits id (shared-sequence default). For every other column, fall
  -- back to the base-table default when the caller didn't supply it, so an
  -- omitted column (NEW is null on a view insert) still gets '' / '{}' / now()
  -- / 'Registered' rather than a null that breaks NOT NULL or loses the default.
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position),
         string_agg(
           case when column_default is not null
                then format('coalesce(new.%I, %s)', column_name, column_default)
                else 'new.' || quote_ident(column_name) end,
           ', ' order by ordinal_position),
         string_agg(quote_ident(column_name) || ' = new.' || quote_ident(column_name), ', ' order by ordinal_position)
    into ins_cols, ins_vals, set_list
    from information_schema.columns
   where table_schema = 'public' and table_name = 'field_calls'
     and is_generated = 'NEVER' and column_name <> 'id';

  execute format($f$
    create or replace function public.calls_view_insert() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(new.call_type)
        when 'installation' then
          insert into public.installation_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
        when 'pm' then
          insert into public.pm_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
        else
          insert into public.field_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state;
      end case;
      return new;
    end $b$;
  $f$, ins_cols, ins_vals);

  execute format($f$
    create or replace function public.calls_view_update() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(old.call_type)
        when 'installation' then update public.installation_calls set %1$s where ucn = old.ucn;
        when 'pm'           then update public.pm_calls           set %1$s where ucn = old.ucn;
        else                     update public.field_calls        set %1$s where ucn = old.ucn;
      end case;
      return new;
    end $b$;
  $f$, set_list);
end $$;

create or replace function public.calls_view_delete() returns trigger language plpgsql as $$
begin
  case public.call_table_for(old.call_type)
    when 'installation' then delete from public.installation_calls where ucn = old.ucn;
    when 'pm'           then delete from public.pm_calls           where ucn = old.ucn;
    else                     delete from public.field_calls        where ucn = old.ucn;
  end case;
  return old;
end $$;

drop trigger if exists calls_view_ins on public.calls;
create trigger calls_view_ins instead of insert on public.calls for each row execute function public.calls_view_insert();
drop trigger if exists calls_view_upd on public.calls;
create trigger calls_view_upd instead of update on public.calls for each row execute function public.calls_view_update();
drop trigger if exists calls_view_del on public.calls;
create trigger calls_view_del instead of delete on public.calls for each row execute function public.calls_view_delete();

-- ---- the last-visit sync now targets the base tables -----------------------
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
declare v_status text; v_at timestamptz;
begin
  select call_status, visit_at into v_status, v_at
    from public.reports where ucn = p_ucn
   order by updated_at desc nulls last, id desc limit 1;   -- null when no visits → Unattended
  update public.field_calls        set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
  update public.installation_calls set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
  update public.pm_calls           set last_status = coalesce(v_status, ''), last_visit_at = v_at where ucn = p_ucn;
end $$;

-- ---- rebuild the derived views over the union ------------------------------
create or replace view public.call_state as
  select ucn, last_status, last_visit_at, open_state as state from public.calls;
create or replace view public.pending_calls as
  select * from public.calls where open_state <> 'Solved';
alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);
grant select on public.call_state, public.pending_calls to authenticated;

-- reports_read reads calls (now the view) to scope a visit by its parent call.
drop policy if exists reports_read on public.reports;
create policy reports_read on public.reports for select
  using (
    (select public.is_admin())
    or (
      (select public.has_perm('calls.view'))
      and (
        (select public.can_view_all_calls())
        or exists (
          select 1 from public.calls c
           where c.ucn = reports.ucn
             and (
               coalesce(c.allocated_to, '') = ''
               or lower(trim(c.allocated_to)) in (
                    select lower(trim(n)) from public.visible_engineer_names() as v(n))
             )
        )
      )
    )
  );

-- ---- RLS: the same three policies (0037 read/update, rbac insert) per table -
do $$
declare t text; vis text;
begin
  -- The shared "may I see this call" test, inlined so the reporting-tree set is
  -- an InitPlan built once (the 0037 shape).
  vis := $v$ (select public.can_view_all_calls())
             or created_by = (select auth.uid())
             or coalesce(allocated_to, '') = ''
             or lower(trim(allocated_to)) in (select lower(trim(n)) from public.visible_engineer_names() as v(n)) $v$;
  foreach t in array array['field_calls', 'installation_calls', 'pm_calls'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists calls_scoped_read on public.%I', t);
    execute format('create policy calls_scoped_read on public.%I for select using ((select public.has_perm(''calls.view'')) and (%s))', t, vis);
    execute format('drop policy if exists calls_insert on public.%I', t);
    execute format('create policy calls_insert on public.%I for insert with check (public.has_perm(''calls.create''))', t);
    execute format('drop policy if exists calls_update on public.%I', t);
    execute format('create policy calls_update on public.%1$I for update using ((select (public.has_perm(''calls.edit'') or public.has_perm(''calls.report''))) and (%2$s)) with check ((select (public.has_perm(''calls.edit'') or public.has_perm(''calls.report''))) and (%2$s))', t, vis);
  end loop;
end $$;

-- ------------------------------------------------------------------------
-- 0041_call_split_hardening.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Stage 3 — harden the calls split. The `calls` view stays (cheap, keeps the
-- cross-type screens simple, and after Stage 2 the registers already read the
-- typed tables directly); this makes keeping it robust:
--
--   1. A CHECK per table pins each row to the right table (call_table_for()),
--      so the INSTEAD OF routing can never misfile a row, and an accidental
--      in-place call_type change is rejected rather than silently orphaned.
--   2. Drop the per-table call_type index LIKE copied from calls — every row in
--      a table now shares one call_type, so the index only costs writes.
--
-- (No constraint-exclusion pruning is attempted: the check is on
-- call_table_for(call_type) while callers filter on call_type, different
-- expressions, and the registers no longer filter the view by type anyway.)
--
-- Idempotent.
-- ===========================================================================

do $$
declare t text; want text; idx text;
begin
  if to_regclass('public.field_calls') is null then
    raise notice 'calls not split yet (0040) — nothing to harden'; return;
  end if;

  foreach t in array array['field_calls', 'installation_calls', 'pm_calls'] loop
    want := case t when 'field_calls' then 'field'
                   when 'installation_calls' then 'installation'
                   else 'pm' end;

    -- 1 + 2. type-pinning CHECK (drop/recreate so it's idempotent).
    execute format('alter table public.%I drop constraint if exists %I', t, t || '_type_ck');
    execute format($c$alter table public.%1$I add constraint %1$s_type_ck check (public.call_table_for(call_type) = %2$L)$c$, t, want);

    -- 3. drop any index on just (call_type) — redundant now the table is one type.
    for idx in
      select indexrelid::regclass::text
        from pg_index i
        join pg_class c on c.oid = i.indrelid
       where c.relname = t and c.relnamespace = 'public'::regnamespace
         and not i.indisprimary and not i.indisunique
         and pg_get_indexdef(i.indexrelid) ilike '%(call_type)%'
    loop
      execute format('drop index if exists %s', idx);
    end loop;
  end loop;
end $$;

-- ------------------------------------------------------------------------
-- 0043_installation_create_gate.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Creating an INSTALLATION call is Commercial's job (they're notified first),
-- with the Hotline desk that registers calls, and admins. Everyone else may
-- still see and report installations, but not create one.
--
-- Enforced on installation_calls only: field_calls / pm_calls keep calls.create.
-- The calls view routes an installation insert into installation_calls, so this
-- governs the view too.
-- ===========================================================================

do $$ begin
  if to_regclass('public.installation_calls') is null then
    raise notice 'calls not split yet (0040) — run split_call_tables.sql first';
    return;
  end if;
  drop policy if exists calls_insert on public.installation_calls;
  create policy calls_insert on public.installation_calls for insert
    with check (public.has_perm('install.create'));
end $$;

-- Grant install.create to the roles that create installations (idempotent).
do $$
declare r text;
begin
  foreach r in array array['admin', 'commercial', 'hotline'] loop
    update public.app_roles
       set permissions = (
             select jsonb_agg(distinct p)
               from (
                 select jsonb_array_elements_text(coalesce(permissions, '[]'::jsonb)) as p
                 union select 'install.create'
               ) u
           ),
           updated_at = now()
     where role = r;
  end loop;
end $$;

-- ------------------------------------------------------------------------
-- 0050_pm_schedule_fields.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- PM schedule fields. PM calls are raised for a due MONTH: the registration
-- DATE is the 1st of that month (so a January batch is dated 1 Jan, whether
-- uploaded in January or backfilled later), and the actual upload date is kept
-- separately as "added_on".
--
-- The call NUMBERING is unchanged (UCN + Call Number as before). What gives a
-- monthly batch a stable order is the registration DATE-AND-TIME: a new
-- `reg_at timestamptz` alongside `reg_date`. The uploader sequences a batch a
-- few seconds apart (see pmImport.ts) — for a fresh month from 00:30 on the
-- 1st, or continuing after the latest existing call when adding to a month that
-- already has some — and the datetime is editable before import.
--
-- reg_date stays a plain `date` (every existing view/index/interval that reads
-- it keeps working); reg_at is the finer-grained companion. Two columns are
-- added to the split call tables, so the calls view and the INSTEAD OF routing
-- triggers are rebuilt to carry them.
-- ===========================================================================

-- An earlier revision of this file trialled a per-month serial (PM-YYYY-MM-####);
-- that idea was dropped (numbering must not change). Remove its objects if a
-- previous bundle created them — harmless if they were never there.
drop trigger  if exists pm_serial_biu on public.pm_calls;
drop function if exists public.pm_serial_assign();
drop function if exists public.next_pm_serial(date);
drop table    if exists public.pm_serial_seq;

do $outer$
begin
  if to_regclass('public.field_calls') is null then
    raise notice 'calls not split yet (0040) — run split_call_tables.sql first';
    return;
  end if;

  -- 1. new columns on each base table (identical shape for the UNION view).
  --    added_on: the day the batch was uploaded. reg_at: the registration
  --    date-and-time (reg_date is its date part).
  alter table public.field_calls        add column if not exists added_on date, add column if not exists reg_at timestamptz;
  alter table public.installation_calls add column if not exists added_on date, add column if not exists reg_at timestamptz;
  alter table public.pm_calls           add column if not exists added_on date, add column if not exists reg_at timestamptz;
  -- The uploader reads the latest reg_at for a due-month to continue after it.
  create index if not exists pm_calls_reg_idx on public.pm_calls (reg_date, reg_at desc);

  -- 2. back-fill reg_at for existing rows so the column is never null where a
  --    date is known (midnight of the registration date).
  update public.field_calls        set reg_at = reg_date::timestamptz where reg_at is null and reg_date is not null;
  update public.installation_calls set reg_at = reg_date::timestamptz where reg_at is null and reg_date is not null;
  update public.pm_calls           set reg_at = reg_date::timestamptz where reg_at is null and reg_date is not null;

  -- 3. the calls view and pending_calls gain the columns (CREATE OR REPLACE
  --    appends the new select-* columns; call_state is unchanged).
  create or replace view public.calls as
    select * from public.field_calls
    union all select * from public.installation_calls
    union all select * from public.pm_calls;
  alter view public.calls set (security_invoker = on);
  create or replace view public.pending_calls as
    select * from public.calls where open_state <> 'Solved';
end $outer$;

-- Keep reg_date and reg_at consistent when only one is supplied: derive the
-- date from the datetime, and default the datetime to midnight of the date.
-- (calls_before_insert() from 0015 also assigns the UCN / Call Number.)
-- Only rebuilt on a SPLIT project — on the pre-split `calls` table there is no
-- reg_at column, so referencing it would break inserts; there we leave the
-- 0015/0040 version in place and this whole migration is a no-op until the
-- split (0040) has run.
do $cbi$
begin
  if to_regclass('public.field_calls') is null then return; end if;
  execute $fn$
    create or replace function public.calls_before_insert()
    returns trigger language plpgsql security definer set search_path = public as $body$
    begin
      if new.ucn is null or new.ucn = '' then
        new.ucn := public.next_ucn(new.call_type);
      end if;
      if new.reg_date is null and new.reg_at is not null then
        new.reg_date := new.reg_at::date;
      end if;
      if coalesce(new.call_number, '') = '' then
        new.call_number := public.next_direct_call_number(to_char(coalesce(new.reg_date, current_date), 'YY'));
      end if;
      if new.reg_date is null then new.reg_date := current_date; end if;
      if new.reg_at is null then new.reg_at := new.reg_date::timestamptz; end if;
      if new.created_by is null then new.created_by := auth.uid(); end if;
      return new;
    end $body$;
  $fn$;
end $cbi$;

-- 4. Rebuild the INSTEAD OF insert/update trigger functions so the two new
--    columns are routed, and returned (both supplied by the caller) on
--    `insert … returning *`.
do $regen$
declare ins_cols text; ins_vals text; set_list text;
begin
  if to_regclass('public.field_calls') is null then return; end if;
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position),
         string_agg(
           case when column_default is not null
                then format('coalesce(new.%I, %s)', column_name, column_default)
                else 'new.' || quote_ident(column_name) end,
           ', ' order by ordinal_position),
         string_agg(quote_ident(column_name) || ' = new.' || quote_ident(column_name), ', ' order by ordinal_position)
    into ins_cols, ins_vals, set_list
    from information_schema.columns
   where table_schema = 'public' and table_name = 'field_calls'
     and is_generated = 'NEVER' and column_name <> 'id';

  execute format($f$
    create or replace function public.calls_view_insert() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(new.call_type)
        when 'installation' then
          insert into public.installation_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
        when 'pm' then
          insert into public.pm_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
        else
          insert into public.field_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
      end case;
      return new;
    end $b$;
  $f$, ins_cols, ins_vals);

  execute format($f$
    create or replace function public.calls_view_update() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(old.call_type)
        when 'installation' then update public.installation_calls set %1$s where ucn = old.ucn;
        when 'pm'           then update public.pm_calls           set %1$s where ucn = old.ucn;
        else                     update public.field_calls        set %1$s where ucn = old.ucn;
      end case;
      return new;
    end $b$;
  $f$, set_list);
end $regen$;

-- ------------------------------------------------------------------------
-- 0053_call_requests_view_all.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Hotline (and the office roles) must see the whole Pending Registrations
-- queue. That screen reads call_requests (rows with no UCN yet), gated by
-- cr_read (0003) — which only showed a user their own requests or an engineer
-- in their reporting sub-tree, with no office-role bypass. So a Hotline engineer
-- saw only the request they raised themselves.
--
-- Fold can_view_all_calls() (admin / data.view_all / hotline / nsm / commercial
-- / spare_coordinator / stores_incharge / tally_coordinator) into cr_read, in
-- line with the call registers and pending_registrations.
-- ===========================================================================

drop policy if exists cr_read on public.call_requests;
create policy cr_read on public.call_requests for select using (
  public.can_view_all_calls()
  or created_by = auth.uid()
  or lower(email) = lower(auth.email())
  or lower(trim(engineer)) in (select lower(trim(n)) from public.visible_engineer_names() as v(n))
);

-- ------------------------------------------------------------------------
-- 0057_call_reopen.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Re-opening a closed call.
--
-- A call whose latest visit says Solved is finished: no more visit entries,
-- spare requests or edits. Sometimes it isn't really finished — the fault
-- returns, or the visit was entered against the wrong call — so the Hotline
-- can RE-OPEN it. A re-opened call counts as open again and carries a flag
-- (`reopen_count`) that makes "how many calls were re-opened?" a filter rather
-- than an archaeology exercise.
--
-- `open_state` itself is left alone: it is a generated column with views
-- hanging off it (field_call_review …), and re-opening is a fact ABOUT the
-- call, not another visit outcome. The effective state — open_state, or
-- 'Reopened' while a re-open is outstanding — is exposed by `call_state` and
-- `pending_calls`, which is what the registers read.
--
-- A re-open is spent by the next visit entry: once visited again the call's
-- state comes from that visit, as usual.
-- ===========================================================================

do $reopen$
declare
  t      text;
  tables text[] := case when to_regclass('public.field_calls') is not null
                        then array['field_calls', 'installation_calls', 'pm_calls']
                        else array['calls'] end;
begin
  if to_regclass('public.field_calls') is null
     and (select c.relkind from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'public' and c.relname = 'calls') <> 'r' then
    raise notice 'calls is neither a table nor split — nothing to alter';
    return;
  end if;

  foreach t in array tables loop
    execute format('alter table public.%I add column if not exists reopened_at timestamptz', t);
    execute format('alter table public.%I add column if not exists reopen_count integer not null default 0', t);
    execute format('create index if not exists %I on public.%I (reopen_count) where reopen_count > 0',
                   t || '_reopen_idx', t);
  end loop;

  -- A view built with select * fixed its column list when it was created, so
  -- it has to be replaced to carry the two new columns. Replacing (rather than
  -- dropping) keeps the INSTEAD OF triggers attached.
  if to_regclass('public.field_calls') is not null then
    create or replace view public.calls as
      select * from public.field_calls
      union all select * from public.installation_calls
      union all select * from public.pm_calls;
  end if;
end $reopen$;

-- The view's INSTEAD OF functions were generated from the column list as it
-- was; regenerate so a write through `calls` carries the new columns too.
do $regen$
declare ins_cols text; ins_vals text; set_list text;
begin
  if to_regclass('public.field_calls') is null then return; end if;
  select string_agg(quote_ident(column_name), ', ' order by ordinal_position),
         string_agg(
           case when column_default is not null
                then format('coalesce(new.%I, %s)', column_name, column_default)
                else 'new.' || quote_ident(column_name) end,
           ', ' order by ordinal_position),
         string_agg(quote_ident(column_name) || ' = new.' || quote_ident(column_name), ', ' order by ordinal_position)
    into ins_cols, ins_vals, set_list
    from information_schema.columns
   where table_schema = 'public' and table_name = 'field_calls'
     and is_generated = 'NEVER' and column_name <> 'id';

  execute format($f$
    create or replace function public.calls_view_insert() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(new.call_type)
        when 'installation' then
          insert into public.installation_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
        when 'pm' then
          insert into public.pm_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
        else
          insert into public.field_calls (%1$s) values (%2$s)
            returning id, ucn, call_number, reg_date, created_by, open_state, added_on, reg_at
            into new.id, new.ucn, new.call_number, new.reg_date, new.created_by, new.open_state, new.added_on, new.reg_at;
      end case;
      return new;
    end $b$;
  $f$, ins_cols, ins_vals);

  execute format($f$
    create or replace function public.calls_view_update() returns trigger language plpgsql as $b$
    begin
      case public.call_table_for(old.call_type)
        when 'installation' then update public.installation_calls set %1$s where ucn = old.ucn;
        when 'pm'           then update public.pm_calls           set %1$s where ucn = old.ucn;
        else                     update public.field_calls        set %1$s where ucn = old.ucn;
      end case;
      return new;
    end $b$;
  $f$, set_list);
end $regen$;

-- ---- a visit entry spends the re-open --------------------------------------
create or replace function public.sync_call_last_visit(p_ucn text)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.calls c
     set last_status   = coalesce(r.call_status, ''),
         last_visit_at = r.visit_at,
         reopened_at   = null
    from (
      select call_status, visit_at
        from public.reports
       where ucn = p_ucn
       order by updated_at desc nulls last, id desc
       limit 1
    ) r
   where c.ucn = p_ucn;

  if not found then  -- no visits left (or none matched): back to Unattended
    update public.calls set last_status = '', last_visit_at = null where ucn = p_ucn;
  end if;
end $$;

-- ---- re-open ---------------------------------------------------------------
-- The Hotline (pending.register) or anyone who may create calls. Security
-- definer so the re-open lands even where the caller may not write the row.
create or replace function public.reopen_call(p_ucn text, p_reason text default '')
returns text language plpgsql security definer set search_path = public as $$
declare v_solved boolean; v_reopened timestamptz;
begin
  if not (public.has_perm('pending.register') or public.has_perm('calls.create')) then
    raise exception 'RBAC: your role cannot re-open a call';
  end if;

  select open_state = 'Solved', reopened_at into v_solved, v_reopened
    from public.calls where ucn = p_ucn;
  if v_solved is null then raise exception 'No call with UCN %', p_ucn; end if;
  if v_reopened is not null then raise exception 'Call % is already re-opened', p_ucn; end if;
  if not v_solved then raise exception 'Call % is not closed, so there is nothing to re-open', p_ucn; end if;

  update public.calls
     set reopened_at = now(), reopen_count = coalesce(reopen_count, 0) + 1
   where ucn = p_ucn;

  return p_ucn;
end $$;
grant execute on function public.reopen_call(text, text) to authenticated;

-- ---- views: effective state, re-open included ------------------------------
drop view if exists public.pending_calls;
drop view if exists public.call_state;

create view public.call_state as
  select ucn, last_status, last_visit_at, reopened_at, reopen_count,
         case when reopened_at is not null then 'Reopened' else open_state end as state
    from public.calls;

create view public.pending_calls as
  select * from public.calls where open_state <> 'Solved' or reopened_at is not null;

alter view public.call_state    set (security_invoker = on);
alter view public.pending_calls set (security_invoker = on);

grant select on public.call_state    to authenticated;
grant select on public.pending_calls to authenticated;

-- ------------------------------------------------------------------------
-- 0058_close_reopened_call.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Closing a re-opened call again, without inventing a visit.
--
-- A call is often re-opened only to correct it — the complaint was typed
-- wrong, the wrong machine was picked. Once corrected there was no way back:
-- the state comes from the latest visit, so the only route to Closed was to
-- enter a visit that never happened.
--
-- `close_reopened_call` withdraws the re-open instead: `reopened_at` is
-- cleared, so the call falls back to what its last visit said (Solved), and
-- nothing is added to its visit history.
--
-- The re-open count is given back. `reopened_at` is only set while NO visit
-- has followed the re-open — once one is entered, sync_call_last_visit clears
-- it and the count stands. So a re-open that is withdrawn never led to a
-- visit: it was an edit, and "how many calls were re-opened" should not count
-- it.
-- ===========================================================================

create or replace function public.close_reopened_call(p_ucn text, p_reason text default '')
returns text language plpgsql security definer set search_path = public as $$
declare v_reopened timestamptz; v_found boolean;
begin
  if not (public.has_perm('pending.register') or public.has_perm('calls.create')) then
    raise exception 'RBAC: your role cannot close a re-opened call';
  end if;

  select true, reopened_at into v_found, v_reopened
    from public.calls where ucn = p_ucn;
  if v_found is null then raise exception 'No call with UCN %', p_ucn; end if;
  if v_reopened is null then
    raise exception 'Call % is not re-opened — close it by entering the visit that solved it', p_ucn;
  end if;

  update public.calls
     set reopened_at  = null,
         reopen_count = greatest(coalesce(reopen_count, 0) - 1, 0)
   where ucn = p_ucn;

  return p_ucn;
end $$;
grant execute on function public.close_reopened_call(text, text) to authenticated;

-- ------------------------------------------------------------------------
-- 0083_request_status_from_ucn.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A request that HAS a UCN is Registered.
--
-- The Hotline sets a request's status explicitly when it registers or maps one
-- (setCallRequestUcn). A bulk load does not — the export carries the UCN in
-- column A and no status at all — so 4,010 registered requests came in reading
-- "Pending" on the register while each pointed at its call. The UCN is the
-- fact; the status is a reading of it, and a reading that can lag the fact is
-- a wrong reading.
--
-- So the database keeps the two in step, on every write from anywhere: a row
-- that carries a UCN and whose status is blank or Pending becomes Registered.
-- Nothing else is touched — Mapped and Registered are already true, Cancelled
-- and Dropped after registration are legitimate states and stay as set.
--
-- The trigger now fires on UPDATE too. It only ever set reqid / unique_key /
-- created_by on insert, which is unchanged; the status rule is the part that
-- has to hold when a UCN is written onto an existing row.
-- ===========================================================================

create or replace function public.call_requests_biu()
returns trigger language plpgsql set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    if new.reqid is null or new.reqid = '' then
      new.reqid := 'R' || nextval('public.call_req_seq')::text;
    end if;
    if new.created_by is null then new.created_by := auth.uid(); end if;
    if coalesce(new.email,'') = '' then new.email := auth.email(); end if;
  end if;
  new.unique_key := new.reqid || '-' || coalesce(nullif(new.product,''),'NA') || '-' || coalesce(nullif(new.serial_no,''),'NA');

  -- A UCN means the request became a call. Only a blank / Pending status is
  -- corrected; every deliberate state is left exactly as it was set.
  if btrim(coalesce(new.ucn, '')) <> ''
     and coalesce(btrim(new.status), '') in ('', 'Pending') then
    new.status := 'Registered';
  end if;
  return new;
end $$;

drop trigger if exists call_requests_biu on public.call_requests;
create trigger call_requests_biu before insert or update on public.call_requests
  for each row execute function public.call_requests_biu();

-- What is already loaded: the same rule, once.
update public.call_requests
   set status = 'Registered'
 where btrim(coalesce(ucn, '')) <> ''
   and coalesce(btrim(status), '') in ('', 'Pending');

-- ------------------------------------------------------------------------
-- 0097_call_reqid_continues.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- REQID PICKS UP WHERE THE HISTORY LEFT OFF.
--
-- The register showed R18576, R18575, R18574 … and then the two requests
-- raised today came out as R1 and R2. Nothing was corrupted; the counter had
-- simply been sent back to the start and never told about the history.
--
-- What happened, in order:
--   1. `_reset_for_production.sql` emptied the demo data and reset the counter
--      (`setval('call_req_seq', 1, false)`). Right at that moment — the table
--      was empty, so R1 was the honest next number.
--   2. The sheet-era requests were then bulk-loaded, EACH CARRYING ITS OWN
--      REQID. An explicit reqid never calls `nextval`, so the counter stayed at
--      1 while 18,576 numbered requests landed above it.
--   3. The next request raised in the app took the counter's word for it.
--
-- Two fixes, because the one-off alone would let it happen again the next time
-- a batch is loaded:
--
--   * `resync_call_req_seq()` lifts the counter to the highest REQID on record,
--     and is run once here for what is already loaded.
--   * The insert trigger now does it CONTINUOUSLY: a row that arrives with its
--     own REQID pushes the counter ahead of itself. Load a hundred thousand old
--     requests and the next one raised in the app still follows the last of
--     them. The counter can no longer fall behind the data it numbers.
--
-- The two that were already issued out of order are re-lettered RC1, RC2. They
-- are real requests people have seen, so the number they were given is kept —
-- but `R1` is a number the sheet era may well have used too, and two different
-- requests reading `R1` is worse than either. `RC` says plainly which series a
-- request belongs to, and the same rule re-letters any other that slipped
-- through: numbered BELOW the register's high-water mark, yet raised AFTER it.
-- ===========================================================================

-- The highest number any REQID carries. `R18576` → 18576; anything not shaped
-- like that is ignored rather than guessed at.
create or replace function public.resync_call_req_seq()
returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_max bigint;
  v_now bigint;
begin
  -- The regex has to be applied BEFORE the cast, and only a CASE guarantees
  -- that: `where <shape> and <cast>` is two quals on one scan and the planner
  -- may order them as it likes, so the first `RC1` in the table would make this
  -- die with "invalid input syntax for type bigint: "C1"" — which it did, the
  -- second time the script was run.
  select max(case when reqid ~ '^R[0-9]{1,15}$' then substring(reqid from 2)::bigint end)
    into v_max from public.call_requests;
  v_now := coalesce(pg_sequence_last_value('public.call_req_seq'::regclass), 0);
  if coalesce(v_max, 0) > v_now then
    perform setval('public.call_req_seq', v_max);
    return v_max;
  end if;
  return v_now;
end $$;
revoke all on function public.resync_call_req_seq() from public;
grant execute on function public.resync_call_req_seq() to authenticated;

-- 0083's trigger, with the one branch it was missing: what to do when the row
-- brings its OWN number.
create or replace function public.call_requests_biu()
returns trigger language plpgsql set search_path = public as $$
declare v_n bigint;
begin
  if tg_op = 'INSERT' then
    if new.reqid is null or new.reqid = '' then
      new.reqid := 'R' || nextval('public.call_req_seq')::text;
    elsif new.reqid ~ '^R[0-9]{1,15}$' then
      -- An imported request carries a number the counter has never issued.
      -- Keep the counter ahead of it, or the next request raised in the app
      -- starts again at R1 alongside an R18576.
      v_n := substring(new.reqid from 2)::bigint;
      if v_n > coalesce(pg_sequence_last_value('public.call_req_seq'::regclass), 0) then
        perform setval('public.call_req_seq', v_n);
      end if;
    end if;
    if new.created_by is null then new.created_by := auth.uid(); end if;
    if coalesce(new.email,'') = '' then new.email := auth.email(); end if;
  end if;
  new.unique_key := new.reqid || '-' || coalesce(nullif(new.product,''),'NA') || '-' || coalesce(nullif(new.serial_no,''),'NA');

  -- A UCN means the request became a call. Only a blank / Pending status is
  -- corrected; every deliberate state is left exactly as it was set. (0083)
  if btrim(coalesce(new.ucn, '')) <> ''
     and coalesce(btrim(new.status), '') in ('', 'Pending') then
    new.status := 'Registered';
  end if;
  return new;
end $$;

drop trigger if exists call_requests_biu on public.call_requests;
create trigger call_requests_biu before insert or update on public.call_requests
  for each row execute function public.call_requests_biu();

-- What is already loaded: once, now.
select public.resync_call_req_seq();

-- ---------------------------------------------------------------------------
-- The ones already issued out of order: numbered below the highest REQID on
-- record, but raised after it. Nothing else can match that — a genuine old
-- request is numbered below the high-water mark AND older than it.
-- ---------------------------------------------------------------------------
do $$
declare
  v_max  bigint;
  v_when timestamptz;
  v_ids  text;
begin
  select max(case when reqid ~ '^R[0-9]{1,15}$' then substring(reqid from 2)::bigint end)
    into v_max from public.call_requests;
  if v_max is null then return; end if;

  -- When the top of the series was raised. Anything numbered below it but not
  -- OLDER than it was numbered by a counter that had lost its place.
  select max(submitted_at) into v_when
    from public.call_requests
   where case when reqid ~ '^R[0-9]{1,15}$' then substring(reqid from 2)::bigint end = v_max;

  select string_agg(distinct reqid, ', ' order by reqid) into v_ids
    from public.call_requests
   where case when reqid ~ '^R[0-9]{1,15}$' then substring(reqid from 2)::bigint end < v_max
     and submitted_at >= v_when;
  if v_ids is null then
    raise notice 'REQID: nothing to re-letter — the series is in order.';
    return;
  end if;

  update public.call_requests
     set reqid = 'RC' || substring(reqid from 2)
   where case when reqid ~ '^R[0-9]{1,15}$' then substring(reqid from 2)::bigint end < v_max
     and submitted_at >= v_when;

  raise notice 'REQID: re-lettered % to RC — numbered below R%, raised after it.', v_ids, v_max;
end $$;

-- ------------------------------------------------------------------------
-- 0104_complaint_suggestions.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- SUGGESTING THE STANDARD COMPLAINT — from the register's own evidence.
--
-- The desk types what the customer said ("Oxygen sensor defective") into
-- Reported Problem, and must then find the right one of FIVE HUNDRED AND SEVEN
-- Standard Complaints. That is the field this suggests.
--
-- The evidence is already here: eighteen thousand past calls, each pairing a
-- reported problem with the standard complaint somebody chose for it. So the
-- first and best answer to "what is this?" is "here is what was chosen the last
-- twelve times somebody described it that way, on this product".
--
-- TWO SOURCES, IN THAT ORDER OF TRUST:
--   1. What was CHOSEN on past calls whose reported problem reads like this one
--      — a decision a person actually made, not a guess about words.
--   2. The wording of the complaint value itself, where no past call is close
--      enough. Weaker, and ranked below.
--
-- Both use the trigram indexes 0052 already built on complaint_reported and
-- standard_complaint, so `%` is an index lookup rather than a scan.
--
-- WHY SECURITY DEFINER. Read as the caller, an engineer would draw suggestions
-- only from their OWN calls, and the newest engineer would get the worst
-- suggestions — the opposite of what is wanted. It returns AGGREGATES ONLY:
-- a master-list value, a count and a score. No call, party, engineer or serial
-- crosses the boundary, so a reader learns nothing about a call they may not
-- see. That is the whole reason it is safe to define it this way.
--
-- WHERE THIS RUNS OUT. It is good at wording that recurs, which on a service
-- desk is most of it — the same fault gets typed the same way. It is weak on a
-- genuine paraphrase: "battery not holding charge" against "Internal battery
-- inoperant" shares one word and scores under any threshold worth using, and
-- pushing the threshold down far enough to catch it drags in everything else.
-- That gap is what the AI layer is for, and it is why the AI layer is worth
-- having rather than an ornament. This layer answers first, always, and the
-- screen works whether or not the other one is switched on.
--
-- IT SUGGESTS. IT DOES NOT DECIDE. The value is written by the person choosing
-- it, on their own authority, and `complaint_suggestions` records what was
-- offered and what was taken so the accept rate can be read rather than
-- assumed.
-- ===========================================================================

create or replace function public.suggest_standard_complaint(
  p_text text, p_product text default '', p_limit int default 5
)
returns table (value text, chosen int, score real, why text)
language sql stable security definer set search_path = public as $$
  with asked as (
    select btrim(coalesce(p_text, '')) as t, btrim(coalesce(p_product, '')) as p
  ),
  -- 1. What a person chose, on a call whose reported problem reads like this.
  --    Narrowed to the product when one is given, because the same words mean
  --    different things on different machines.
  from_calls as (
    select c.standard_complaint as v,
           count(*)::int as n,
           max(greatest(similarity(c.complaint_reported, a.t),
                        word_similarity(a.t, c.complaint_reported))) as sim
      from public.calls c, asked a
     where a.t <> ''
       and coalesce(c.standard_complaint, '') <> ''
       and coalesce(c.complaint_reported, '') <> ''
       and (a.p = '' or c.product_name = a.p)
       -- TWO WAYS OF BEING ALIKE, because whole-string similarity alone misses
       -- the way people actually retype a fault. "O2 sensor faulty" against
       -- "Oxygen sensor defective" scores 0.24 on similarity() — under the 0.3
       -- threshold, so the twelve calls that settled exactly this question were
       -- invisible — and 0.41 on word_similarity(), which asks whether the words
       -- asked for appear in what was written rather than whether the two
       -- strings look alike end to end.
       --
       -- The `%` arm is index-backed (0052's trigram indexes). The word arm is
       -- not, which is why it is worth scoping to the product: a scan of one
       -- product's calls is small, a scan of every call is not.
       and (c.complaint_reported % a.t or word_similarity(a.t, c.complaint_reported) >= 0.35)
     group by c.standard_complaint
  ),
  -- 2. The complaint's own wording, for a description nothing has been called
  --    before. Only live values: a deactivated one must not be offered again.
  from_master as (
    select m.value as v, greatest(similarity(m.value, a.t), word_similarity(a.t, m.value)) as sim
      from public.masters m, asked a
     where a.t <> ''
       and m.name = 'complaint'
       and coalesce(m.active, true)
       and (m.value % a.t or word_similarity(a.t, m.value) >= 0.35)
  ),
  merged as (
    select coalesce(fc.v, fm.v) as v,
           coalesce(fc.n, 0) as n,
           greatest(coalesce(fc.sim, 0), coalesce(fm.sim, 0)) as sim,
           (fc.v is not null) as seen
      from from_calls fc
      full join from_master fm on fm.v = fc.v
  )
  select v,
         n,
         -- A decision somebody made outranks a resemblance between two strings,
         -- so evidence carries the weight and the wording breaks ties. The log
         -- is there to be argued with: if the ranking is wrong, the accept rate
         -- will say so.
         (sim + least(n, 20) * 0.05)::real as score,
         case
           when n >= 2 then 'chosen on ' || n || ' similar call' || case when n = 1 then '' else 's' end
           when n = 1 then 'chosen once on a similar call'
           else 'wording match'
         end as why
    from merged
   where v is not null and v <> ''
   order by score desc, n desc, v
   limit greatest(coalesce(p_limit, 5), 1);
$$;
revoke all on function public.suggest_standard_complaint(text, text, int) from public;
grant execute on function public.suggest_standard_complaint(text, text, int) to authenticated;

-- ---------------------------------------------------------------------------
-- WHAT WAS OFFERED, AND WHAT WAS TAKEN.
--
-- Without this the only honest thing that could be said about the feature is
-- "it seems to help". One row per registration where a suggestion was shown:
-- the list offered in order, and the value the person actually chose. The
-- accept rate falls out of it, and so does the answer to "is the AI adding
-- anything the register's own evidence did not already give us".
--
-- It records a SUGGESTION, not a quality record, so it is not in the
-- record_audit set and carries no before/after image.
-- ---------------------------------------------------------------------------
create table if not exists public.complaint_suggestions (
  id            bigint generated always as identity primary key,
  asked_at      timestamptz not null default now(),
  asked_by      uuid,
  asked_by_name text not null default '',
  product       text not null default '',
  reported      text not null default '',
  -- [{ value, why, rank, source }] — source is 'register' or 'ai'.
  suggested     jsonb not null default '[]'::jsonb,
  -- What the person chose. '' means they took none of them, which is the most
  -- interesting row in the table.
  accepted      text not null default '',
  accepted_rank int,
  ucn           text not null default ''
);
create index if not exists complaint_suggestions_at_idx on public.complaint_suggestions (asked_at desc);

alter table public.complaint_suggestions enable row level security;
grant select, insert on public.complaint_suggestions to authenticated;

drop policy if exists cs_insert on public.complaint_suggestions;
create policy cs_insert on public.complaint_suggestions for insert
  with check (auth.role() = 'authenticated');
drop policy if exists cs_read on public.complaint_suggestions;
create policy cs_read on public.complaint_suggestions for select
  using ((select public.is_admin()) or (select public.has_perm('audit.view')));

-- Stamp the author in the database rather than trusting the client with it.
create or replace function public.complaint_suggestions_bi()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.asked_by := auth.uid();
  new.asked_by_name := coalesce((select full_name from public.profiles where id = auth.uid()), '');
  return new;
end $$;
drop trigger if exists complaint_suggestions_bi on public.complaint_suggestions;
create trigger complaint_suggestions_bi before insert on public.complaint_suggestions
  for each row execute function public.complaint_suggestions_bi();

-- ------------------------------------------------------------------------
-- 0105_calls_view_security_invoker.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE `calls` VIEW WAS READING AS ITS OWNER — SO EVERY USER SAW EVERY CALL.
--
-- 0040 created the view over the three typed tables and set `security_invoker`
-- on it, which is what makes row-level security apply to the person reading
-- rather than to the view's owner. 0050 re-created the view and correctly set
-- it again. 0057 re-created the view and DID NOT.
--
-- `create or replace view` does not carry the setting over. There is no error
-- and no warning; the view simply starts running as its owner, and RLS stops
-- applying to everything read through it.
--
-- Measured on a database with every migration applied, as an engineer holding
-- twelve calls that belong to somebody else:
--
--     field_calls (the table)   0 rows      <- RLS working
--     calls (the view)         12 rows      <- RLS bypassed
--     pending_calls            12 rows      <- reads `calls`, so it leaks too
--     call_state               12 rows      <- same
--     failure_modes_by_product  visible     <- same
--
-- pending_calls and call_state carry `security_invoker` themselves and were
-- still wide open, because a view marked invoker that reads a view running as
-- its owner inherits the owner's reach. Marking the outer view is no protection
-- if an inner one is unmarked.
--
-- That defeats URS-002 (role-based visibility), FRS-003/004, R-01 and OQ-02 —
-- an engineer could read every call in the register, and the KPI screens
-- counted the whole fleet for everybody.
--
-- WHAT CHANGES WHEN THIS IS APPLIED: engineers and managers will see FEWER
-- calls on Pending Calls, the registers and the KPIs — the ones their role
-- actually permits. That is the intended behaviour and what the validation
-- package has always claimed; it will nonetheless look like something broke to
-- anyone who had grown used to seeing everything.
--
-- A SECURITY DEFINER function reading the view is unaffected: inside one, the
-- invoker IS the function's owner, so `suggest_standard_complaint()` still
-- draws on every call, which is the whole point of defining it that way.
--
-- THIS LIVES IN THE `call_requests` BUNDLE, after 0057, because that is the
-- bundle that defines the view. Anywhere else and replaying call_requests.sql
-- would put the leak straight back.
-- ===========================================================================

do $$
begin
  if to_regclass('public.calls') is not null
     and (select relkind from pg_class where oid = 'public.calls'::regclass) = 'v' then
    execute 'alter view public.calls set (security_invoker = on)';
    raise notice 'calls: row-level security now applies to the reader, not the view owner.';
  end if;
end $$;

-- The views built ON it, re-asserted for the same reason: cheap, and it removes
-- any doubt about the order these were last written in.
do $$
declare v text;
begin
  foreach v in array array['pending_calls', 'call_state'] loop
    if to_regclass('public.' || v) is not null then
      execute format('alter view public.%I set (security_invoker = on)', v);
    end if;
  end loop;
end $$;

commit;
