-- ===========================================================================
-- RITHI CRM — Document Library (service manuals & QMS): apply bundle
--
-- The service-manual shelf and the QMS shelf (`documents`). The FILES live
-- in Google Drive; this is the catalogue that makes one findable --- above
-- all which PRODUCT a manual covers, so a call can hand the engineer the
-- manual for the machine in front of them instead of a folder to hunt
-- through. Read by everyone signed in; maintained by `docs.manage` for the
-- manuals and `qms.manage` for the controlled QMS documents, which are two
-- separate jobs. A superseded document is RETIRED, never deleted.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0070_documents.sql
--   0265_qms_document_key.sql
--   0272_service_note_upload_key.sql
--   0299_document_drive_details.sql
--   0350_service_note_dated_latest.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0070_documents.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- DOCUMENT LIBRARY — service manuals and QMS documents.
--
-- The FILES live in Google Drive (uploaded through the CallReg bridge, the same
-- path a manual report already takes); what lives here is the CATALOGUE that
-- makes one findable: which product a manual covers, its revision, and the link.
-- That is the whole point of the table — an engineer on a call must be handed
-- THE RIGHT manual for the machine in front of them, and a Drive folder cannot
-- answer that question.
--
-- One table, two kinds:
--   'service_manual' — keyed by PRODUCT; surfaced on the call as a supporting
--                      document for the machine the call is against.
--   'qms'            — the controlled quality documents (SOPs, work
--                      instructions, forms), carrying a document number,
--                      revision and effective date.
-- They differ only in which fields matter and who may maintain them, so they
-- share the table and split on `kind`.
--
-- Maintaining them is two separate rights, because they are two separate jobs:
--   docs.manage — service manuals and general documents
--   qms.manage  — the QMS shelf (quality's own)
-- Everyone signed in READS both: a manual nobody can open is no use in the
-- field, and a QMS document the team cannot find is not controlled, it is lost.
-- ===========================================================================

create table if not exists public.documents (
  id             bigint generated always as identity primary key,
  kind           text not null default 'service_manual',
  title          text not null,
  -- The product/model a manual covers. BLANK deliberately means "every
  -- product" — a general manual still has to reach every call.
  product        text not null default '',
  doc_no         text not null default '',   -- QMS document number
  revision       text not null default '',
  effective_date date,
  tags           text not null default '',   -- comma-separated, matched against a call
  url            text not null,              -- the Drive link
  file_name      text not null default '',
  notes          text not null default '',
  active         boolean not null default true,
  uploaded_by      uuid references auth.users (id),
  uploaded_by_name text not null default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

alter table public.documents add column if not exists effective_date date;
alter table public.documents add column if not exists notes text not null default '';

-- A call looks a manual up BY PRODUCT, every time a call is opened, so that
-- lookup gets its own index rather than a scan of the shelf.
create index if not exists documents_kind_idx     on public.documents (kind);
create index if not exists documents_product_idx  on public.documents (lower(product));
create index if not exists documents_active_idx   on public.documents (active);

-- Stamp who uploaded it (cannot be spoofed) and keep updated_at honest.
create or replace function public.documents_before_write()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    new.uploaded_by := coalesce(new.uploaded_by, auth.uid());
  else
    new.uploaded_by := old.uploaded_by;   -- authorship is not editable
    new.created_at  := old.created_at;
  end if;
  new.kind := lower(trim(coalesce(new.kind, 'service_manual')));
  if new.kind = '' then new.kind := 'service_manual'; end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists documents_biu on public.documents;
create trigger documents_biu before insert or update on public.documents
  for each row execute function public.documents_before_write();

alter table public.documents enable row level security;
grant select, insert, update, delete on public.documents to authenticated;

-- Read: everyone signed in, both kinds.
drop policy if exists documents_read on public.documents;
create policy documents_read on public.documents for select
  using (auth.role() = 'authenticated');

-- Write: the right that matches the kind. Admins hold both via has_perm().
drop policy if exists documents_insert on public.documents;
create policy documents_insert on public.documents for insert
  with check (case when kind = 'qms' then public.has_perm('qms.manage')
                   else public.has_perm('docs.manage') end);

-- Both sides tested, so a document cannot be moved between shelves by someone
-- who may only maintain one of them.
drop policy if exists documents_update on public.documents;
create policy documents_update on public.documents for update
  using      (case when kind = 'qms' then public.has_perm('qms.manage')
                   else public.has_perm('docs.manage') end)
  with check (case when kind = 'qms' then public.has_perm('qms.manage')
                   else public.has_perm('docs.manage') end);

drop policy if exists documents_delete on public.documents;
create policy documents_delete on public.documents for delete
  using (case when kind = 'qms' then public.has_perm('qms.manage')
              else public.has_perm('docs.manage') end);

-- ---------------------------------------------------------------------------
-- Grant the new rights to the roles that already do this work, by MERGING into
-- app_roles — never by overwriting, since an admin may have tuned the role.
-- Service manuals: the roles that maintain masters. QMS: admin only, until
-- quality says who else keeps it.
-- ---------------------------------------------------------------------------
do $$
declare r record;
begin
  if to_regclass('public.app_roles') is null then
    raise notice 'public.app_roles is not present — run the rbac bundle first';
    return;
  end if;

  for r in select role, coalesce(permissions, '[]'::jsonb) as perms from public.app_roles loop
    if r.role in ('admin', 'hotline', 'nsm', 'spare_coordinator')
       and not (r.perms ? 'docs.manage') then
      update public.app_roles
         set permissions = r.perms || '["docs.manage"]'::jsonb, updated_at = now()
       where role = r.role;
    end if;
    if r.role = 'admin' and not (r.perms ? 'qms.manage') then
      update public.app_roles
         set permissions = coalesce(permissions, '[]'::jsonb) || '["qms.manage"]'::jsonb, updated_at = now()
       where role = r.role;
    end if;
  end loop;

  -- And the modules themselves, so the two screens are reachable at all.
  update public.app_roles
     set permissions = coalesce(permissions, '[]'::jsonb) || '["mod:/service-manuals"]'::jsonb, updated_at = now()
   where not (coalesce(permissions, '[]'::jsonb) ? 'mod:/service-manuals');
  update public.app_roles
     set permissions = coalesce(permissions, '[]'::jsonb) || '["mod:/qms"]'::jsonb, updated_at = now()
   where role in ('admin', 'nsm', 'hotline')
     and not (coalesce(permissions, '[]'::jsonb) ? 'mod:/qms');
end $$;

-- ------------------------------------------------------------------------
-- 0265_qms_document_key.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- QMS DOCUMENTS BY BULK UPLOAD -- the Master List.
--
--   The user, 2026-09-30: "I want to be able to do a bulk upload on QMS
--   Documents. 99% it will be a One Time Activity, the QMS Department has a
--   Specific format to maintain the MasterList." What goes up: the Master List
--   with each document's Drive URL (the files are already on Drive).
--
-- TWO THINGS THE UPLOAD NEEDS:
--
--   * A KEY, so a re-load CORRECTS a row instead of adding a second copy of
--     the document: the document number + revision, on the QMS shelf only.
--     NULL for anything without a number (every service manual, and a QMS row
--     typed without one), and NULLs never collide -- so the index constrains
--     exactly the rows the Master List can name, and is a plain unique index
--     PostgREST can infer (check:upserts), not a partial one.
--   * SOMEWHERE FOR THE MASTER LIST'S OWN COLUMNS. Its format is the QMS
--     department's; every heading with no column here is kept in `extra`
--     under its own spelling rather than dropped.
--
-- IF TWO QMS ROWS ALREADY SHARE A NUMBER AND REVISION, the index cannot be
-- built, and this says so instead of failing: nothing is deleted or merged
-- (quality records are never deleted) -- retire or correct one of them on the
-- QMS Documents screen and run this again. _status.sql row 205 checks it.
-- ===========================================================================

alter table public.documents add column if not exists extra jsonb not null default '{}'::jsonb;
alter table public.documents add column if not exists doc_key text generated always as (
  case when kind = 'qms' and btrim(doc_no) <> ''
       then lower(btrim(doc_no)) || '|' || lower(btrim(revision)) end) stored;

do $$
declare dup text;
begin
  if exists (select 1 from pg_indexes where schemaname = 'public' and indexname = 'documents_doc_key_uniq') then
    return;
  end if;
  select string_agg(doc_key, ', ') into dup
    from (select doc_key from public.documents where doc_key is not null
           group by doc_key having count(*) > 1 limit 20) x;
  if dup is not null then
    raise notice '0265: QMS documents share a number + revision (%); the upload key was NOT created. Correct them and run again.', dup;
    return;
  end if;
  create unique index documents_doc_key_uniq on public.documents (doc_key);
end $$;

-- ------------------------------------------------------------------------
-- 0272_service_note_upload_key.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- TECHNICAL / SERVICE NOTES BY BULK UPLOAD -- a key for re-loading the list.
--
--   The user, 2026-09-30, pasting the Drive listing of the Technical Note
--   folder: "Normalise this for bulk upload". The shelf itself exists since
--   v0.10.6 (documents kind 'service_note', no migration); what a bulk load
--   needs is a KEY, so loading the list a second time CORRECTS those rows
--   instead of adding a second copy of every note.
--
-- THE KEY IS THE DRIVE LINK. A note has no controlled number and revision the
-- way a QMS document does (0265): the listing's file names carry a number
-- sometimes and a revision rarely, and two different notes are filed under the
-- same number in two product folders (NT606 is under Extend-XT AND Monnal
-- T75). What names ONE file unambiguously is its Drive link. So url_key is the
-- link, lower-cased and trimmed, for SERVICE NOTES ONLY -- NULL for every other
-- kind, and NULLs never collide, so the index constrains exactly the rows this
-- upload writes and is a plain unique index PostgREST can infer.
--
-- IF TWO NOTES ALREADY SHARE A LINK the index cannot be built; this says so
-- instead of failing, and nothing is deleted. _status.sql row 212 checks it.
-- ===========================================================================

alter table public.documents add column if not exists url_key text generated always as (
  case when kind = 'service_note' and btrim(url) <> '' then lower(btrim(url)) end) stored;

do $$
declare dup text;
begin
  if exists (select 1 from pg_indexes where schemaname = 'public' and indexname = 'documents_url_key_uniq') then
    return;
  end if;
  select string_agg(url_key, ', ') into dup
    from (select url_key from public.documents where url_key is not null
           group by url_key having count(*) > 1 limit 20) x;
  if dup is not null then
    raise notice '0272: service notes share a Drive link (%); the upload key was NOT created. Retire one of each and run again.', dup;
    return;
  end if;
  create unique index documents_url_key_uniq on public.documents (url_key);
end $$;

-- ------------------------------------------------------------------------
-- 0299_document_drive_details.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A TECHNICAL / SERVICE NOTE CARRIES ITS DRIVE DETAILS.
--
--   The user, 2026-09-30, after loading the Technical Note list: "I didn't
--   want this '30-Sep-2026 10:27:25' in the updated date and time -- it has to
--   reflect the Meta data from Drive. Added also has to be mapped per the Drive
--   Details." Their answers: the shelf shows Added = Drive's Created,
--   Added By = Drive's Last Modified By, Updated = Drive's Last Modified; and
--   RITHI's own record of who loaded it and when is KEPT, shown in the record
--   details rather than the table.
--
-- SO THESE ARE THREE NEW COLUMNS, NOT created_at / updated_at REWRITTEN.
-- created_at, updated_at and uploaded_by answer "when and by whom was this
-- entered HERE" -- documents_before_write() (0070) stamps them and that is the
-- audit trail. What Drive says about the FILE is a different fact about a
-- different thing, and putting it in those columns would lose the first to
-- record the second. Blank for anything not loaded from a Drive listing.
-- ===========================================================================

alter table public.documents add column if not exists source_created_at  timestamptz;
alter table public.documents add column if not exists source_modified_at timestamptz;
alter table public.documents add column if not exists source_modified_by text not null default '';

comment on column public.documents.source_created_at  is 'Drive''s Created date-time of the file, from the listing it was loaded from (0299). Not when it was entered here -- that is created_at.';
comment on column public.documents.source_modified_at is 'Drive''s Last Modified date-time of the file (0299). Not when the row was last changed here -- that is updated_at.';
comment on column public.documents.source_modified_by is 'Drive''s Last Modified By, as the listing wrote it (0299). Not who entered it here -- that is uploaded_by.';

-- ------------------------------------------------------------------------
-- 0350_service_note_dated_latest.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- TECHNICAL / SERVICE NOTES: A DATE OF THEIR OWN, AND THE LATEST ONE PER
-- PRODUCT MARKED.
--
-- The user, 2026-10-04: "Group it as Per Product. Add a Column [Dated], which
-- I will update manually. Sort it by Dated, Newest to Oldest. Automatically add
-- a Tag as Latest. When I add a new Technical Note for the Product, these Auto
-- Tags should reset and update according to the Latest. I should have a Button
-- to Trigger this correction."  Settled with the user the same day:
--   * a note covering several products is listed under EACH of them, and may
--     be the latest for one and not another -- so the mark is PER PRODUCT;
--   * a note with no product is the "Every product" group (token '');
--   * only a LIVE note with a Dated can be the latest -- a note not yet dated,
--     or retired, is never marked; two live notes on the same newest date are
--     both marked;
--   * the mark is STORED, recalculated automatically, and on demand by a button.
--
-- documents.dated       the date the user gives the note, by hand. Not
--                       effective_date (the QMS field) and not created_at (when
--                       it was entered here) -- a note entered today may be
--                       dated years ago.
-- documents.latest_for  the products this note is currently the latest for,
--                       spelled as on the note; '' stands for "Every product".
--                       Written ONLY by refresh_service_note_latest_all().
--
-- WHEN IT RECALCULATES: a statement-level trigger after any insert or delete of
-- a document, and after an update of kind / product / dated / active -- so a
-- bulk upload of 300 notes recalculates once, and the recalculation's own write
-- (latest_for only) does not fire it again. The Refresh button calls
-- refresh_service_note_latest(), which asks for docs.manage and does the same.
-- Only rows whose mark actually changes are written.
-- ===========================================================================

alter table public.documents add column if not exists dated date;
alter table public.documents add column if not exists latest_for text[] not null default '{}';

comment on column public.documents.dated is
  'Technical / Service Notes: the note''s own date, entered by hand. Orders the shelf (newest first) and decides which note is the latest per product (0350).';
comment on column public.documents.latest_for is
  'Technical / Service Notes: the products this note is the latest for ('''' = every product). Written only by refresh_service_note_latest_all() (0350).';

create index if not exists documents_dated_idx on public.documents (kind, dated desc);

-- THE RECALCULATION. Products are split exactly as the screen splits them
-- (comma, semicolon, bar, newline; trimmed; blanks dropped) and compared
-- case-insensitively, so "MONNAL T60" and "Monnal T60" are one product.
create or replace function public.refresh_service_note_latest_all()
returns integer language plpgsql security definer set search_path = public as $$
declare v_changed integer;
begin
  with note_products as (
    select d.id, d.dated,
           coalesce(nullif(btrim(p.prod), ''), '') as prod
      from public.documents d
      left join lateral regexp_split_to_table(coalesce(d.product, ''), '[,;|\n]') as p(prod) on true
     where d.kind = 'service_note' and d.active and d.dated is not null
  ),
  -- A note with products listed has '' rows only from blank pieces; drop
  -- those unless the note names no product at all.
  cleaned as (
    select np.* from note_products np
     where np.prod <> ''
        or not exists (select 1 from note_products o where o.id = np.id and o.prod <> '')
  ),
  newest as (
    select lower(prod) as k, max(dated) as top from cleaned group by lower(prod)
  ),
  marks as (
    select c.id, array_agg(distinct c.prod order by c.prod) as latest
      from cleaned c join newest n on n.k = lower(c.prod) and n.top = c.dated
     group by c.id
  ),
  target as (
    select d.id, coalesce(m.latest, '{}'::text[]) as latest
      from public.documents d left join marks m on m.id = d.id
     where d.kind = 'service_note'
  )
  update public.documents d set latest_for = t.latest
    from target t
   where t.id = d.id and d.latest_for is distinct from t.latest;
  get diagnostics v_changed = row_count;
  return v_changed;
end $$;

revoke execute on function public.refresh_service_note_latest_all() from public, anon, authenticated;

-- THE BUTTON. The same work, for whoever may maintain the shelf.
create or replace function public.refresh_service_note_latest()
returns integer language plpgsql security definer set search_path = public as $$
begin
  if not public.has_perm('docs.manage') then
    raise exception 'Your role does not have permission for this action' using errcode = '42501';
  end if;
  return public.refresh_service_note_latest_all();
end $$;

revoke execute on function public.refresh_service_note_latest() from public, anon;
grant execute on function public.refresh_service_note_latest() to authenticated;

create or replace function public.documents_refresh_latest()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.refresh_service_note_latest_all();
  return null;
end $$;

revoke execute on function public.documents_refresh_latest() from public, anon, authenticated;

drop trigger if exists zz_service_note_latest_ins on public.documents;
create trigger zz_service_note_latest_ins after insert or delete on public.documents
  for each statement execute function public.documents_refresh_latest();
drop trigger if exists zz_service_note_latest_upd on public.documents;
create trigger zz_service_note_latest_upd after update of kind, product, dated, active on public.documents
  for each statement execute function public.documents_refresh_latest();

-- The notes already on the shelf: none has a Dated yet, so this marks nothing
-- today; it is here so a re-run after dates were loaded by hand lands right.
select public.refresh_service_note_latest_all();

commit;
