-- ===========================================================================
-- RITHI CRM — Hand Stock: apply bundle
--
-- The stock level an engineer is carrying, per spare:
-- 
--   Stock Level = Stock Out (Stores) - Consumption
--               - Stock Transfer From + Stock Transfer To
-- 
-- Engineer-to-engineer transfers (the only new entry), the two views that
-- net the four movements, their guards and grants — and, at the end, the
-- queries for reading a stock level back.
-- 
-- Needs the spare workflow through per-spare approvals; run the
-- spare_requests bundle first if _status.sql says that is missing.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0020_handstock.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.spare_requests') is null then
    missing := array_append(missing, 'the spare_requests table — 0001_init.sql');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.is_admin()') is null then
    missing := array_append(missing, 'is_admin() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.can_approve_spares()') is null then
    missing := array_append(missing, 'can_approve_spares() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.spare_line_stage(text,text,text,text,timestamptz,text)') is null then
    missing := array_append(missing, 'per-spare approvals (spare_request_lines.dispatched_at) — 0016_spare_line_approvals.sql (apply bundle: spare_requests)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0020_handstock.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Hand stock — the stock level an engineer is carrying, per spare.
--
--   Stock Level = Stock Out (from Stores)
--               − Consumption
--               − Stock Transfer From
--               + Stock Transfer To
--
-- Three of those four movements already existed and had never been put side by
-- side: Stores dispatching a spare against an OR, the spare consumed on a call
-- report, and — new here — a spare handed from one engineer to another.
--
--   stock_transfers     — engineer → engineer hand-overs (the only new entry).
--   handstock_movements — one row per movement, all four kinds.
--   handstock_balance   — the stock level per engineer + spare.
--
-- The views run with the caller's rights, so the register is scoped exactly
-- like the tables under it: an engineer sees their own stock, an RM their
-- sub-tree, an admin everyone's.
-- ===========================================================================

-- Consumption is keyed by the engineer's NAME (that is all the report form ever
-- wrote). The name is what the movements are matched on; the email is carried
-- alongside so a rename can be untangled later, and so new rows can be matched
-- on it once the field has been filled for a while.
alter table public.spare_consumption
  add column if not exists engineer_email text default '';

create index if not exists spare_consumption_engineer_idx     on public.spare_consumption (lower(btrim(engineer)));
create index if not exists spare_consumption_created_at_idx   on public.spare_consumption (created_at desc);
create index if not exists spare_request_lines_stores_idx     on public.spare_request_lines (lower(coalesce(stores_status, '')));
create index if not exists spare_request_lines_dispatched_idx on public.spare_request_lines (dispatched_at) where dispatched_at is not null;

-- ---------------------------------------------------------------------------
-- The two things a movement is matched on. Names arrive with stray case and
-- spacing from four different screens; a spare is stored as its catalogue
-- string "CODE|Description", and only the CODE identifies it.
-- ---------------------------------------------------------------------------
create or replace function public.handstock_key(p text)
returns text language sql immutable as $$ select lower(btrim(coalesce(p, ''))) $$;

create or replace function public.part_code(p text)
returns text language sql immutable as $$ select upper(btrim(split_part(coalesce(p, ''), '|', 1))) $$;

grant execute on function public.handstock_key(text) to authenticated;
grant execute on function public.part_code(text)     to authenticated;

-- ---------------------------------------------------------------------------
-- Stock transfers: one engineer hands a spare to another. The only movement
-- with no home elsewhere, so it gets a table — deliberately a plain record of
-- a hand-over, not a second approval chain.
-- ---------------------------------------------------------------------------
create table if not exists public.stock_transfers (
  id                 bigint generated always as identity primary key,
  transfer_no        text unique,                  -- ST-YY/MM/N, assigned here
  from_engineer      text not null default '',
  from_engineer_email text default '',
  to_engineer        text not null default '',
  to_engineer_email  text default '',
  part               text not null default '',     -- CODE|Description
  qty                numeric not null default 1,
  reason             text default '',
  remarks            text default '',
  transferred_at     timestamptz not null default now(),
  created_at         timestamptz not null default now(),
  created_by         uuid default auth.uid() references auth.users (id)
);
create index if not exists stock_transfers_from_idx on public.stock_transfers (lower(btrim(from_engineer)));
create index if not exists stock_transfers_to_idx   on public.stock_transfers (lower(btrim(to_engineer)));

-- Numbered per month, like the OR series (0017): ST-26/08/1.
create table if not exists public.stock_transfer_counters (
  period  text primary key,          -- 'YY/MM'
  last_no integer not null default 0
);
alter table public.stock_transfer_counters enable row level security;  -- definer-only

create or replace function public.next_stock_transfer_no(p_on date default current_date)
returns text language plpgsql security definer set search_path = public as $$
declare
  p text := to_char(p_on, 'YY/MM');
  n integer;
begin
  insert into public.stock_transfer_counters (period, last_no) values (p, 1)
  on conflict (period) do update set last_no = public.stock_transfer_counters.last_no + 1
  returning last_no into n;
  return 'ST-' || p || '/' || n;
end $$;
grant execute on function public.next_stock_transfer_no(date) to authenticated;

-- ---------------------------------------------------------------------------
-- Movements — the four terms of the formula, one row each.
--
-- Stock out is dated by the DISPATCH, not the acknowledgement: the spare left
-- Stores and is the engineer's from that moment, whether or not they have got
-- round to acknowledging it. Since 0016_spare_line_approvals.sql dispatch is
-- per SPARE, so a partly dispatched OR moves only what actually went out.
--
-- What makes it a stock out is the STATUS, not the timestamp. Dispatches from
-- before this module — sheet-era history, imports, anything dispatched before
-- 0009 added dispatched_at — carry a DC and a status but no date, and they are
-- every bit as much stock in the engineer's hands. They count, dated by the
-- best timestamp the row has.
-- ---------------------------------------------------------------------------
create or replace view public.handstock_movements as
-- 1. Stock out from Stores (+)
select
  'IN'::text                                        as direction,
  'Stock out'::text                                 as movement,
  public.handstock_key(r.engineer)                  as engineer_key,
  coalesce(r.engineer, '')                          as engineer,
  coalesce(r.engineer_email, '')                    as engineer_email,
  public.part_code(l.part)                          as part_code,
  coalesce(l.part, '')                              as part,
  coalesce(l.qty, 0)                                as qty,
  coalesce(l.dispatched_at, r.dispatched_at, l.created_at, r.created_at)
                                                    as moved_at,
  coalesce(nullif(l.dc_number, ''), r.or_no, '')    as ref,
  'Stores DC'::text                                 as ref_type,
  coalesce(r.uid, '')                               as ref_uid,
  coalesce(r.ucn, '')                               as ucn,
  coalesce(r.call_number, '')                       as call_number,
  coalesce(r.party_name, '')                        as party_name,
  coalesce(nullif(l.dispatch_remarks, ''), '')      as remarks
from public.spare_request_lines l
join public.spare_requests r on r.uid = l.request_uid
where coalesce(l.stores_status, '') ~* 'dispatch'
union all
-- 2. Consumption on a call (−)
select
  'OUT'::text, 'Consumption'::text,
  public.handstock_key(c.engineer),
  coalesce(c.engineer, ''),
  coalesce(c.engineer_email, ''),
  public.part_code(c.part),
  coalesce(c.part, ''),
  coalesce(c.qty, 0),
  c.created_at,
  coalesce(nullif(btrim(c.call_number), ''), coalesce(c.ucn, '')),
  'Call'::text,
  ''::text,
  coalesce(c.ucn, ''),
  coalesce(c.call_number, ''),
  ''::text,
  ''::text
from public.spare_consumption c
union all
-- 3. Stock transfer FROM this engineer (−)
select
  'OUT'::text, 'Transfer out'::text,
  public.handstock_key(t.from_engineer),
  coalesce(t.from_engineer, ''),
  coalesce(t.from_engineer_email, ''),
  public.part_code(t.part),
  coalesce(t.part, ''),
  coalesce(t.qty, 0),
  t.transferred_at,
  coalesce(t.transfer_no, ''),
  'Transfer'::text,
  ''::text,
  ''::text,
  ''::text,
  coalesce(t.to_engineer, ''),                      -- who it went to
  btrim(coalesce(t.reason, '') || ' ' || coalesce(t.remarks, ''))
from public.stock_transfers t
union all
-- 4. Stock transfer TO this engineer (+)
select
  'IN'::text, 'Transfer in'::text,
  public.handstock_key(t.to_engineer),
  coalesce(t.to_engineer, ''),
  coalesce(t.to_engineer_email, ''),
  public.part_code(t.part),
  coalesce(t.part, ''),
  coalesce(t.qty, 0),
  t.transferred_at,
  coalesce(t.transfer_no, ''),
  'Transfer'::text,
  ''::text,
  ''::text,
  ''::text,
  coalesce(t.from_engineer, ''),                    -- who it came from
  btrim(coalesce(t.reason, '') || ' ' || coalesce(t.remarks, ''))
from public.stock_transfers t;

-- ---------------------------------------------------------------------------
-- The stock level, one row per engineer + spare, with each term of the formula
-- kept separate so a figure can be argued with.
--
-- A negative level is not an error to hide: it means more was consumed or
-- handed on than this module has seen issued — stock carried from before the
-- register existed, or a spare taken without a DC.
-- ---------------------------------------------------------------------------
create or replace view public.handstock_balance as
select
  m.engineer_key,
  max(m.engineer)                                                       as engineer,
  max(m.engineer_email)                                                 as engineer_email,
  m.part_code,
  -- the catalogue string as the parts master spells it: prefer a Stores
  -- dispatch's, since a consumption row may carry an older wording.
  coalesce(max(m.part) filter (where m.movement = 'Stock out'), max(m.part))
                                                                        as part,
  sum(case when m.movement = 'Stock out'    then m.qty else 0 end)      as stock_out,
  sum(case when m.movement = 'Consumption'  then m.qty else 0 end)      as consumed,
  sum(case when m.movement = 'Transfer in'  then m.qty else 0 end)      as transferred_in,
  sum(case when m.movement = 'Transfer out' then m.qty else 0 end)      as transferred_out,
  sum(case when m.direction = 'IN' then m.qty else -m.qty end)          as on_hand,
  max(m.moved_at) filter (where m.direction = 'IN')                     as last_in,
  max(m.moved_at) filter (where m.direction = 'OUT')                    as last_out,
  max(m.moved_at)                                                       as last_movement,
  count(*)                                                              as movements
from public.handstock_movements m
where m.engineer_key <> '' and m.part_code <> ''
group by m.engineer_key, m.part_code;

alter view public.handstock_movements set (security_invoker = on);
alter view public.handstock_balance   set (security_invoker = on);

grant select on public.handstock_movements to authenticated;
grant select on public.handstock_balance   to authenticated;
grant select, insert on public.stock_transfers to authenticated;

-- ---------------------------------------------------------------------------
-- The stock level for one engineer + spare, read with the definer's rights so
-- the transfer guard can check stock the transferring user may not be able to
-- see (an admin moving a part between two engineers, say).
-- ---------------------------------------------------------------------------
create or replace function public.handstock_on_hand(p_engineer_key text, p_part_code text)
returns numeric language sql stable security definer set search_path = public as $$
  select coalesce(sum(case when m.direction = 'IN' then m.qty else -m.qty end), 0)
    from public.handstock_movements m
   where m.engineer_key = p_engineer_key and m.part_code = p_part_code;
$$;
-- Deliberately NOT granted to `authenticated`: it reads with the definer's
-- rights, so exposing it would let anyone ask what any engineer is holding.
-- The trigger below calls it from inside a definer function, which needs no
-- grant; the app reads the RLS-scoped `handstock_balance` view instead.
revoke execute on function public.handstock_on_hand(text, text) from public, authenticated;

-- A hand-over cannot invent stock, move nothing, or go to the person who
-- already has it. Numbering happens here too, so nothing else has to.
create or replace function public.stock_transfers_check()
returns trigger language plpgsql security definer set search_path = public as $$
declare available numeric;
begin
  if coalesce(new.qty, 0) < 1 then
    raise exception 'Transfer quantity must be at least 1';
  end if;
  if public.handstock_key(new.from_engineer) = '' or public.handstock_key(new.to_engineer) = '' then
    raise exception 'A transfer needs both the engineer handing over and the one receiving';
  end if;
  if public.handstock_key(new.from_engineer) = public.handstock_key(new.to_engineer) then
    raise exception 'A spare cannot be transferred to the engineer who already holds it';
  end if;
  if public.part_code(new.part) = '' then
    raise exception 'A transfer needs a spare';
  end if;

  available := public.handstock_on_hand(public.handstock_key(new.from_engineer), public.part_code(new.part));
  if new.qty > available then
    raise exception 'Only % of % in %''s hand stock — cannot transfer %',
      available, public.part_code(new.part), new.from_engineer, new.qty;
  end if;

  if new.transfer_no is null or btrim(new.transfer_no) = '' then
    new.transfer_no := public.next_stock_transfer_no(coalesce(new.transferred_at, now())::date);
  end if;
  return new;
end $$;

drop trigger if exists stock_transfers_check on public.stock_transfers;
create trigger stock_transfers_check
  before insert on public.stock_transfers
  for each row execute function public.stock_transfers_check();

-- A transfer is a record of something that happened; correcting one means
-- another transfer the other way, not an edit. Only an admin may amend.
create or replace function public.stock_transfers_immutable()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_admin() then return new; end if;
  raise exception 'A stock transfer cannot be edited — record the return transfer instead';
end $$;

drop trigger if exists stock_transfers_immutable on public.stock_transfers;
create trigger stock_transfers_immutable
  before update on public.stock_transfers
  for each row execute function public.stock_transfers_immutable();

alter table public.stock_transfers enable row level security;

-- Readable by whoever may see the engineer's stock at all: the two engineers
-- on the transfer, anyone whose reporting sub-tree either of them is in, the
-- spare approvers, and admins.
drop policy if exists st_read on public.stock_transfers;
create policy st_read on public.stock_transfers for select
  using (
    public.is_admin()
    or created_by = auth.uid()
    or lower(coalesce(from_engineer_email, '')) = lower(auth.email())
    or lower(coalesce(to_engineer_email, ''))   = lower(auth.email())
    or public.can_approve_spares()
    or lower(btrim(from_engineer)) in (select lower(btrim(n)) from public.visible_engineer_names() as v(n))
    or lower(btrim(to_engineer))   in (select lower(btrim(n)) from public.visible_engineer_names() as v(n))
  );

-- Recording one needs the permission, and — unless you may act for others —
-- it has to be your own stock you are handing over.
drop policy if exists st_insert on public.stock_transfers;
create policy st_insert on public.stock_transfers for insert
  with check (
    public.has_perm('stock.transfer')
    and (public.is_admin()
         or public.can_approve_spares()
         or lower(coalesce(from_engineer_email, '')) = lower(auth.email()))
  );

drop policy if exists st_delete on public.stock_transfers;
create policy st_delete on public.stock_transfers for delete using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Access. Neither key is on any role until granted; append them — additively —
-- to the roles that already work with spares, leaving anything an admin has
-- since edited alone.
--   mod:/handstock  opens the register.
--   stock.transfer  records a hand-over (own stock, unless you may act for
--                   others). Stores and the approvers get it too, since they
--                   are the ones who move stock between engineers.
-- ---------------------------------------------------------------------------
update public.app_roles
   set permissions = coalesce(permissions, '[]'::jsonb) || '["mod:/handstock"]'::jsonb,
       updated_at  = now()
 where coalesce(permissions, '[]'::jsonb) ? 'mod:/spare-requests'
   and not coalesce(permissions, '[]'::jsonb) ? 'mod:/handstock';

update public.app_roles
   set permissions = coalesce(permissions, '[]'::jsonb) || '["stock.transfer"]'::jsonb,
       updated_at  = now()
 where role in ('admin', 'engineer', 'rm', 'rgm', 'spare_coordinator', 'stores_incharge')
   and not coalesce(permissions, '[]'::jsonb) ? 'stock.transfer';

commit;

-- ===========================================================================
-- Reading a stock level back. Uncomment one and run it on its own.
-- ===========================================================================
--
-- 1. What is the field holding right now?
-- select engineer, part_code, part, stock_out, consumed,
--        transferred_in, transferred_out, on_hand
--   from public.handstock_balance
--  where on_hand > 0
--  order by engineer, part_code;
--
-- 2. One engineer's stock — what the report form's consumption picker offers.
-- select part, on_hand from public.handstock_balance
--  where engineer_key = lower(btrim('Engineer Name')) and on_hand > 0
--  order by part_code;
--
-- 3. Where a disputed level came from: every movement behind one line.
-- select moved_at, movement, qty, ref, ref_type, ucn, party_name, remarks
--   from public.handstock_movements
--  where engineer_key = lower(btrim('Engineer Name')) and part_code = 'SP-100'
--  order by moved_at desc;
--
-- 4. Short lines — consumed or handed on more than Stores ever issued.
-- select engineer, part_code, stock_out, consumed, transferred_out, on_hand
--   from public.handstock_balance where on_hand < 0 order by on_hand;
--
-- 5. Transfers, newest first.
-- select transfer_no, transferred_at, from_engineer, to_engineer, part, qty, reason
--   from public.stock_transfers order by transferred_at desc;
--
-- 6. Spares dispatched to an engineer and never consumed or handed on
--    (a spare sitting in a car long after the call closed).
-- select engineer, part_code, part, stock_out, on_hand, last_in
--   from public.handstock_balance
--  where on_hand > 0 and last_in < now() - interval '30 days'
--  order by last_in;
--
-- 7. Did the module land? (the same check _status.sql makes)
-- select to_regclass('public.handstock_balance')   is not null as balance_view,
--        to_regclass('public.handstock_movements') is not null as movements_view,
--        to_regclass('public.stock_transfers')     is not null as transfers_table;
