-- ===========================================================================
-- RITHI CRM — Knowledge Base: apply bundle
--
-- Team-written field-solution articles (kb_articles): anyone signed in reads
-- every article and contributes one; the author or an admin edits or deletes.
-- Rich text with images and tables is stored as sanitized HTML on the row.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0042_knowledge_base.sql
--   0043_help_screenshots.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if to_regprocedure('public.is_admin()') is null then
    missing := array_append(missing, 'is_admin() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0042_knowledge_base.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Knowledge Base — team-written field-solution articles. Anyone signed in can
-- read every article and contribute one; the author (or an admin) can edit or
-- delete their own. Stamped with the author so the team knows who to ask.
-- ===========================================================================

create table if not exists public.kb_articles (
  id           bigint generated always as identity primary key,
  title        text not null,
  body         text not null,
  category     text default '',      -- Field Issue / How-To / Product Tip / Other
  product      text default '',      -- optional: the product / model it concerns
  tags         text default '',      -- optional: comma-separated keywords
  attachments  jsonb not null default '[]',  -- [{name, url}] — links to files in Drive / on Pages / anywhere
  author_name  text default '',
  author_email text default '',
  created_by   uuid references auth.users (id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists kb_articles_updated_idx  on public.kb_articles (updated_at desc);
create index if not exists kb_articles_category_idx  on public.kb_articles (category);

-- Stamp the author on insert (can't be spoofed) and updated_at on every write.
create or replace function public.kb_before_write()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' and auth.uid() is not null then
    new.created_by := auth.uid();
  end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists kb_biu on public.kb_articles;
create trigger kb_biu before insert or update on public.kb_articles
  for each row execute function public.kb_before_write();

alter table public.kb_articles enable row level security;
grant select, insert, update, delete on public.kb_articles to authenticated;

-- Read: everyone signed in. Contribute: any signed-in user (stamped as self).
-- Edit / delete: the author, or an admin.
drop policy if exists kb_read on public.kb_articles;
create policy kb_read on public.kb_articles for select
  using (auth.role() = 'authenticated');

drop policy if exists kb_insert on public.kb_articles;
create policy kb_insert on public.kb_articles for insert
  with check (auth.uid() is not null);

drop policy if exists kb_update on public.kb_articles;
create policy kb_update on public.kb_articles for update
  using (created_by = auth.uid() or public.is_admin())
  with check (created_by = auth.uid() or public.is_admin());

drop policy if exists kb_delete on public.kb_articles;
create policy kb_delete on public.kb_articles for delete
  using (created_by = auth.uid() or public.is_admin());

-- ------------------------------------------------------------------------
-- 0043_help_screenshots.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Help screenshots — one optional picture per task in the "How to use RITHI
-- CRM" guide, keyed by the task's section id (e.g. 'request', 'install'). Every
-- signed-in user sees them; only an admin can set or clear one. The image is a
-- downscaled data URL (same as Knowledge Base article images), so no separate
-- file store is needed.
-- ===========================================================================

create table if not exists public.help_screenshots (
  section_id  text primary key,             -- matches a guide section id
  image       text not null,                -- data URL (downscaled JPEG/PNG)
  caption     text not null default '',
  updated_by  uuid references auth.users (id),
  updated_at  timestamptz not null default now()
);

-- Stamp who/when on every write (can't be spoofed by the client).
create or replace function public.help_shot_before_write()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is not null then new.updated_by := auth.uid(); end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists help_shot_biu on public.help_screenshots;
create trigger help_shot_biu before insert or update on public.help_screenshots
  for each row execute function public.help_shot_before_write();

alter table public.help_screenshots enable row level security;
grant select, insert, update, delete on public.help_screenshots to authenticated;

-- Read: everyone signed in. Set / replace / clear: admins only.
drop policy if exists help_shot_read on public.help_screenshots;
create policy help_shot_read on public.help_screenshots for select
  using (auth.role() = 'authenticated');

drop policy if exists help_shot_insert on public.help_screenshots;
create policy help_shot_insert on public.help_screenshots for insert
  with check (public.is_admin());

drop policy if exists help_shot_update on public.help_screenshots;
create policy help_shot_update on public.help_screenshots for update
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists help_shot_delete on public.help_screenshots;
create policy help_shot_delete on public.help_screenshots for delete
  using (public.is_admin());

commit;
