-- ===========================================================================
-- RITHI CRM — What the public key can reach: apply bundle
--
-- Row-level security ON for the Party Key counter, and EXECUTE withdrawn
-- from the API roles on the owner-rights functions the app never calls:
-- raise_ffr(), the register-wide maintenance functions and every
-- numbered-series generator. Each is reached from inside the database by
-- a definer trigger or function, so it keeps working there. The three the
-- app does call keep signed-in access and lose only the not-signed-in
-- role. Findings 49-52 of the table review, 2026-09-26.
-- 
-- LAST IN THE ORDER so every function it names exists when it runs; each
-- is guarded, so it is harmless on a project behind on other modules.
-- _status.sql rows 188 and 189 say whether it holds.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0248_lock_down_internal_functions.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin

  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0248_lock_down_internal_functions.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- WHAT THE PUBLIC KEY CAN REACH, NARROWED (findings 49, 50, 51, 52).
--
--   The user, 2026-09-26: "Fix all low hanging fruits", after the table review
--   (RITHI Table Atlas) measured, on a database built from the migrations:
--     49  the NOT-signed-in role set the Party Key counter to 999,999, and the
--         next key issued was Party-1000000 -- party_key_seq was the one table
--         with row-level security OFF, and Supabase grants every table to anon;
--     50  the not-signed-in role called raise_ffr() and a Field Failure Report
--         was raised on a call of its choosing -- an undeletable quality record
--         using up a number in the controlled R-SER-03 series;
--     51  register-wide maintenance functions ran for any caller;
--     52  every numbered series (UCN, OR, DC, MRN, ST, Party Key, Call Number)
--         could be consumed by a direct call, leaving gaps.
--
-- THE RULE APPLIED: a SECURITY DEFINER function that the APP does not call
-- is not the API's to call. Every one below is reached from inside the
-- database -- a trigger function or another function, EACH OF THEM SECURITY
-- DEFINER, checked against the catalogue before this was written -- so it runs
-- as the owner there and keeps working. Only the two roles a client speaks as
-- lose it: anon and authenticated. PUBLIC is revoked too, because that is where
-- a function's default EXECUTE comes from.
--
-- WHAT THE APP DOES CALL keeps authenticated and loses only anon:
--   next_call_reqid()        -- Request Registration mints a REQID
--   refresh_product_cover()  -- Data Import, after a cover import
--   cover_unpin_inherited()  -- the same step; 0247 makes both ask for cover.edit
--
-- IDEMPOTENT, and GUARDED: a function a project has not got yet is skipped, not
-- an error, so this can run on a project behind on other modules. It is the
-- LAST module for the same reason sys_columns was: a replay of the module that
-- owns one of these functions uses `create or replace`, which keeps the grants,
-- but a re-run of THIS bundle is also how to put them back if a rebuild did not.
-- `_status.sql` rows 188 and 189 say whether it holds.
-- ===========================================================================

-- ---- 49. the Party Key counter: row-level security on, no policy -----------
-- Exactly how the other eight counters are kept: nothing but a definer function
-- may read or write the row. next_party_key() is one, and the parties insert
-- trigger that calls it is another, so a new party still gets its key.
do $$
begin
  if to_regclass('public.party_key_seq') is null then return; end if;
  alter table public.party_key_seq enable row level security;
  revoke all on table public.party_key_seq from anon, authenticated;
end $$;

-- ---- 50, 51, 52. what the API may call ---------------------------------------
do $$
declare
  fn text;
  internal text[] := array[
    -- 50: raised by the review trigger (ffr_from_review) and backfill_ffrs()
    'public.raise_ffr(public.call_reviews)',
    -- 51: register-wide maintenance, reached only from definer triggers or cron
    'public.upsert_product_from_sale(bigint)',
    'public.sync_product_cover(text)',
    'public.sync_call_last_visit(text)',
    'public.purge_audit_log()',
    -- 52: the numbered series, each assigned by a definer trigger on insert
    'public.next_ucn(text)',
    'public.next_party_key()',
    'public.next_spare_or_no(date)',
    'public.next_mrn_uid(date)',
    'public.next_dispatch_no(text,date)',
    'public.next_stock_out_no(date)',
    'public.next_stock_transfer_no(date)',
    'public.next_direct_call_number(text)'];
  app_called text[] := array[
    'public.next_call_reqid()',
    'public.refresh_product_cover()',
    'public.cover_unpin_inherited()'];
begin
  foreach fn in array internal loop
    if to_regprocedure(fn) is null then continue; end if;
    execute format('revoke execute on function %s from public', fn);
    begin execute format('revoke execute on function %s from anon, authenticated', fn);
    exception when undefined_object then null; end;
  end loop;

  foreach fn in array app_called loop
    if to_regprocedure(fn) is null then continue; end if;
    execute format('revoke execute on function %s from public', fn);
    begin
      execute format('revoke execute on function %s from anon', fn);
      execute format('grant execute on function %s to authenticated', fn);
    exception when undefined_object then null; end;
  end loop;
end $$;

commit;
