-- ===========================================================================
-- RITHI CRM — Search performance (trigram indexes): apply bundle
--
-- pg_trgm trigram indexes so substring searches (product, party, call
-- registers) are index-backed instead of full table scans — the fix for
-- "canceling statement due to statement timeout" on Search. Runs last so
-- every table it indexes already exists; skips the calls view / absent columns.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0052_search_indexes.sql
--   0098_product_register_names.sql
--   0099_no_jit.sql
--   0101_kpi_views.sql
--   0128_kpi_field_inst.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin

  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0052_search_indexes.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Search performance. The app searches with substring ILIKE ('%term%') across
-- products, parties and the call registers. A leading wildcard cannot use the
-- existing lower(col) btree indexes, so every search seq-scans the whole table
-- and, once the tables grew, hit the API statement timeout ("canceling
-- statement due to statement timeout") on every page.
--
-- pg_trgm trigram GIN indexes make substring/ILIKE matching index-backed. This
-- block installs pg_trgm and adds a trigram index for each searched column that
-- exists, on each base table that exists — so it works before or after the call
-- split (0040): the `calls` VIEW is skipped, its base tables are indexed.
-- Idempotent (create index if not exists); safe to re-run.
-- ===========================================================================

create extension if not exists pg_trgm;

do $$
declare
  trgm text;   -- schema pg_trgm actually lives in (extensions on Supabase)
  rec  record;
  idx  text;
begin
  select quote_ident(n.nspname) into trgm
    from pg_extension e join pg_namespace n on n.oid = e.extnamespace
   where e.extname = 'pg_trgm';
  if trgm is null then raise notice 'pg_trgm not available — skipping'; return; end if;

  for rec in
    select tbl, col from (values
      ('products','serial_number'), ('products','item_name'), ('products','party_name'),
      ('parties','party_name'),
      ('field_calls','ucn'), ('field_calls','call_number'), ('field_calls','party_name'),
      ('field_calls','serial'), ('field_calls','product_name'), ('field_calls','allocated_to'),
      ('field_calls','city'), ('field_calls','state'), ('field_calls','standard_complaint'),
      ('field_calls','complaint_reported'), ('field_calls','customer_name'),
      ('installation_calls','ucn'), ('installation_calls','call_number'), ('installation_calls','party_name'),
      ('installation_calls','serial'), ('installation_calls','product_name'), ('installation_calls','allocated_to'),
      ('installation_calls','city'), ('installation_calls','state'), ('installation_calls','standard_complaint'),
      ('installation_calls','complaint_reported'), ('installation_calls','customer_name'),
      ('pm_calls','ucn'), ('pm_calls','call_number'), ('pm_calls','party_name'),
      ('pm_calls','serial'), ('pm_calls','product_name'), ('pm_calls','allocated_to'),
      ('pm_calls','city'), ('pm_calls','state'), ('pm_calls','standard_complaint'),
      ('pm_calls','complaint_reported'), ('pm_calls','customer_name'),
      ('calls','ucn'), ('calls','call_number'), ('calls','party_name'),
      ('calls','serial'), ('calls','product_name'), ('calls','allocated_to'),
      ('calls','city'), ('calls','state'), ('calls','standard_complaint'),
      ('calls','complaint_reported'), ('calls','customer_name')
    ) as v(tbl, col)
  loop
    -- table must exist and be an ordinary table (skip the calls VIEW after split)
    if to_regclass('public.' || rec.tbl) is null then continue; end if;
    if (select relkind from pg_class where oid = ('public.' || rec.tbl)::regclass) <> 'r' then continue; end if;
    -- column must exist on it
    if not exists (select 1 from information_schema.columns
                    where table_schema = 'public' and table_name = rec.tbl and column_name = rec.col) then
      continue;
    end if;
    idx := rec.tbl || '_' || rec.col || '_trgm';
    execute format('create index if not exists %I on public.%I using gin (%I %s.gin_trgm_ops)',
                   idx, rec.tbl, rec.col, trgm);
  end loop;
end $$;

-- Btree indexes for the EXACT-match / IN lookups (a trigram index does not
-- serve `=`/`IN`): the request cascade filters products by party_name (and
-- item_name) with eq, and openCallsFor looks up calls by serial / party_name
-- with IN. Without these, those lookups seq-scan and time out too.
do $$
declare rec record; idx text;
begin
  for rec in
    select tbl, col from (values
      ('products','party_name'), ('products','item_name'),
      ('field_calls','serial'), ('field_calls','party_name'),
      ('installation_calls','serial'), ('installation_calls','party_name'),
      ('pm_calls','serial'), ('pm_calls','party_name'),
      ('calls','serial'), ('calls','party_name')
    ) as v(tbl, col)
  loop
    if to_regclass('public.' || rec.tbl) is null then continue; end if;
    if (select relkind from pg_class where oid = ('public.' || rec.tbl)::regclass) <> 'r' then continue; end if;
    if not exists (select 1 from information_schema.columns
                    where table_schema = 'public' and table_name = rec.tbl and column_name = rec.col) then
      continue;
    end if;
    idx := rec.tbl || '_' || rec.col || '_eq';
    execute format('create index if not exists %I on public.%I (%I)', idx, rec.tbl, rec.col);
  end loop;
end $$;

-- Refresh planner stats so the new indexes are used right away.
do $$
declare t text;
begin
  foreach t in array array['products','parties','field_calls','installation_calls','pm_calls','calls'] loop
    if to_regclass('public.' || t) is not null
       and (select relkind from pg_class where oid = ('public.' || t)::regclass) = 'r' then
      execute 'analyze public.' || quote_ident(t);
    end if;
  end loop;
end $$;

-- ------------------------------------------------------------------------
-- 0098_product_register_names.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE PRODUCT LIST COMES FROM THE PRODUCT REGISTER.
--
-- Product & Party Search was filling its product dropdown from the `product`
-- master value list. That is a list somebody maintains, and it can be empty,
-- short, or spelled differently from the register — which is what the screen
-- showed. The register itself is the authority on what products exist: a
-- machine is in it or it is not.
--
-- PostgREST cannot ask for `select distinct`, so the distinct list is a view.
-- It carries the count as well, because "MONNAL T75 (1,204)" tells the person
-- choosing far more than the name alone, and it costs nothing to group once.
--
-- The serial dropdown that depends on it needs no view: it is
-- `item_name = <the one chosen>`, which 0052's btree on products(item_name)
-- already serves. (A trigram index does NOT serve equality — that lesson cost
-- this project a fortnight of timeouts.)
-- ===========================================================================

create or replace view public.product_register_names as
  select item_name,
         count(*)::int as machines
    from public.products
   where coalesce(item_name, '') <> ''
   group by item_name;

-- `create or replace view` does NOT carry `security_invoker` forward, so it is
-- asserted every time the view is written. Without it the view would read the
-- register as its owner and hand back rows RLS meant to withhold.
alter view public.product_register_names set (security_invoker = on);

grant select on public.product_register_names to authenticated;

-- ------------------------------------------------------------------------
-- 0099_no_jit.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE HAND STOCK TIMEOUT WAS JIT COMPILATION, NOT THE QUERY.
--
-- Hand Stock timed out, then took 11-14 seconds, then 3-5 after 0095. Every
-- reading pointed at row-level security, because switching RLS off made it
-- instant. It was the right symptom and the wrong cause. `EXPLAIN ANALYZE`
-- with the JIT block showing says it plainly:
--
--     Timing: Generation 23 ms, Inlining 145 ms,
--             Optimization 2134 ms, Emission 1440 ms, Total 3742 ms
--     Execution Time: 3912 ms
--
-- Three and three-quarter seconds COMPILING a query that then runs in under
-- two hundred milliseconds. The trigger is `jit_above_cost` (100,000): the
-- planner's ESTIMATE for the nine-arm movement view is half a million, almost
-- all of it invented by the cost of RLS sub-plans it will barely run. So the
-- more access rules a query carries, the more certain Postgres is to spend
-- seconds compiling it — and that is why turning RLS off "fixed" it.
--
-- With JIT off, and NOTHING else changed, the whole 102,893-row history reads
-- in 323 ms. Closed through 2025 it is 174 ms. Measured on a copy of the live
-- data, as the `authenticated` role, with every policy in force.
--
-- Nothing in this application benefits from JIT. These are sub-second API
-- queries; compiling them can only ever cost more than it saves. Off is the
-- right setting for the whole database, not a special case for one screen.
--
-- TO PUT IT BACK: `alter database postgres reset jit;`
--
-- It applies to CONNECTIONS MADE AFTER IT RUNS. Pooled connections already
-- open keep the old setting, so give it a few minutes — or restart the project
-- — before judging whether it worked.
-- ===========================================================================

do $$
begin
  execute format('alter database %I set jit = off', current_database());
  raise notice 'JIT disabled for database % — new connections only.', current_database();
exception
  when insufficient_privilege then
    raise notice 'Could not disable JIT: this role does not own the database. Set it in the Supabase dashboard, or run: alter database postgres set jit = off;';
end $$;

-- ------------------------------------------------------------------------
-- 0101_kpi_views.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- KPIs THAT COME FROM THE RECORD, NOT FROM A SPREADSHEET.
--
-- Three questions the service function actually asks, each answered by an
-- aggregate the database computes rather than a page that pulls forty thousand
-- rows across the wire and adds them up in a browser:
--
--   FAILURE RATE      how often does a product fail, per machine in the field?
--                     A count of calls means nothing on its own — a product with
--                     1,200 machines SHOULD generate more calls than one with 40.
--                     The denominator is the install base, which the Product
--                     Register already holds.
--
--   SPARE USE BY COVER  what do we spend on parts under warranty, under CMC,
--                     under AMC, and out of guarantee? The cover is on the CALL,
--                     the parts are on the consumption; the join is the answer.
--
--   SPARE USE BY REGION  the same figure per region, so a region consuming twice
--                     its share can be looked at rather than guessed at.
--
-- EVERY VIEW IS security_invoker, so an engineer's KPIs are their own calls and
-- a manager's are their team's. The numbers a person sees are the numbers they
-- are allowed to see, without a second set of rules to keep in step.
--
-- `create or replace view` does NOT carry security_invoker over — it is asserted
-- on every one of them, every time.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- One row per part consumed, carrying what the call says about it. This is the
-- grain everything else rolls up from; it is also worth reading on its own when
-- a number looks wrong.
--
-- The cover (`item_status`) and the region are FACTS ABOUT THE CALL AND THE
-- ENGINEER, not about the part, so they are read from there rather than copied
-- onto the consumption row where they would age.
-- ---------------------------------------------------------------------------
create or replace view public.spare_usage as
  select c.id,
         c.ucn,
         c.call_number,
         c.part,
         public.part_code(c.part)                            as part_code,
         coalesce(c.qty, 0)                                  as qty,
         coalesce(nullif(btrim(c.engineer), ''), '')         as engineer,
         coalesce(nullif(btrim(k.item_status), ''), 'Not stated') as cover,
         coalesce(nullif(btrim(k.product_name), ''), '')     as product,
         coalesce(nullif(btrim(k.call_type), ''), '')        as call_type,
         coalesce(nullif(btrim(k.city), ''), '')             as city,
         coalesce(nullif(btrim(ud.region), ''), 'No region') as region,
         coalesce(nullif(btrim(c.source), ''), 'Engineer')   as source,
         c.created_at                                        as consumed_at
    from public.spare_consumption c
    left join public.calls k on k.ucn = c.ucn
    left join public.user_directory ud
           on lower(btrim(ud.name)) = lower(btrim(coalesce(nullif(c.engineer, ''), k.allocated_to)))
   where coalesce(c.qty, 0) <> 0;
alter view public.spare_usage set (security_invoker = on);
grant select on public.spare_usage to authenticated;

-- ---------------------------------------------------------------------------
-- Spare use by cover, region and product, in one rollup the screen pivots.
--
-- One row per combination rather than three separate views: a few thousand rows
-- at most, and a client that has them can answer "CMC in the South" without
-- another round trip — and, more to the point, without the three views being
-- able to disagree with each other.
-- ---------------------------------------------------------------------------
create or replace view public.spare_usage_rollup as
  select cover, region, product,
         count(*)::int                     as lines,
         sum(qty)                          as qty,
         count(distinct ucn)::int          as calls,
         count(distinct part_code)::int    as parts,
         count(distinct engineer)::int     as engineers
    from public.spare_usage
   group by cover, region, product;
alter view public.spare_usage_rollup set (security_invoker = on);
grant select on public.spare_usage_rollup to authenticated;

-- ---------------------------------------------------------------------------
-- FAILURE RATE — calls per hundred machines in the field, over twelve months.
--
-- `machines` is the install base from the Product Register and is NOT scoped by
-- who is asking: it is a property of the fleet, the same number for everybody.
-- `calls_12m` is scoped, because it is a count of calls. So an engineer reads
-- their own share of a fleet-wide denominator, which is the honest reading of
-- what they can see, and a rate is only comparable between products for someone
-- who can see all the calls. The screen says so.
--
-- Twelve months because a reliability figure needs a period; the same view
-- carries the all-time count beside it so a young product is not read as a
-- reliable one.
-- ---------------------------------------------------------------------------
create or replace view public.failure_rate_by_product as
  with fleet as (
    select coalesce(nullif(btrim(item_name), ''), '') as product, count(*)::int as machines
      from public.products
     where coalesce(btrim(item_name), '') <> ''
     group by 1
  ), calls as (
    select coalesce(nullif(btrim(product_name), ''), '') as product,
           count(*)::int as calls_total,
           count(*) filter (where reg_date >= (current_date - 365))::int as calls_12m,
           count(*) filter (where open_state <> 'Solved')::int as calls_open
      from public.calls
     where coalesce(btrim(product_name), '') <> ''
     group by 1
  )
  select coalesce(f.product, c.product)      as product,
         coalesce(f.machines, 0)             as machines,
         coalesce(c.calls_total, 0)          as calls_total,
         coalesce(c.calls_12m, 0)            as calls_12m,
         coalesce(c.calls_open, 0)           as calls_open,
         case when coalesce(f.machines, 0) > 0
              then round(coalesce(c.calls_12m, 0)::numeric * 100 / f.machines, 1)
         end                                  as per_100_machines
    from fleet f
    full join calls c on c.product = f.product;
alter view public.failure_rate_by_product set (security_invoker = on);
grant select on public.failure_rate_by_product to authenticated;

-- ---------------------------------------------------------------------------
-- HOW a product fails, not just how often. The standard complaint is the field
-- the service desk already chooses from a controlled list, so it is the one
-- thing in the record that groups reliably across thousands of calls.
-- ---------------------------------------------------------------------------
create or replace view public.failure_modes_by_product as
  select coalesce(nullif(btrim(product_name), ''), '')       as product,
         coalesce(nullif(btrim(standard_complaint), ''), 'Not stated') as complaint,
         count(*)::int                                       as calls,
         count(*) filter (where reg_date >= (current_date - 365))::int as calls_12m
    from public.calls
   where coalesce(btrim(product_name), '') <> ''
   group by 1, 2;
alter view public.failure_modes_by_product set (security_invoker = on);
grant select on public.failure_modes_by_product to authenticated;

-- The joins these views make, indexed. `spare_consumption.ucn` is the one that
-- matters: without it every rollup is a hash of the whole consumption history
-- against the whole call register.
create index if not exists spare_consumption_ucn_idx on public.spare_consumption (ucn);
create index if not exists field_calls_product_idx on public.field_calls (product_name);
create index if not exists installation_calls_product_idx on public.installation_calls (product_name);
create index if not exists pm_calls_product_idx on public.pm_calls (product_name);

-- ------------------------------------------------------------------------
-- 0128_kpi_field_inst.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE KPI WORKBOOK'S "Field_INST" SHEET, FROM THE REGISTER.
--
-- The user's KPI workbook is maintained by hand; this is its Field_INST tab
-- computed from the calls instead. PHASE 1 (their scoping, 2026-09-07) is
-- columns A to AB — the same fields, in the same order, under the same
-- headings — plus the two dates the sheet fills in by eye. AC to AG (Attended
-- in Days, Solved in Days, TTA, TTS, Failure Month) are formulas in the
-- workbook and are Phase 2.
--
-- THE THREE RULES THEY GAVE, and each is a decision, not a detail:
--
--   CALL ATTENDED ON = the EARLIER of the first visit and the first spare
--   request. A spare raised before anyone visits is still somebody attending
--   to the call — often the first thing that happens on a fault that needs a
--   part. `least()` ignores NULLs in Postgres, so a call with one and not the
--   other gets the one it has, and a call with neither is blank.
--
--   CALL SOLVED = the visit date of the entry that moved it to "Solved -
--   Report Completed". Not the last visit, and not the day somebody typed it
--   in: the visit on which the machine was actually fixed. Where a call was
--   solved, reopened and solved again, it is the LATEST such entry, because
--   that is the one the call's current status comes from (0032 — the latest
--   ENTRY, `updated_at desc, id desc`, not the latest visit DATE).
--
--   OPEN / CLOSE = Close ONLY when the call is Solved - Report Completed.
--   Anything else is Open, including "Solved - Report Pending": the workbook
--   counted a report-pending call as open and so does this.
--
--   CANCELLED CALLS ARE NOT CONSIDERED AT ALL — not as Open, not as Close,
--   not in the row count. The sheet counted them as Close, which is why its
--   581 "Close" rows are 563 completed calls plus 18 cancellations; this view
--   drops them, so Close means solved and nothing else.
--
-- PM calls are not here: the workbook keeps them on their own tab.
-- ===========================================================================

create or replace view public.kpi_field_inst as
with c as (
  select ucn, call_number, reg_at, reg_date, complaint_date, party_name, city, state,
         product_name, serial, item_status, warranty_number, warranty_start, warranty_end,
         contract_number, contract_start, contract_end, contract_type, call_type,
         standard_complaint, complaint_reported, allocated_to, breakdown_date
    from public.field_calls where cancelled_at is null
  union all
  select ucn, call_number, reg_at, reg_date, complaint_date, party_name, city, state,
         product_name, serial, item_status, warranty_number, warranty_start, warranty_end,
         contract_number, contract_start, contract_end, contract_type, call_type,
         standard_complaint, complaint_reported, allocated_to, breakdown_date
    from public.installation_calls where cancelled_at is null
),
-- The call's CURRENT visit — the latest ENTRY, which is what its status comes
-- from. A call with no visit has none, and reads as Unattended below.
latest as (
  select distinct on (ucn) ucn, call_status, pending_reason, engineer
    from public.reports
   order by ucn, updated_at desc, id desc
),
-- The entry that put it at Solved - Report Completed, latest first so a call
-- solved twice reports the solve that is currently standing.
solved as (
  select distinct on (ucn) ucn, visit_at
    from public.reports
   where call_status ilike 'solved%report%complet%'
   order by ucn, updated_at desc, id desc
),
first_visit as (
  select ucn, min(visit_at) as at from public.reports where visit_at is not null group by ucn
),
-- The first spare RAISED on the call. or_req_date is the request's own date;
-- created_at is when the row was written, and is the fallback for an imported
-- request that never carried one.
first_spare as (
  select ucn, min(coalesce(or_req_date, created_at::date)) as on_date
    from public.spare_requests
   where coalesce(btrim(ucn), '') <> ''
   group by ucn
)
select
  c.ucn                                          as "UC Number",
  c.call_number                                  as "Call Number",
  coalesce(c.reg_at, c.reg_date::timestamptz)    as "Call Registeration Date",
  c.complaint_date                               as "Complaint Date",
  c.party_name                                   as "Party Name",
  c.city                                         as "City",
  c.state                                        as "State",
  c.product_name                                 as "Product Name",
  c.serial                                       as "Product Serial Number",
  c.item_status                                  as "Item Status",
  c.warranty_number                              as "Warranty Number",
  c.warranty_start                               as "Warranty Start Date",
  c.warranty_end                                 as "Warranty End Date",
  c.contract_number                              as "Contract Number",
  c.contract_start                               as "Contract Start Date",
  c.contract_end                                 as "Contract End Date",
  c.contract_type                                as "Contract Type",
  c.call_type                                    as "Call Type",
  c.standard_complaint                           as "Standard Complaint",
  c.complaint_reported                           as "Complaint Reported",
  c.allocated_to                                 as "Call Allocated To",
  c.breakdown_date                               as "Breakdown Date",
  case when s.visit_at is not null then 'Close' else 'Open' end
                                                 as "Open/Close",
  coalesce(nullif(btrim(l.call_status), ''), 'Unattended')
                                                 as "Call Status",
  coalesce(l.pending_reason, '')                 as "CALL PENDING REASON",
  coalesce(l.engineer, '')                       as "Visiting Service Engineer",
  least(fv.at::date, fs.on_date)                 as "Call Attended On",
  s.visit_at::date                               as "Call Solved Date & Time"
  from c
  left join latest      l  on l.ucn  = c.ucn
  left join solved      s  on s.ucn  = c.ucn
  left join first_visit fv on fv.ucn = c.ucn
  left join first_spare fs on fs.ucn = c.ucn;

-- READS AS THE READER. Without this the view runs as its owner and row-level
-- security stops applying: an engineer's export would be every call in the
-- company. `create or replace view` DROPS the setting, so it is re-asserted
-- here and must be on every rebuild (CLAUDE.md).
alter view public.kpi_field_inst set (security_invoker = on);
grant select on public.kpi_field_inst to authenticated;

comment on view public.kpi_field_inst is
  'The KPI workbook''s Field_INST tab, columns A-AB, from the register. Cancelled calls are excluded entirely; Close means Solved - Report Completed and nothing else; Call Attended On is the earlier of the first visit and the first spare request; Call Solved is the visit date of the entry that completed it. AC-AG are workbook formulas (Phase 2).';

commit;
