-- ===========================================================================
-- RITHI CRM — Product Database 2.0: apply bundle
--
-- One row per MACHINE — model and serial — assembled from the warranty
-- sale register, the contract register, the additional entries, the
-- ownership transfer register and the installation call. A VIEW beside
-- `products` and `machine_cover`, which it does not touch.
-- 
-- A MODULE OF ITS OWN BECAUSE OF WHERE IT HAS TO RUN, not because it is
-- big. It reads `imported_ts()` (0215, in `performance`) and
-- `cover_code()` (0208, in `data_integrity`), and both a SQL-language
-- function body and a view are resolved AT CREATION — so filed with the
-- registers it reads it died twice, first on cover_code and then on
-- imported_ts. Everything it needs exists only after the last module,
-- so it runs after the last module. `check:replay` found both.
-- 
-- IT IS MATERIALISED (0220). The plain view TIMED OUT in use: the
-- screen pages it, so all five registers were re-derived on every
-- page -- 2,936 ms a page measured under RLS, against a Supabase
-- statement timeout. It is now a matview plus a thin gating view
-- (3-6 ms a page), rebuilt by `refresh_product_database_2()`.
-- IT KEEPS ITSELF ALIVE (0223). The five registers mark it stale on
-- change -- a STATEMENT-level trigger, so a 12,000-row upload costs
-- one flag write -- and pg_cron rebuilds every five minutes only if
-- something moved. The COVER STATUS is not stored at all (0222): it
-- depends on today, so materialising it froze it at the last
-- rebuild, and it is computed on every read instead.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0218_product_database_v2.sql
--   0220_product_database_2_is_materialised.sql
--   0221_product_database_2_needs_no_gate.sql
--   0222_status_is_computed_when_read.sql
--   0223_product_database_2_keeps_itself_alive.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regprocedure('public.imported_ts(jsonb,text)') is null then
    missing := array_append(missing, 'imported_ts() — 0215_visit_dates_fall_back_to_first_booked.sql (apply bundle: performance)');
  end if;
  if to_regprocedure('public.cover_code(text)') is null then
    missing := array_append(missing, 'cover_code() — 0208_cover_code_normalised.sql (apply bundle: data_integrity)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0218_product_database_v2.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- PRODUCT DATABASE 2.0 — THE MACHINE AS THE REGISTERS TOGETHER DESCRIBE IT.
--
--   The user, 2026-09-20: "All unique product+serial no should be listed
--   [ Source = Warranty Sale Details, Contract Details, Additional Entries ],
--   then arrange these sources + Ownership Transfer to come to a conclusion on
--   the Party, Warranty period, contract period, then derive the item status
--   based on the warranty period & Contract period."
--
-- THE EXISTING `products` TABLE IS NOT TOUCHED, and neither is `machine_cover`.
-- This is a VIEW beside them ("Do Not disturb the current product Database,
-- create this as Product Database 2.0"), so nothing that reads either changes
-- behaviour and the two can be compared on live data before anything moves.
--
-- WHY IT IS NOT `machine_cover` WITH MORE COLUMNS. That view answers the same
-- question and gets three things differently, each of which this one had to
-- settle rather than inherit:
--
--   1. IT KEYS ON THE SERIAL ALONE (`lower(btrim(serial_number))`). This
--      project's own `src/lib/machine.ts` says why that is wrong -- "a machine
--      is its MODEL plus its SERIAL, never the serial alone... the install base
--      has eleven machines numbered 219" -- and a serial-only key MERGES those
--      eleven into one row wearing one machine's cover. This view keys on
--      product + serial.
--   2. IT READS TWO REGISTERS. Additional Entries (0073 — the machines
--      recovered by hand, which exist precisely because the two registers
--      missed them) and Ownership Transfer (0072) are not consulted at all, so
--      a machine that changed hands still reads as the original buyer's.
--   3. ITS STATUS PUTS CONTRACT FIRST: `when contract_end >= today then
--      contract_type when warranty_end >= today then 'WGP'`. The user's rule is
--      the other way round -- "If it's under warranty then WGP, if it's under
--      Contract check the type" -- which changes the answer for every machine
--      that is inside both, and a machine in warranty is not being billed under
--      its contract.
--
-- EVERY DERIVED FIELD SAYS WHERE IT CAME FROM. `party_from`, `warranty_from`,
-- `contract_from` and `item_status_reason` are columns, not comments: a value
-- assembled from five registers that cannot show its evidence is one nobody can
-- check, and this whole view is an opinion about somebody's machine.
--
-- NOTHING IS INVENTED. A machine with no warranty date anywhere gets no
-- warranty, not a guessed one; an unrecognised contract type is carried through
-- UNCHANGED rather than bucketed (the 0208 rule -- "a guess written into a
-- quality record is worse than a value that reads as odd").
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- WHICH MACHINE — the SQL twin of `machineKey()` in `src/lib/machine.ts`.
--
-- Squashed, not merely lowercased: "ORION-G", "ORION G" and "ORIONG" are one
-- model, and splitting them would list one machine three times with a third of
-- its cover on each. That is the client's rule and `check:ui` compares the two
-- word for word, so there is ONE definition of which machine this is.
--
-- The generated `machine_key` columns on `products` and
-- `product_additional_entries` are `lower(btrim(...))` and are LEFT ALONE: they
-- exist to make those tables' own uniqueness indexes, and changing a stored
-- generated column is a rewrite of both tables for no gain here.
-- ---------------------------------------------------------------------------
create or replace function public.machine_key(p_product text, p_serial text)
returns text language sql immutable as $$
  select regexp_replace(lower(coalesce(p_product, '')), '[^a-z0-9]', '', 'g')
      || '|'
      || regexp_replace(lower(coalesce(p_serial, '')),  '[^a-z0-9]', '', 'g')
$$;
comment on function public.machine_key(text, text) is
  'Which machine: model + serial, squashed. The SQL twin of machineKey() in src/lib/machine.ts; check:ui compares them.';

-- ---------------------------------------------------------------------------
-- WHAT A CONTRACT COVERS — labour or comprehensive.
--
--   The user: "check the type of contract - labor/amc maps to AMC,
--   Comprehensive/CMC maps to CMC".
--
-- `cover_code()` (0208) already knows AMC and CMC; it does not know LABOUR or
-- COMPREHENSIVE, which are the words the contract register actually carries.
-- This adds those two families and then DEFERS to cover_code for everything
-- else, so there is still one vocabulary and one place that decides it.
--
-- AN UNRECOGNISED TYPE COMES BACK UNCHANGED. `machine_cover` defaults it to
-- 'CMC' (`coalesce(nullif(contract_type, ''), 'CMC')`), which silently upgrades
-- a labour contract to comprehensive on the strength of a blank cell -- and a
-- guess written into a quality record is worse than a value that reads as odd,
-- because the odd one gets reported.
-- ---------------------------------------------------------------------------
create or replace function public.contract_cover_code(p_type text)
returns text language sql immutable as $$
  select case
    when p_type is null or btrim(p_type) = '' then null
    when regexp_replace(lower(p_type), '[^a-z0-9]', '', 'g') in
         ('labour', 'labor', 'labourcontract', 'laborcontract',
          'amc', 'annualmaintenancecontract', 'underamc', 'labouramc', 'laboramc')
      then 'AMC'
    when regexp_replace(lower(p_type), '[^a-z0-9]', '', 'g') in
         ('comprehensive', 'comprehensivecontract', 'cmc',
          'comprehensivemaintenancecontract', 'undercmc')
      then 'CMC'
    else public.cover_code(p_type)
  end
$$;
comment on function public.contract_cover_code(text) is
  'Contract type -> AMC (labour) or CMC (comprehensive); anything else is returned unchanged, never bucketed.';

-- ---------------------------------------------------------------------------
-- WHEN A PERIOD ENDS — the application's rule, in SQL.
--
-- `addPeriod(start, 0, months)` in `src/lib/dates.ts` is what the app uses, and
-- it carries JAVASCRIPT's month arithmetic: `setMonth` OVERFLOWS rather than
-- clamping, so 31 January plus one month is 3 March (Feb 31 rolls forward), not
-- 28 February. Postgres's `+ interval '1 month'` CLAMPS to 28 February.
--
-- A plain `+ make_interval(months => n)` here would therefore disagree with
-- every end date the application has ever computed, on exactly the month-end
-- starts that a yearly warranty is most likely to have. So the overflow is
-- reproduced: go to the first of the start month, add the months, then add back
-- the day-of-month, then step back one day.
--
-- It is PROVED against `addPeriod` rather than reasoned about -- see
-- `product_database_v2_test.sql`, which walks every start day of every month
-- against a range of periods.
-- ---------------------------------------------------------------------------
create or replace function public.cover_period_end(p_start date, p_months numeric)
returns date language sql immutable as $$
  select case
    when p_start is null or p_months is null or p_months <= 0 then null
    else (date_trunc('month', p_start)::date
          + make_interval(months => round(p_months)::int)
          + make_interval(days   => extract(day from p_start)::int - 1))::date
         - 1
  end
$$;
comment on function public.cover_period_end(date, numeric) is
  'Start + period - 1 day, reproducing addPeriod() in src/lib/dates.ts including its JavaScript month overflow.';

-- ===========================================================================
-- THE VIEW.
--
-- One row per MACHINE that any of the three registers names. Everything else
-- is assembled around that row, and every assembled value carries the name of
-- the register it came from.
-- ===========================================================================
-- DROPPED FIRST, AND NOT FOR TIDINESS. 0220 replaces this name with a THIN
-- gating view over a materialised one, which publishes a column this
-- definition does not — so on a REPLAY of this bundle (which runs 0218 then
-- 0220, one file at a time) `create or replace view` hits "cannot drop columns
-- from view" and the whole bundle stops. `check:replay` caught exactly that.
-- The drop is safe in both directions: nothing depends on this view, and 0220
-- rebuilds the matview and the gate straight after.
drop view if exists public.product_database_v2 cascade;
create view public.product_database_v2 as
with w as (
  -- THE WARRANTY SALE — the machine's birth record. Latest by the cover it
  -- grants, so a re-sale or a corrected row wins over the one it replaced.
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, sa_number,
         warranty_start, warranty_end, warranty_years, warranty_months,
         sale_entry_date, invoice_date, state, city, engineer
    from public.warranty_sale_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, warranty_end desc nulls last, id desc
), c as (
  -- THE CONTRACT — latest by the cover it grants, so a renewal wins over the
  -- contract it succeeded (0187/FRS-056: the successor starts the day after).
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, mc_number,
         contract_type, contract_start, contract_end, contract_years,
         contract_months, contract_entry_date
    from public.contract_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, contract_end desc nulls last, id desc
), a as (
  -- ADDITIONAL ENTRIES (0073) — the machines recovered by hand because neither
  -- register had them. Already one row per machine by its own unique index.
  select public.machine_key(item_name, serial_number) as mkey,
         id, item_name, serial_number, party_name,
         warranty_number, warranty_start, warranty_end,
         contract_number, contract_type, contract_start, contract_end, created_at
    from public.product_additional_entries
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
), o as (
  -- OWNERSHIP TRANSFER (0072) — the explicit, dated record that the machine
  -- changed hands. Latest transfer wins; a machine can move more than once.
  select distinct on (public.machine_key(item_name, serial_number))
         public.machine_key(item_name, serial_number) as mkey,
         id, to_party, from_party, transfer_date, reference_no
    from public.ownership_transfers
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
   order by 1, transfer_date desc nulls last, id desc
), inst as (
  -- THE INSTALLATION CALL, which is where a warranty actually starts.
  --
  --   The user: "for warranty Start date check the installation call detail -
  --   in feedback/reporting there is a question - Warranty Start Date -- if
  --   it's call solved date then take the warranty Start date from the call
  --   solved date".
  --
  -- The answer is read through `imported_ts()` (0215) rather than cast: it is a
  -- cell somebody typed, and a bare `::date` on "n/a" would not spoil one row,
  -- it would take THE WHOLE VIEW down. The call's solved date is the fallback,
  -- which is the same date the question is asking the engineer to confirm.
  select distinct on (public.machine_key(cl.product_name, cl.serial))
         public.machine_key(cl.product_name, cl.serial) as mkey,
         cl.ucn,
         public.imported_ts(fb.answers, 'Warranty Start Date?')::date as answered_start,
         case when cl.open_state = 'Solved' then cl.last_visit_at::date end as solved_on
    from public.calls cl
    left join public.feedback fb on fb.ucn = cl.ucn
   where upper(coalesce(cl.call_type, '')) like 'INSTALL%'
     and coalesce(btrim(cl.serial), '')       <> ''
     and coalesce(btrim(cl.product_name), '') <> ''
   order by 1, cl.last_visit_at desc nulls last, cl.ucn desc
), keys as (
  select mkey from w union select mkey from c union select mkey from a
), base as (
  select
    k.mkey,
    coalesce(w.product_name, c.product_name, a.item_name)        as product_name,
    coalesce(w.serial_number, c.serial_number, a.serial_number)  as serial_number,
    coalesce(w.product_code, c.product_code)                     as product_code,
    -- ---- the warranty, in the order the user gave -------------------------
    coalesce(i.answered_start, i.solved_on, a.warranty_start, w.warranty_start) as warranty_start,
    coalesce(w.warranty_months, (w.warranty_years * 12)::int)                   as warranty_months,
    a.warranty_end  as a_warranty_end,
    w.warranty_end  as w_warranty_end,
    case when i.answered_start is not null then 'Installation call ' || i.ucn
         when i.solved_on      is not null then 'Installation call ' || i.ucn || ' (solved date)'
         when a.warranty_start is not null then 'Additional entry'
         when w.warranty_start is not null then 'Warranty sale ' || coalesce(w.sa_number, '')
         else null end                                           as warranty_from,
    -- ---- the contract -----------------------------------------------------
    coalesce(c.contract_start, a.contract_start)                 as contract_start,
    coalesce(c.contract_months, (c.contract_years * 12)::int)    as contract_months,
    coalesce(c.contract_end, a.contract_end)                     as contract_end_stored,
    coalesce(c.contract_type, a.contract_type)                   as contract_type_raw,
    coalesce(c.mc_number, a.contract_number)                     as contract_number,
    case when c.id is not null then 'Contract ' || coalesce(c.mc_number, '')
         when a.contract_start is not null or a.contract_end is not null then 'Additional entry'
         else null end                                           as contract_from,
    -- ---- who owns it ------------------------------------------------------
    p.party_name, p.party_from,
    w.sa_number, w.state, w.city, w.engineer,
    o.from_party, o.to_party, o.transfer_date, o.reference_no,
    (w.mkey is not null) as in_warranty_register,
    (c.mkey is not null) as in_contract_register,
    (a.mkey is not null) as in_additional_entries,
    i.ucn as installation_ucn
  from keys k
  left join w on w.mkey = k.mkey
  left join c on c.mkey = k.mkey
  left join a on a.mkey = k.mkey
  left join o on o.mkey = k.mkey
  left join inst i on i.mkey = k.mkey
  -- WHOSE MACHINE IS IT: the LATEST DATED EVIDENCE wins, not a fixed order of
  -- registers. A machine sold in 2020, transferred in 2021 and then put under a
  -- new contract in 2024 belongs to whoever the 2024 contract names -- an
  -- ownership transfer is not permanently the last word, it is one dated claim
  -- among several. Ties break towards the record that exists SPECIFICALLY to
  -- say the machine changed hands.
  left join lateral (
    select v.party_name, v.party_from
      from (values
        (o.to_party,    'Ownership transfer ' || coalesce(o.reference_no, ''), o.transfer_date,           1),
        (a.party_name,  'Additional entry',                                    a.created_at::date,        2),
        (c.party_name,  'Contract ' || coalesce(c.mc_number, ''),              c.contract_start,          3),
        (w.party_name,  'Warranty sale ' || coalesce(w.sa_number, ''),
                        coalesce(w.sale_entry_date::date, w.invoice_date),                                4)
      ) as v(party_name, party_from, on_date, rank)
     where coalesce(btrim(v.party_name), '') <> ''
     order by v.on_date desc nulls last, v.rank
     limit 1
  ) p on true
)
select
  b.mkey                                   as machine_key,
  b.product_name,
  b.serial_number,
  b.product_code,
  b.party_name,
  b.party_from,
  -- ---- warranty ----------------------------------------------------------
  b.warranty_start,
  b.warranty_months,
  -- DERIVED where the start and the period are both known -- which is what the
  -- user asked for ("derive at the warranty end date") -- and the register's
  -- own end date otherwise, so a machine whose period nobody recorded still
  -- shows the cover it was sold.
  case when b.warranty_start is not null and b.warranty_months is not null
       then public.cover_period_end(b.warranty_start, b.warranty_months)
       else coalesce(b.a_warranty_end, b.w_warranty_end) end     as warranty_end,
  b.warranty_from,
  public.cover_state(
    case when b.warranty_start is not null and b.warranty_months is not null
         then public.cover_period_end(b.warranty_start, b.warranty_months)
         else coalesce(b.a_warranty_end, b.w_warranty_end) end)  as warranty_state,
  -- ---- contract ----------------------------------------------------------
  b.contract_number,
  b.contract_type_raw                                            as contract_type_as_recorded,
  public.contract_cover_code(b.contract_type_raw)                as contract_type,
  b.contract_start,
  b.contract_months,
  coalesce(b.contract_end_stored,
           public.cover_period_end(b.contract_start, b.contract_months)) as contract_end,
  b.contract_from,
  public.cover_state(
    coalesce(b.contract_end_stored,
             public.cover_period_end(b.contract_start, b.contract_months))) as contract_state,
  -- ---- what it is under TODAY --------------------------------------------
  -- WARRANTY FIRST. The user's rule, and the opposite of `machine_cover`: a
  -- machine inside its warranty is not being billed under its contract, so the
  -- contract does not decide its status while the warranty runs.
  case
    when coalesce(
           case when b.warranty_start is not null and b.warranty_months is not null
                then public.cover_period_end(b.warranty_start, b.warranty_months)
                else coalesce(b.a_warranty_end, b.w_warranty_end) end,
           '-infinity'::date) >= current_date
      then 'WGP'
    when coalesce(b.contract_end_stored,
                  public.cover_period_end(b.contract_start, b.contract_months),
                  '-infinity'::date) >= current_date
      -- A CONTRACT WITH NO TYPE IS NOT GUESSED AT. `machine_cover` calls it
      -- CMC, which upgrades a labour contract to comprehensive on the strength
      -- of a blank cell; this says so instead, because that row needs fixing.
      then coalesce(public.contract_cover_code(b.contract_type_raw), 'CONTRACT (TYPE NOT RECORDED)')
    else 'OGP'
  end                                                            as item_status,
  case
    when coalesce(
           case when b.warranty_start is not null and b.warranty_months is not null
                then public.cover_period_end(b.warranty_start, b.warranty_months)
                else coalesce(b.a_warranty_end, b.w_warranty_end) end,
           '-infinity'::date) >= current_date
      then 'inside warranty — ' || coalesce(b.warranty_from, 'source not recorded')
    when coalesce(b.contract_end_stored,
                  public.cover_period_end(b.contract_start, b.contract_months),
                  '-infinity'::date) >= current_date
      then 'under contract — ' || coalesce(b.contract_from, 'source not recorded')
    else 'no warranty and no contract covers today'
  end                                                            as item_status_reason,
  -- ---- where it came from, so the row can be checked ---------------------
  b.sa_number, b.state, b.city, b.engineer,
  b.from_party, b.to_party, b.transfer_date, b.reference_no,
  b.in_warranty_register, b.in_contract_register, b.in_additional_entries,
  b.installation_ucn
  from base b;

-- RE-ASSERTED, as it must be on every rebuild: without it the view reads as its
-- OWNER and row-level security stops applying to whoever is reading, with no
-- error and no warning (0040/0050/0057).
alter view public.product_database_v2 set (security_invoker = on);

-- THE GRANT. 28 of the 30 views these migrations create carry one and this did
-- not; the only other exception is `calls`, which replaced a TABLE and inherited
-- its privileges. Supabase's default privileges usually cover a view created by
-- `postgres`, which is why the omission can hide -- but "usually" is not a rule
-- to rely on for the one object a new screen reads, and a project rebuilt in a
-- different order does not get it.
--
-- `security_invoker` is what actually decides the ROWS (set above): this grant
-- opens the view, row-level security on the five registers underneath still
-- applies to whoever is reading, so nobody sees a machine they could not
-- already see through the registers themselves.
grant select on public.product_database_v2 to authenticated;

comment on view public.product_database_v2 is
  'Product Database 2.0: one row per machine (model + serial) assembled from Warranty Sale Details, Contract Details, Additional Entries, Ownership Transfer and the installation call. Every derived value names the register it came from. Does not replace public.products.';

-- ------------------------------------------------------------------------
-- 0220_product_database_2_is_materialised.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- PRODUCT DATABASE 2.0 TIMED OUT. This is the repair, and it is structural.
--
--   Reported from use, 2026-09-20, as an empty screen and the banner
--   "Load failed: canceling statement due to statement timeout".
--
-- MEASURED, NOT REASONED ABOUT. A throwaway Postgres built from every
-- migration, loaded to the live project's own order of magnitude (12,000
-- warranty sale items, 5,000 contract items, 22,000 calls, 24,000 feedback
-- rows, 10,000 machines), then timed as `postgres` and again under RLS as
-- `authenticated` with an admin profile:
--
--   count(*), no RLS ............................     164 ms
--   count(*), RLS ..............................   1,361 ms
--   one page (select *, order by, limit 1000) ..   2,936 ms   <-- the screen
--
-- The screen PAGES the view, so the whole derivation ran again for every page:
-- ten pages at ~3 s is ~30 s of database time for one screen, and each single
-- page is already past Supabase's statement timeout on live volumes.
--
-- WHERE IT WENT. The installation-call lookup alone, isolated and timed both
-- ways: 24 ms without RLS, 1,255 ms with it -- FIFTY-TWO TIMES, because
-- `calls` is the one source in this view whose read policy is per ROW
-- (`can_view_all_calls() OR mine OR my team's`, and the team branch walks
-- `user_directory` recursively). The other four sources have whole-table
-- predicates that cost the same whether there is one row or a million.
--
-- SO THE FIX HAS TWO PARTS, AND THE FIRST ONE IS ABOUT CORRECTNESS, NOT SPEED.
--
-- 1. `machine_install_start()` is SECURITY DEFINER. A machine's warranty start
--    date is a FACT ABOUT THE MACHINE, and reading it through a per-row policy
--    made it a fact about the READER: two people looking at the same machine
--    got different warranty dates, and the one who could not see the
--    installation call got the selling register's date with nothing saying so.
--    On a quality record that is worse than the slowness. It returns four
--    columns for the latest installation call per machine -- key, UCN, the
--    answered start, the solved date -- and nothing else about the call.
--    EXECUTE is granted to `authenticated` only.
--
-- 2. THE VIEW IS MATERIALISED. The definer function alone took a page from
--    2,936 ms to 1,764 ms -- better and still hopeless, because the real cost
--    is re-deriving 10,000 machines out of eight tables ON EVERY PAGE. A view
--    assembled from five registers cannot be paged cheaply; it can only be
--    computed once. With `product_database_v2_mv` and a unique index on
--    `machine_key`, the same three reads measure:
--
--      count(*) .....   5 ms      first page ..  3 ms      last page ..  6 ms
--
--    ~600x on the page the user actually waits for, and the ten-page load goes
--    from ~30 s to under a tenth of a second.
--
-- WHAT IT COSTS, SAID PLAINLY: the numbers are AS OF THE LAST REBUILD. That is
-- a real cost and it is made visible rather than hidden -- `refreshed_at` is
-- published as a column of the view, the screen prints it, and anybody who may
-- edit masters can rebuild from the screen. A stale figure nobody can date is
-- the fault this project has written down more than once; a stale figure with
-- its date on it is an ordinary report.
--
-- THE GATE IS KEPT, BECAUSE A MATERIALISED VIEW HAS NO RLS. `product_database_v2`
-- remains a security_invoker VIEW, now a thin one over the matview, carrying
-- the SAME whole-table predicate as `sale_items_read` and `contract_items_read`
-- (`masters.view` OR `cover.edit` OR admin) -- the narrowest of its sources, so
-- this widens nobody's reach. The matview itself is granted to NOBODY and is
-- reachable only through that view.
--
-- WHAT IS DELIBERATELY NOT DONE: the per-row `calls` policy is not weakened,
-- `products` and `machine_cover` are untouched (the user's standing rule), and
-- the view publishes exactly the columns it published before plus
-- `refreshed_at` -- APPENDED at the end, because `create or replace view` can
-- only add columns there.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- WHEN THE FIGURES WERE ASSEMBLED. One row, so the screen can date what it
-- shows. Written by the refresh function and by nothing else.
-- ---------------------------------------------------------------------------
create table if not exists public.product_database_v2_state (
  only_row    boolean primary key default true check (only_row),
  refreshed_at timestamptz not null default now(),
  rows_built   integer     not null default 0,
  refreshed_by uuid
);
insert into public.product_database_v2_state (only_row) values (true)
  on conflict (only_row) do nothing;
alter table public.product_database_v2_state enable row level security;
do $$ begin
  create policy pdv2_state_read on public.product_database_v2_state for select
    using (public.has_perm('masters.view') or public.has_perm('cover.edit') or public.is_admin());
exception when duplicate_object then null; end $$;
grant select on public.product_database_v2_state to authenticated;

-- ---------------------------------------------------------------------------
-- THE INSTALLATION CALL, ONCE, FOR EVERYBODY — part 1 above.
--
-- `security definer` with a pinned search_path and no arguments: there is no
-- caller-supplied value anywhere in it, so there is nothing to inject. It
-- exposes, per machine, the UCN of the latest installation call and two dates.
-- Every other fact about that call stays behind the call policies.
-- ---------------------------------------------------------------------------
create or replace function public.machine_install_start()
returns table (mkey text, ucn text, answered_start date, solved_on date)
language sql stable security definer set search_path = public as $$
  select distinct on (public.machine_key(cl.product_name, cl.serial))
         public.machine_key(cl.product_name, cl.serial),
         cl.ucn,
         -- Read through imported_ts() (0215) rather than cast: it is a cell
         -- somebody typed, and a bare ::date on "n/a" takes the WHOLE view down.
         public.imported_ts(fb.answers, 'Warranty Start Date?')::date,
         case when cl.open_state = 'Solved' then cl.last_visit_at::date end
    from public.calls cl
    left join public.feedback fb on fb.ucn = cl.ucn
   where upper(coalesce(cl.call_type, '')) like 'INSTALL%'
     and coalesce(btrim(cl.serial), '')       <> ''
     and coalesce(btrim(cl.product_name), '') <> ''
   order by 1, cl.last_visit_at desc nulls last, cl.ucn desc
$$;
comment on function public.machine_install_start() is
  'The latest installation call per machine: key, UCN, the answered Warranty Start Date and the solved date. DEFINER on purpose (0220) — a machine''s warranty start is a fact about the MACHINE, not about who is looking, and reading it through the per-row calls policy both changed the answer per reader and cost 1,255 ms of every page.';
revoke all on function public.machine_install_start() from public;
grant execute on function public.machine_install_start() to authenticated;

-- ---------------------------------------------------------------------------
-- THE MACHINES, COMPUTED ONCE — part 2 above.
-- The view must go first: 0218 created it as a plain view and the name is
-- being reused for the gating view below.
-- ---------------------------------------------------------------------------
drop view if exists public.product_database_v2 cascade;
drop materialized view if exists public.product_database_v2_mv cascade;
create materialized view public.product_database_v2_mv as
with w as (
  -- THE WARRANTY SALE — the machine's birth record. Latest by the cover it
  -- grants, so a re-sale or a corrected row wins over the one it replaced.
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, sa_number,
         warranty_start, warranty_end, warranty_years, warranty_months,
         sale_entry_date, invoice_date, state, city, engineer
    from public.warranty_sale_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, warranty_end desc nulls last, id desc
), c as (
  -- THE CONTRACT — latest by the cover it grants, so a renewal wins over the
  -- contract it succeeded (0187/FRS-056: the successor starts the day after).
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, mc_number,
         contract_type, contract_start, contract_end, contract_years,
         contract_months, contract_entry_date
    from public.contract_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, contract_end desc nulls last, id desc
), a as (
  -- ADDITIONAL ENTRIES (0073) — the machines recovered by hand because neither
  -- register had them. Already one row per machine by its own unique index.
  select public.machine_key(item_name, serial_number) as mkey,
         id, item_name, serial_number, party_name,
         warranty_number, warranty_start, warranty_end,
         contract_number, contract_type, contract_start, contract_end, created_at
    from public.product_additional_entries
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
), o as (
  -- OWNERSHIP TRANSFER (0072) — the explicit, dated record that the machine
  -- changed hands. Latest transfer wins; a machine can move more than once.
  select distinct on (public.machine_key(item_name, serial_number))
         public.machine_key(item_name, serial_number) as mkey,
         id, to_party, from_party, transfer_date, reference_no
    from public.ownership_transfers
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
   order by 1, transfer_date desc nulls last, id desc
), inst as (
  -- THE INSTALLATION CALL — now read through `machine_install_start()`, a
  -- DEFINER function. See the header: this is both the speed and the
  -- correctness half of 0220.
  select mkey, ucn, answered_start, solved_on from public.machine_install_start()
), keys as (
  select mkey from w union select mkey from c union select mkey from a
), base as (
  select
    k.mkey,
    coalesce(w.product_name, c.product_name, a.item_name)        as product_name,
    coalesce(w.serial_number, c.serial_number, a.serial_number)  as serial_number,
    coalesce(w.product_code, c.product_code)                     as product_code,
    -- ---- the warranty, in the order the user gave -------------------------
    coalesce(i.answered_start, i.solved_on, a.warranty_start, w.warranty_start) as warranty_start,
    coalesce(w.warranty_months, (w.warranty_years * 12)::int)                   as warranty_months,
    a.warranty_end  as a_warranty_end,
    w.warranty_end  as w_warranty_end,
    case when i.answered_start is not null then 'Installation call ' || i.ucn
         when i.solved_on      is not null then 'Installation call ' || i.ucn || ' (solved date)'
         when a.warranty_start is not null then 'Additional entry'
         when w.warranty_start is not null then 'Warranty sale ' || coalesce(w.sa_number, '')
         else null end                                           as warranty_from,
    -- ---- the contract -----------------------------------------------------
    coalesce(c.contract_start, a.contract_start)                 as contract_start,
    coalesce(c.contract_months, (c.contract_years * 12)::int)    as contract_months,
    coalesce(c.contract_end, a.contract_end)                     as contract_end_stored,
    coalesce(c.contract_type, a.contract_type)                   as contract_type_raw,
    coalesce(c.mc_number, a.contract_number)                     as contract_number,
    case when c.id is not null then 'Contract ' || coalesce(c.mc_number, '')
         when a.contract_start is not null or a.contract_end is not null then 'Additional entry'
         else null end                                           as contract_from,
    -- ---- who owns it ------------------------------------------------------
    p.party_name, p.party_from,
    w.sa_number, w.state, w.city, w.engineer,
    o.from_party, o.to_party, o.transfer_date, o.reference_no,
    (w.mkey is not null) as in_warranty_register,
    (c.mkey is not null) as in_contract_register,
    (a.mkey is not null) as in_additional_entries,
    i.ucn as installation_ucn
  from keys k
  left join w on w.mkey = k.mkey
  left join c on c.mkey = k.mkey
  left join a on a.mkey = k.mkey
  left join o on o.mkey = k.mkey
  left join inst i on i.mkey = k.mkey
  -- WHOSE MACHINE IS IT: the LATEST DATED EVIDENCE wins, not a fixed order of
  -- registers. A machine sold in 2020, transferred in 2021 and then put under a
  -- new contract in 2024 belongs to whoever the 2024 contract names -- an
  -- ownership transfer is not permanently the last word, it is one dated claim
  -- among several. Ties break towards the record that exists SPECIFICALLY to
  -- say the machine changed hands.
  left join lateral (
    select v.party_name, v.party_from
      from (values
        (o.to_party,    'Ownership transfer ' || coalesce(o.reference_no, ''), o.transfer_date,           1),
        (a.party_name,  'Additional entry',                                    a.created_at::date,        2),
        (c.party_name,  'Contract ' || coalesce(c.mc_number, ''),              c.contract_start,          3),
        (w.party_name,  'Warranty sale ' || coalesce(w.sa_number, ''),
                        coalesce(w.sale_entry_date::date, w.invoice_date),                                4)
      ) as v(party_name, party_from, on_date, rank)
     where coalesce(btrim(v.party_name), '') <> ''
     order by v.on_date desc nulls last, v.rank
     limit 1
  ) p on true
)
select
  b.mkey                                   as machine_key,
  b.product_name,
  b.serial_number,
  b.product_code,
  b.party_name,
  b.party_from,
  -- ---- warranty ----------------------------------------------------------
  b.warranty_start,
  b.warranty_months,
  -- DERIVED where the start and the period are both known -- which is what the
  -- user asked for ("derive at the warranty end date") -- and the register's
  -- own end date otherwise, so a machine whose period nobody recorded still
  -- shows the cover it was sold.
  case when b.warranty_start is not null and b.warranty_months is not null
       then public.cover_period_end(b.warranty_start, b.warranty_months)
       else coalesce(b.a_warranty_end, b.w_warranty_end) end     as warranty_end,
  b.warranty_from,
  public.cover_state(
    case when b.warranty_start is not null and b.warranty_months is not null
         then public.cover_period_end(b.warranty_start, b.warranty_months)
         else coalesce(b.a_warranty_end, b.w_warranty_end) end)  as warranty_state,
  -- ---- contract ----------------------------------------------------------
  b.contract_number,
  b.contract_type_raw                                            as contract_type_as_recorded,
  public.contract_cover_code(b.contract_type_raw)                as contract_type,
  b.contract_start,
  b.contract_months,
  coalesce(b.contract_end_stored,
           public.cover_period_end(b.contract_start, b.contract_months)) as contract_end,
  b.contract_from,
  public.cover_state(
    coalesce(b.contract_end_stored,
             public.cover_period_end(b.contract_start, b.contract_months))) as contract_state,
  -- ---- what it is under TODAY --------------------------------------------
  -- WARRANTY FIRST. The user's rule, and the opposite of `machine_cover`: a
  -- machine inside its warranty is not being billed under its contract, so the
  -- contract does not decide its status while the warranty runs.
  case
    when coalesce(
           case when b.warranty_start is not null and b.warranty_months is not null
                then public.cover_period_end(b.warranty_start, b.warranty_months)
                else coalesce(b.a_warranty_end, b.w_warranty_end) end,
           '-infinity'::date) >= current_date
      then 'WGP'
    when coalesce(b.contract_end_stored,
                  public.cover_period_end(b.contract_start, b.contract_months),
                  '-infinity'::date) >= current_date
      -- A CONTRACT WITH NO TYPE IS NOT GUESSED AT. `machine_cover` calls it
      -- CMC, which upgrades a labour contract to comprehensive on the strength
      -- of a blank cell; this says so instead, because that row needs fixing.
      then coalesce(public.contract_cover_code(b.contract_type_raw), 'CONTRACT (TYPE NOT RECORDED)')
    else 'OGP'
  end                                                            as item_status,
  case
    when coalesce(
           case when b.warranty_start is not null and b.warranty_months is not null
                then public.cover_period_end(b.warranty_start, b.warranty_months)
                else coalesce(b.a_warranty_end, b.w_warranty_end) end,
           '-infinity'::date) >= current_date
      then 'inside warranty — ' || coalesce(b.warranty_from, 'source not recorded')
    when coalesce(b.contract_end_stored,
                  public.cover_period_end(b.contract_start, b.contract_months),
                  '-infinity'::date) >= current_date
      then 'under contract — ' || coalesce(b.contract_from, 'source not recorded')
    else 'no warranty and no contract covers today'
  end                                                            as item_status_reason,
  -- ---- where it came from, so the row can be checked ---------------------
  b.sa_number, b.state, b.city, b.engineer,
  b.from_party, b.to_party, b.transfer_date, b.reference_no,
  b.in_warranty_register, b.in_contract_register, b.in_additional_entries,
  b.installation_ucn
  from base b;

-- RE-ASSERTED, as it must be on every rebuild: without it the view reads as its
-- OWNER and row-level security stops applying to whoever is reading, with no
-- error and no warning (0040/0050/0057).;

-- CONCURRENTLY needs a unique index, and CONCURRENTLY is what keeps a rebuild
-- from blocking every reader of the screen. `machine_key` is the view's own
-- identity, so it is unique by construction.
create unique index if not exists product_database_v2_mv_key
  on public.product_database_v2_mv (machine_key);

-- REVOKED EXPLICITLY, AND THIS IS THE WHOLE GATE. Supabase grants the API
-- roles blanket DML on `public` and leaves RLS as the fence — but a
-- MATERIALISED VIEW CANNOT CARRY RLS, so without this the matview inherits
-- that default grant and every authenticated caller can read all five
-- registers' worth of machines straight off it, going round the gating view
-- entirely. Found by a test asserting the opposite, not by reading the file.
revoke all on public.product_database_v2_mv from authenticated, anon, public;

-- ---------------------------------------------------------------------------
-- THE GATE. A materialised view cannot carry RLS, so the name the application
-- reads stays a security_invoker VIEW over it, carrying the SAME whole-table
-- predicate as the narrowest of its sources (`sale_items_read` /
-- `contract_items_read`). Evaluated ONCE per query, not per row.
-- ---------------------------------------------------------------------------
create view public.product_database_v2 as
  select m.*, s.refreshed_at
    from public.product_database_v2_mv m
    cross join public.product_database_v2_state s
   where public.has_perm('masters.view')
      or public.has_perm('cover.edit')
      or public.is_admin()
      -- A DIRECT DATABASE SESSION IS NOT AN API CALLER, and this line is the
      -- 0170 lesson in a second place. The gate is a WHERE clause rather than
      -- RLS (a matview cannot carry RLS), and a WHERE clause is NOT bypassed
      -- by superuser — so without this the SUPABASE SQL EDITOR, which runs as
      -- `postgres` with no JWT, reads ZERO ROWS from this view and reports it
      -- as an empty grid. That is the confidently-wrong answer this project
      -- keeps writing down: nothing in it looks like an error. A direct
      -- connection already holds every table underneath, so admitting it here
      -- guards nothing away. Tested BOTH ways: `request.jwt.claims` is set by
      -- PostgREST on every request including anon, so an API caller never
      -- matches this, and the test harness (which sets auth.uid() from a table
      -- and no claims) still sees an engineer refused.
      or (auth.uid() is null
          and current_setting('request.jwt.claims', true) is null);
alter view public.product_database_v2 set (security_invoker = on);
grant select on public.product_database_v2 to authenticated;
comment on view public.product_database_v2 is
  'Product Database 2.0 — one row per machine, as of refreshed_at. A thin gate over product_database_v2_mv (0220); the matview is granted to nobody.';

-- ---------------------------------------------------------------------------
-- REBUILDING IT. CONCURRENTLY, so nobody reading the screen is blocked, and
-- inside a function, which Postgres does allow (proved, not assumed).
-- ---------------------------------------------------------------------------
create or replace function public.refresh_product_database_2()
returns timestamptz language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if not (public.has_perm('masters.edit') or public.has_perm('cover.edit') or public.is_admin()) then
    raise exception 'Your role may not rebuild Product Database 2.0.' using errcode = '42501';
  end if;
  refresh materialized view concurrently public.product_database_v2_mv;
  select count(*) into n from public.product_database_v2_mv;
  update public.product_database_v2_state
     set refreshed_at = now(), rows_built = n, refreshed_by = auth.uid()
   where only_row;
  return (select refreshed_at from public.product_database_v2_state where only_row);
end $$;
comment on function public.refresh_product_database_2() is
  'Rebuild Product Database 2.0 from the five registers. CONCURRENTLY, so readers are never blocked; requires masters.edit, cover.edit or admin.';
revoke all on function public.refresh_product_database_2() from public;
grant execute on function public.refresh_product_database_2() to authenticated;

-- The matview is built WITH DATA, so record that first build honestly.
update public.product_database_v2_state
   set refreshed_at = now(),
       rows_built   = (select count(*) from public.product_database_v2_mv)
 where only_row;

-- ------------------------------------------------------------------------
-- 0221_product_database_2_needs_no_gate.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- "HOW DOES A SUPER ADMIN NOT HAVE ACCESS TO SOMETHING???" — they do not, and
-- this was never a permission decision. It was a bug in 0220, and the answer to
-- the question is that NOTHING should have been refusing anybody here.
--
--   The user, 2026-09-20, as Rithi Admin / Permission · Admin:
--   "Your role does not have permission to read this."
--   ...and then: "RBAC is creaking my setup, so i am not running it."
--
-- WHAT 0220 GOT WRONG, precisely. It made `product_database_v2` a
-- `security_invoker` view — which reads AS THE CALLER — over a materialised
-- view it had just REVOKED from `authenticated`. Those two lines contradict
-- each other: the caller is required to hold a privilege that was deliberately
-- taken away, so the view refused EVERY reader, administrators included, with
-- `permission denied for materialized view product_database_v2_mv`. It is not
-- a role that is missing something; it is a view that cannot read its own
-- storage.
--
-- WHY THE TESTS DID NOT CATCH IT, WHICH MATTERS MORE THAN THE BUG. The suite
-- said `set local role authenticated` — and **SET LOCAL OUTSIDE A TRANSACTION
-- BLOCK IS A NO-OP**, a warning and nothing else. So every "as authenticated"
-- assertion in it actually ran as `postgres`, which is a superuser and bypasses
-- exactly the privilege check that was broken. The suite passed, twice, while
-- proving nothing about roles at all. It uses `set role` now, and
-- `product_database_2_materialised_test.sql` asserts an ADMIN CAN READ —
-- an assertion that FAILS against 0220 and passes against this file.
--
-- AND THE GATE ITSELF IS GONE, NOT REPAIRED. 0220 invented a permission
-- predicate for this screen that nothing else in its family has, and it is the
-- thing that broke. Four of the five sources this view assembles are already
-- readable by any signed-in user (`products` — the OLD Product Database, and
-- the ~20,000 machines on it — `product_additional_entries`,
-- `ownership_transfers`, and `machine_cover`, which publishes the same machine
-- and cover facts to everybody). The screen is gated where every other screen
-- is gated: by `mod:/product-database-2`, which 0219 put on the roles that hold
-- the old Product Database.
--
-- SAID PLAINLY, BECAUSE IT IS A REAL CHANGE: the warranty and contract detail
-- assembled here is now readable by any signed-in user who can open the screen,
-- where 0220 asked for `masters.view`, `cover.edit` or admin. That brings 2.0
-- into line with the Product Database beside it rather than out of line in the
-- other direction. Putting the gate back is one predicate and a grant, and it
-- is a decision for the user rather than for this file.
-- ===========================================================================

-- The storage the view reads. Granted, because a `security_invoker` view reads
-- AS THE CALLER — this is the half 0220 revoked and then required.
grant select on public.product_database_v2_mv to authenticated;

-- No predicate. A plain, fast pass-through: the machines, and when they were
-- last built. `security_invoker` is re-asserted because `create or replace`
-- drops it (0040/0050/0057), and it is re-asserted on a view that no longer
-- needs it, deliberately — the setting costs nothing and the next person to
-- add an RLS-protected table to this view inherits the right default.
drop view if exists public.product_database_v2 cascade;
create view public.product_database_v2 as
  select m.*, s.refreshed_at
    from public.product_database_v2_mv m
    cross join public.product_database_v2_state s;
alter view public.product_database_v2 set (security_invoker = on);
grant select on public.product_database_v2 to authenticated;
comment on view public.product_database_v2 is
  'Product Database 2.0 — one row per machine, as of refreshed_at. Readable by any signed-in user, like the Product Database beside it; the SCREEN is gated by mod:/product-database-2 (0219). 0220 gated the view itself and, by revoking the matview it reads as the caller, refused everybody including administrators (0221).';

-- The state row is read through the view above, so it needs the same audience.
-- Its policy stays as it is for anyone reading the table directly.
do $$ begin
  create policy pdv2_state_read_all on public.product_database_v2_state for select
    using (auth.role() = 'authenticated');
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------------------
-- 0222_status_is_computed_when_read.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A STATUS THAT DEPENDS ON TODAY MUST NOT BE STORED AS OF LAST TUESDAY.
--
--   The user, 2026-09-20: "Should I Re-build it everytime?"
--
-- The honest answer is no -- only when one of the five registers changes. But
-- answering it exposed a defect in 0220: `item_status`, `item_status_reason`,
-- `warranty_state` and `contract_state` are all derived from `current_date`,
-- and 0220 MATERIALISED them. A materialised view evaluates its expressions AT
-- REFRESH TIME and stores the answer, so the cover status of every machine was
-- frozen at whenever somebody last pressed Rebuild.
--
-- A machine whose warranty lapsed the next morning would have gone on reading
-- WGP indefinitely -- with a "Built <time>" caption beside it that looks like
-- it accounts for exactly this and does not. MEASURED on the loaded fixture:
-- 209 machines of 10,000 carry the wrong status after thirty days without a
-- rebuild, about 2% a month. Against the live install base of 19,229 that is
-- roughly 400 machines a month quietly reading the wrong cover.
--
-- IT WOULD ALSO HAVE MADE THE ANSWER TO THE QUESTION WRONG. "Rebuild when a
-- register changes" is right for the assembly and useless for the clock: cover
-- lapses on its own, with nothing uploaded and nothing to notice. The answer is
-- not "rebuild daily" -- it is to stop storing the part that moves.
--
-- SO THE TWO HALVES ARE SPLIT ALONG THE LINE THAT ACTUALLY DIVIDES THEM:
--
--   STORED, because it is expensive and only changes when a register does:
--     which machines exist, whose they are, the warranty and contract dates,
--     the periods, the numbers, and which register said so. That is the part
--     that measured 2,936 ms a page to derive.
--
--   COMPUTED ON EVERY READ, because it depends on the date and on nothing
--     else: the four columns above. They are CASE expressions over columns
--     already on the row -- no joins, no registers -- so the screen keeps the
--     speed and stops being wrong the morning after it was built.
--
-- THE PUBLISHED COLUMNS ARE UNCHANGED in name, order and meaning, so nothing
-- reading this view has to know anything happened.
--
-- AND THEY ARE REMOVED FROM THE MATVIEW RATHER THAN LEFT THERE STALE. A frozen
-- `item_status` sitting in `product_database_v2_mv` for whoever queries it
-- directly is the trap this project keeps writing down: a value that is wrong
-- is worse than one that is absent, because nothing about it reads as an error.
-- ===========================================================================

drop view if exists public.product_database_v2 cascade;
drop materialized view if exists public.product_database_v2_mv cascade;

create materialized view public.product_database_v2_mv as

with w as (
  -- THE WARRANTY SALE — the machine's birth record. Latest by the cover it
  -- grants, so a re-sale or a corrected row wins over the one it replaced.
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, sa_number,
         warranty_start, warranty_end, warranty_years, warranty_months,
         sale_entry_date, invoice_date, state, city, engineer
    from public.warranty_sale_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, warranty_end desc nulls last, id desc
), c as (
  -- THE CONTRACT — latest by the cover it grants, so a renewal wins over the
  -- contract it succeeded (0187/FRS-056: the successor starts the day after).
  select distinct on (public.machine_key(product_name, serial_number))
         public.machine_key(product_name, serial_number) as mkey,
         id, product_name, product_code, serial_number, party_name, mc_number,
         contract_type, contract_start, contract_end, contract_years,
         contract_months, contract_entry_date
    from public.contract_details
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(product_name), '')  <> ''
   order by 1, contract_end desc nulls last, id desc
), a as (
  -- ADDITIONAL ENTRIES (0073) — the machines recovered by hand because neither
  -- register had them. Already one row per machine by its own unique index.
  select public.machine_key(item_name, serial_number) as mkey,
         id, item_name, serial_number, party_name,
         warranty_number, warranty_start, warranty_end,
         contract_number, contract_type, contract_start, contract_end, created_at
    from public.product_additional_entries
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
), o as (
  -- OWNERSHIP TRANSFER (0072) — the explicit, dated record that the machine
  -- changed hands. Latest transfer wins; a machine can move more than once.
  select distinct on (public.machine_key(item_name, serial_number))
         public.machine_key(item_name, serial_number) as mkey,
         id, to_party, from_party, transfer_date, reference_no
    from public.ownership_transfers
   where coalesce(btrim(serial_number), '') <> ''
     and coalesce(btrim(item_name), '')     <> ''
   order by 1, transfer_date desc nulls last, id desc
), inst as (
  -- THE INSTALLATION CALL — now read through `machine_install_start()`, a
  -- DEFINER function. See the header: this is both the speed and the
  -- correctness half of 0220.
  select mkey, ucn, answered_start, solved_on from public.machine_install_start()
), keys as (
  select mkey from w union select mkey from c union select mkey from a
), base as (
  select
    k.mkey,
    coalesce(w.product_name, c.product_name, a.item_name)        as product_name,
    coalesce(w.serial_number, c.serial_number, a.serial_number)  as serial_number,
    coalesce(w.product_code, c.product_code)                     as product_code,
    -- ---- the warranty, in the order the user gave -------------------------
    coalesce(i.answered_start, i.solved_on, a.warranty_start, w.warranty_start) as warranty_start,
    coalesce(w.warranty_months, (w.warranty_years * 12)::int)                   as warranty_months,
    a.warranty_end  as a_warranty_end,
    w.warranty_end  as w_warranty_end,
    case when i.answered_start is not null then 'Installation call ' || i.ucn
         when i.solved_on      is not null then 'Installation call ' || i.ucn || ' (solved date)'
         when a.warranty_start is not null then 'Additional entry'
         when w.warranty_start is not null then 'Warranty sale ' || coalesce(w.sa_number, '')
         else null end                                           as warranty_from,
    -- ---- the contract -----------------------------------------------------
    coalesce(c.contract_start, a.contract_start)                 as contract_start,
    coalesce(c.contract_months, (c.contract_years * 12)::int)    as contract_months,
    coalesce(c.contract_end, a.contract_end)                     as contract_end_stored,
    coalesce(c.contract_type, a.contract_type)                   as contract_type_raw,
    coalesce(c.mc_number, a.contract_number)                     as contract_number,
    case when c.id is not null then 'Contract ' || coalesce(c.mc_number, '')
         when a.contract_start is not null or a.contract_end is not null then 'Additional entry'
         else null end                                           as contract_from,
    -- ---- who owns it ------------------------------------------------------
    p.party_name, p.party_from,
    w.sa_number, w.state, w.city, w.engineer,
    o.from_party, o.to_party, o.transfer_date, o.reference_no,
    (w.mkey is not null) as in_warranty_register,
    (c.mkey is not null) as in_contract_register,
    (a.mkey is not null) as in_additional_entries,
    i.ucn as installation_ucn
  from keys k
  left join w on w.mkey = k.mkey
  left join c on c.mkey = k.mkey
  left join a on a.mkey = k.mkey
  left join o on o.mkey = k.mkey
  left join inst i on i.mkey = k.mkey
  -- WHOSE MACHINE IS IT: the LATEST DATED EVIDENCE wins, not a fixed order of
  -- registers. A machine sold in 2020, transferred in 2021 and then put under a
  -- new contract in 2024 belongs to whoever the 2024 contract names -- an
  -- ownership transfer is not permanently the last word, it is one dated claim
  -- among several. Ties break towards the record that exists SPECIFICALLY to
  -- say the machine changed hands.
  left join lateral (
    select v.party_name, v.party_from
      from (values
        (o.to_party,    'Ownership transfer ' || coalesce(o.reference_no, ''), o.transfer_date,           1),
        (a.party_name,  'Additional entry',                                    a.created_at::date,        2),
        (c.party_name,  'Contract ' || coalesce(c.mc_number, ''),              c.contract_start,          3),
        (w.party_name,  'Warranty sale ' || coalesce(w.sa_number, ''),
                        coalesce(w.sale_entry_date::date, w.invoice_date),                                4)
      ) as v(party_name, party_from, on_date, rank)
     where coalesce(btrim(v.party_name), '') <> ''
     order by v.on_date desc nulls last, v.rank
     limit 1
  ) p on true
)
select
  b.mkey                                   as machine_key,
  b.product_name,
  b.serial_number,
  b.product_code,
  b.party_name,
  b.party_from,
  -- ---- warranty ----------------------------------------------------------
  b.warranty_start,
  b.warranty_months,
  -- DERIVED where the start and the period are both known -- which is what the
  -- user asked for ("derive at the warranty end date") -- and the register's
  -- own end date otherwise, so a machine whose period nobody recorded still
  -- shows the cover it was sold.
  case when b.warranty_start is not null and b.warranty_months is not null
       then public.cover_period_end(b.warranty_start, b.warranty_months)
       else coalesce(b.a_warranty_end, b.w_warranty_end) end     as warranty_end,
  b.warranty_from,
  -- ---- contract ----------------------------------------------------------
  b.contract_number,
  b.contract_type_raw                                            as contract_type_as_recorded,
  public.contract_cover_code(b.contract_type_raw)                as contract_type,
  b.contract_start,
  b.contract_months,
  coalesce(b.contract_end_stored,
           public.cover_period_end(b.contract_start, b.contract_months)) as contract_end,
  b.contract_from,
  -- ---- where it came from, so the row can be checked ---------------------
  b.sa_number, b.state, b.city, b.engineer,
  b.from_party, b.to_party, b.transfer_date, b.reference_no,
  b.in_warranty_register, b.in_contract_register, b.in_additional_entries,
  b.installation_ucn
  from base b;

-- RE-ASSERTED, as it must be on every rebuild: without it the view reads as its
-- OWNER and row-level security stops applying to whoever is reading, with no
-- error and no warning (0040/0050/0057).;

-- CONCURRENTLY needs a unique index, and CONCURRENTLY is what keeps a rebuild
-- from blocking every reader of the screen. `machine_key` is the view's own
-- identity, so it is unique by construction.
;

create unique index if not exists product_database_v2_mv_key
  on public.product_database_v2_mv (machine_key);

-- Granted, because the view over it is `security_invoker` and so reads AS THE
-- CALLER. 0220 revoked this while leaving the view invoker and refused every
-- reader, administrators included (0221).
grant select on public.product_database_v2_mv to authenticated;

-- ---------------------------------------------------------------------------
-- THE FOUR LIVE COLUMNS, in the SAME positions this view has always published
-- them in. `current_date` is read HERE -- which is on every read, rather than
-- at the last rebuild.
-- ---------------------------------------------------------------------------
create view public.product_database_v2 as
select
  m.machine_key, m.product_name, m.serial_number, m.product_code,
  m.party_name, m.party_from,
  m.warranty_start, m.warranty_months, m.warranty_end, m.warranty_from,
  public.cover_state(m.warranty_end)                     as warranty_state,
  m.contract_number, m.contract_type_as_recorded, m.contract_type,
  m.contract_start, m.contract_months, m.contract_end, m.contract_from,
  public.cover_state(m.contract_end)                     as contract_state,
  -- WARRANTY FIRST -- the user's rule, and the opposite of `machine_cover`: a
  -- machine inside its warranty is not being billed under its contract.
  case
    when coalesce(m.warranty_end, '-infinity'::date) >= current_date then 'WGP'
    when coalesce(m.contract_end, '-infinity'::date) >= current_date
      -- A CONTRACT WITH NO TYPE IS NOT GUESSED AT (0208): `machine_cover` calls
      -- it CMC, which upgrades a labour contract to comprehensive on a blank
      -- cell. This says so instead, because that row needs fixing.
      then coalesce(public.contract_cover_code(m.contract_type_as_recorded),
                    'CONTRACT (TYPE NOT RECORDED)')
    else 'OGP'
  end                                                    as item_status,
  case
    when coalesce(m.warranty_end, '-infinity'::date) >= current_date
      then 'inside warranty — ' || coalesce(m.warranty_from, 'source not recorded')
    when coalesce(m.contract_end, '-infinity'::date) >= current_date
      then 'under contract — ' || coalesce(m.contract_from, 'source not recorded')
    else 'no warranty and no contract covers today'
  end                                                    as item_status_reason,
  m.sa_number, m.state, m.city, m.engineer,
  m.from_party, m.to_party, m.transfer_date, m.reference_no,
  m.in_warranty_register, m.in_contract_register, m.in_additional_entries,
  m.installation_ucn,
  s.refreshed_at
from public.product_database_v2_mv m
cross join public.product_database_v2_state s;
alter view public.product_database_v2 set (security_invoker = on);
grant select on public.product_database_v2 to authenticated;
comment on view public.product_database_v2 is
  'Product Database 2.0 — one row per machine. The ASSEMBLY is stored (refreshed_at says when); the cover STATUS is computed on every read, because it depends on today''s date and storing it froze it at the last rebuild (0222).';

-- The matview was just rebuilt from scratch, so date the storage honestly.
update public.product_database_v2_state
   set refreshed_at = now(),
       rows_built   = (select count(*) from public.product_database_v2_mv)
 where only_row;

-- ------------------------------------------------------------------------
-- 0223_product_database_2_keeps_itself_alive.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- "IT SHOULD BE ALIVE DATA" (the user, 2026-09-20), and a Rebuild button is
-- not alive — it is a chore that somebody has to remember, on a screen they
-- are about to make the primary product list for the whole application.
--
-- THE CONFLICT IS REAL AND THIS IS HOW IT IS RESOLVED. Deriving these machines
-- on demand measured 2,936 ms a page and timed out (0220); storing them
-- measured 3 ms and goes stale. So the storage stays, and what changes is WHO
-- NOTICES: the five registers now tell the storage when they have moved, and a
-- scheduled job acts on it. Nobody presses anything.
--
--   1. A STATEMENT-LEVEL trigger on each source sets `stale`. Statement-level,
--      not row-level, and that is the whole reason this is affordable: a bulk
--      upload of 12,000 warranty items is ONE statement, so it costs ONE flag
--      write, not 12,000 — a structural property of `for each statement`, not
--      an optimisation to be hoped for. Timed against a 12,000-row load it is
--      not distinguishable from noise, which is the point; a row-level trigger
--      here would have made every register upload slower than the problem it
--      was added to solve.
--   2. `refresh_product_database_2_if_stale()` rebuilds only when the flag is
--      set, CONCURRENTLY, so no reader is ever blocked.
--   3. pg_cron runs it every five minutes. Worst case the machines are five
--      minutes behind a register upload; typically far less, and the screen
--      SAYS which it is rather than leaving it to be guessed.
--
-- WHAT IS NOT DONE, DELIBERATELY: the refresh is not fired from the trigger
-- itself. That would rebuild once per statement of a bulk load — ten uploads
-- in a minute is ten full rebuilds, each of them wasted but the last — and a
-- `refresh materialized view` inside somebody's INSERT transaction makes their
-- upload wait on it. The flag separates "something changed" from "act on it",
-- which is the only reason this is cheap.
--
-- THE COVER STATUS IS ALREADY LIVE (0222) and is not what this file is about:
-- that half is computed on every read, so a warranty lapsing overnight is
-- visible immediately whether or not anything has been refreshed. This is
-- about the ASSEMBLY — a machine sold, transferred or put under contract.
-- ===========================================================================

alter table public.product_database_v2_state
  add column if not exists stale boolean not null default true;

comment on column public.product_database_v2_state.stale is
  'Set by the source registers when they change (0223); cleared by a refresh. The screen reads it to say whether it is showing live figures or figures waiting on the next rebuild.';

-- ---------------------------------------------------------------------------
-- "A REGISTER MOVED." Definer, because `product_database_v2_state` carries RLS
-- and has no UPDATE policy — deliberately, nobody should be writing it by
-- hand. Without definer every insert into a register would fail on the flag.
--
-- The conditional keeps a long bulk load off the row once it is already
-- flagged, so concurrent uploads do not queue on one row's lock.
-- ---------------------------------------------------------------------------
create or replace function public.pdv2_mark_stale()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.product_database_v2_state
     set stale = true
   where only_row and not stale;
  return null;   -- statement-level: there is no row to return
end $$;
comment on function public.pdv2_mark_stale() is
  'Marks Product Database 2.0 as needing a rebuild. STATEMENT-level, so a 12,000-row upload costs one write (0223).';

do $$
declare t text;
begin
  foreach t in array array[
    'sale_entries', 'sale_items',                 -- the warranty sale register
    'contract_entries', 'contract_items',         -- the contract register
    'product_additional_entries',                 -- the machines recovered by hand
    'ownership_transfers',                        -- who owns it now
    'installation_calls', 'feedback'              -- where a warranty actually starts
  ] loop
    if to_regclass('public.' || t) is not null then
      execute format('drop trigger if exists zz_pdv2_stale on public.%I', t);
      execute format(
        'create trigger zz_pdv2_stale after insert or update or delete on public.%I '
        'for each statement execute function public.pdv2_mark_stale()', t);
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- THE SCHEDULED REBUILD. Returns what it did, so the job's history says
-- whether it is working rather than only that it ran.
-- ---------------------------------------------------------------------------
create or replace function public.refresh_product_database_2_if_stale()
returns text language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if not exists (select 1 from public.product_database_v2_state where only_row and stale) then
    return 'up to date';
  end if;
  refresh materialized view concurrently public.product_database_v2_mv;
  select count(*) into n from public.product_database_v2_mv;
  update public.product_database_v2_state
     set refreshed_at = now(), rows_built = n, stale = false
   where only_row;
  return 'rebuilt ' || n || ' machines';
end $$;
comment on function public.refresh_product_database_2_if_stale() is
  'Rebuild Product Database 2.0 only if a register has changed since the last one. Run every five minutes by pg_cron (0223).';
revoke all on function public.refresh_product_database_2_if_stale() from public;
grant execute on function public.refresh_product_database_2_if_stale() to authenticated;

-- The manual rebuild clears the flag too, or the scheduler would do the same
-- work again five minutes later.
create or replace function public.refresh_product_database_2()
returns timestamptz language plpgsql security definer set search_path = public as $$
declare n integer;
begin
  if not (public.has_perm('masters.edit') or public.has_perm('cover.edit') or public.is_admin()) then
    raise exception 'Your role may not rebuild Product Database 2.0.' using errcode = '42501';
  end if;
  refresh materialized view concurrently public.product_database_v2_mv;
  select count(*) into n from public.product_database_v2_mv;
  update public.product_database_v2_state
     set refreshed_at = now(), rows_built = n, refreshed_by = auth.uid(), stale = false
   where only_row;
  return (select refreshed_at from public.product_database_v2_state where only_row);
end $$;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    if exists (select 1 from cron.job where jobname = 'refresh-product-database-2') then
      perform cron.unschedule('refresh-product-database-2');
    end if;
    perform cron.schedule('refresh-product-database-2', '*/5 * * * *',
                          'select public.refresh_product_database_2_if_stale();');
  end if;
end $$;

-- Built by this migration, so it starts clean rather than claiming to be stale.
update public.product_database_v2_state set stale = false where only_row;

-- ---------------------------------------------------------------------------
-- THE SCREEN HAS TO BE ABLE TO SAY WHICH IT IS. "Built 20-Sep 22:57" on its own
-- cannot tell somebody whether that is the current picture or one waiting on a
-- rebuild, and those read identically while meaning opposite things. APPENDED
-- at the end, which is the only place `create or replace view` accepts a new
-- column.
-- ---------------------------------------------------------------------------
create or replace view public.product_database_v2 as
select
  m.machine_key, m.product_name, m.serial_number, m.product_code,
  m.party_name, m.party_from,
  m.warranty_start, m.warranty_months, m.warranty_end, m.warranty_from,
  public.cover_state(m.warranty_end)                     as warranty_state,
  m.contract_number, m.contract_type_as_recorded, m.contract_type,
  m.contract_start, m.contract_months, m.contract_end, m.contract_from,
  public.cover_state(m.contract_end)                     as contract_state,
  case
    when coalesce(m.warranty_end, '-infinity'::date) >= current_date then 'WGP'
    when coalesce(m.contract_end, '-infinity'::date) >= current_date
      then coalesce(public.contract_cover_code(m.contract_type_as_recorded),
                    'CONTRACT (TYPE NOT RECORDED)')
    else 'OGP'
  end                                                    as item_status,
  case
    when coalesce(m.warranty_end, '-infinity'::date) >= current_date
      then 'inside warranty — ' || coalesce(m.warranty_from, 'source not recorded')
    when coalesce(m.contract_end, '-infinity'::date) >= current_date
      then 'under contract — ' || coalesce(m.contract_from, 'source not recorded')
    else 'no warranty and no contract covers today'
  end                                                    as item_status_reason,
  m.sa_number, m.state, m.city, m.engineer,
  m.from_party, m.to_party, m.transfer_date, m.reference_no,
  m.in_warranty_register, m.in_contract_register, m.in_additional_entries,
  m.installation_ucn,
  s.refreshed_at,
  s.stale
from public.product_database_v2_mv m
cross join public.product_database_v2_state s;
alter view public.product_database_v2 set (security_invoker = on);
grant select on public.product_database_v2 to authenticated;

commit;
