-- ===========================================================================
-- RITHI CRM — Reports: apply bundle
--
-- The visit history: the indexes behind its newest-first ordering, and the
-- two columns the bulk report -> call mapping needs --- `source_ref` (the
-- AppSheet reference a Drive link was derived from, kept so a wrong one can
-- be re-resolved) and `mapped_at` (this visit was recovered in bulk, not
-- reported live).
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0010_reports_ordering.sql
--   0071_report_source_ref.sql
--   0115_visit_date_sanity.sql
--   0224_solved_without_a_report.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0010_reports_ordering.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Reports ordering. `public.reports` has no `created_at` column — the visit
-- history is ordered by `visit_at` (newest visit first), with the identity
-- `id` as the tiebreaker for rows that share a date or have none. These
-- indexes back that sort so the register and the per-call/per-UCN lookups
-- stay fast. Run in the Supabase SQL Editor as postgres.
-- ===========================================================================

create index if not exists reports_visit_at_idx on public.reports (visit_at desc nulls last, id desc);
create index if not exists reports_call_number_idx on public.reports (call_number);

-- ------------------------------------------------------------------------
-- 0071_report_source_ref.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Bulk report → call mapping: keep what a link was DERIVED FROM.
--
-- Reports recovered from an AppSheet export arrive carrying AppSheet file
-- references, not Drive links — `Reports_Images/foo.png`, or a
-- gettablefileurl?... URL. The import turns those into Drive links and stores
-- them in `manual_report`, which is what the app opens.
--
-- `source_ref` keeps the ORIGINAL reference alongside it. Without that, a link
-- that resolved to the wrong file is unprovable and unfixable: you cannot tell
-- what it was meant to point at, and a re-run has nothing to re-resolve from.
-- For a quality record that is the difference between a recoverable mistake and
-- a permanent one, which is why it is a column and not a note in `data`.
--
-- `mapped_at` says the row came in through the bulk mapping rather than from an
-- engineer in the field — so a recovered visit is never mistaken for one
-- reported live.
-- ===========================================================================

alter table public.reports add column if not exists source_ref text not null default '';
alter table public.reports add column if not exists mapped_at  timestamptz;

comment on column public.reports.source_ref is
  'The original AppSheet file reference this row''s manual_report was derived from. Kept so a wrong link can be re-resolved.';
comment on column public.reports.mapped_at is
  'Set when the row was loaded by the bulk report → call mapping, not reported live.';

-- The mapping looks a call up by UCN and by call number; both already have
-- their index (0002, 0010). This one is for finding what the bulk run touched.
create index if not exists reports_mapped_at_idx on public.reports (mapped_at desc) where mapped_at is not null;

-- ---------------------------------------------------------------------------
-- Make `uid` usable as an UPSERT target.
--
-- 0002 created it as a PARTIAL unique index (`where uid is not null`).
-- Postgres will not infer a partial index from a bare `on conflict (uid)`, so
-- the bulk mapping's upsert failed outright with "there is no unique or
-- exclusion constraint matching the ON CONFLICT specification" — which is what
-- makes re-running a recovery sheet correct its rows instead of doubling the
-- visit history.
--
-- A FULL unique index is equivalent here and does infer: NULLs are distinct in
-- a unique index, so the rows with no uid (the sheet-era ones) still coexist
-- exactly as they did under the partial index.
-- ---------------------------------------------------------------------------
create unique index if not exists reports_uid_uniq on public.reports (uid);
drop index if exists public.reports_uid_key;

-- ------------------------------------------------------------------------
-- 0115_visit_date_sanity.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A VISIT CANNOT HAVE HAPPENED IN THE FUTURE, OR BEFORE THE COMPLAINT.
--
-- The user's two rules (2026-09-06), on the Visit Update form. Both are about a
-- visit that has not happened, rather than one recorded untidily:
--
--   1. NOT IN THE FUTURE. A call's status comes from its LATEST visit, so a
--      visit dated next week closes a call nobody has been to — and keeps it
--      closed until that day passes.
--   2. NOT BEFORE THE COMPLAINT. Nobody attended a fault that had not been
--      reported, and every response-time figure taken from the pair goes
--      negative.
--
-- The form enforces both. This is the same rule where it cannot be typed past:
-- `min`/`max` on a date input stop the PICKER, not a pasted value, and a visit
-- report is a quality record.
--
-- ---------------------------------------------------------------------------
-- WHAT IT DELIBERATELY DOES NOT JUDGE: HISTORY.
--
-- `reports` is also where the superseded system's visits live, and they must be
-- loadable exactly as they were — a file whose dates are imperfect is still the
-- record of what happened, and refusing it would leave the register with a gap
-- instead of an imperfection. That is the same exemption 0089 makes for
-- imported stock.
--
-- The signal is the row's own id, which each writer sets and none of them share:
--
--   WEB-…   the Visit Update form (saveReport)     -> CHECKED
--   IMP-…   Bulk Uploads, derived from call + date -> not checked
--   other   Bulk Report Mapping (carries source_ref), a restore, a migration
--                                                  -> not checked
--
-- So the rule governs what is ENTERED from today, and says nothing about what
-- was loaded. Widening it later is one line; it would want a look at the
-- existing data first, which is why it is not done here.
--
-- A call with NO complaint date is held to rule 1 only: there is nothing to
-- compare against, and refusing the visit would invent a requirement.
--
-- TIMEZONE, and why this is not `> now()`. The app writes the chosen calendar
-- day as UTC midnight (`2026-09-06T00:00:00Z`). Between midnight and 05:30 IST
-- that instant is still in the FUTURE relative to now(), so a plain `> now()`
-- would refuse a visit entered early in the morning and dated today. The
-- comparison is therefore between DAYS: the visit's own day (UTC, as written)
-- against today in India, which is where the business is.
-- ===========================================================================

create or replace function public.reports_visit_date_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_visit date; v_complaint date; v_today date;
begin
  if new.visit_at is null then return new; end if;

  -- Only what the Visit Update form writes. See the header.
  if coalesce(new.uid, '') !~ '^WEB-' then return new; end if;

  -- An UPDATE that leaves the date alone is not this trigger's business — a
  -- report corrected years later must not be blocked by a rule about when it
  -- was entered.
  if tg_op = 'UPDATE' and old.visit_at is not distinct from new.visit_at then
    return new;
  end if;

  v_visit := (new.visit_at at time zone 'UTC')::date;
  v_today := (now() at time zone 'Asia/Kolkata')::date;

  if v_visit > v_today then
    raise exception 'A visit cannot be dated in the future (% is after %)', v_visit, v_today
      using errcode = 'check_violation';
  end if;

  select c.complaint_date into v_complaint from public.calls c where c.ucn = new.ucn;
  if v_complaint is not null and v_visit < v_complaint then
    raise exception 'A visit cannot be dated before the complaint (% is before %)', v_visit, v_complaint
      using errcode = 'check_violation';
  end if;

  return new;
end $$;

drop trigger if exists reports_visit_date_guard on public.reports;
create trigger reports_visit_date_guard
  before insert or update on public.reports
  for each row execute function public.reports_visit_date_guard();

comment on function public.reports_visit_date_guard() is
  'A visit entered on the Visit Update form (uid WEB-...) cannot be dated in the future or before its call''s complaint date. Imported history is exempt by design — see the migration header.';

-- ------------------------------------------------------------------------
-- 0224_solved_without_a_report.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- SOLVED, BUT NOBODY FILED THE REPORT.
--
--   The user, 2026-09-20: "Create a Report - Call is Solved, but Report or
--   Visit Entry is missing - View only for Admins and Super Admins."
--
-- This is the list that says WHICH visits to re-upload, and it exists because
-- the answer was previously "load them all again and hope".
--
-- THE FOUR GAPS ARE NOT THE SAME GAP, and a report that lumps them together
-- cannot be acted on — each needs a different fix:
--
--   no visit at all ....... the call has NO `reports` row. Nothing recorded
--                           that anybody attended. The visit must be loaded.
--   no visit date ......... a visit row with no `visit_at`. It cannot be
--                           placed in time, so it cannot date the call.
--   entry date is an ....... `reports.updated_at` is NOT NULL and DEFAULTS TO
--   import stamp            `now()`, so a file with no Visit Entry Date does
--                           not leave a blank — it silently takes the MOMENT
--                           OF THE IMPORT. A missing entry date therefore
--                           cannot be found by looking for a null, which is
--                           why this report looks for the signature instead:
--                           the number of visits sharing that timestamp TO THE
--                           MICROSECOND. Twenty-five visits genuinely entered
--                           at the same instant is not a thing that happens;
--                           a batch load is. The COUNT is published either way
--                           (`visits_sharing_entry_stamp`), so the reader sees
--                           the evidence and not only the verdict.
--                           It matters because that column decides a call's
--                           status — 0032 takes the LATEST ENTRY — so a whole
--                           batch sharing one stamp lets an arbitrary row
--                           decide every call in it.
--   no service report ..... no `manual_report`. The visit is recorded, the
--                           document behind it is not.
--
-- A call can be missing more than one, so `missing` lists every one of them
-- rather than the first — being told about a gap, fixing it, and being told
-- about the next one is three round trips for one row.
--
-- "SOLVED" INCLUDES "SOLVED - REPORT PENDING", AND THE ROW SAYS WHICH. They
-- are different findings: Report Pending is the system stating a known
-- absence, and a plain Solved with no report is the system contradicting
-- itself. Filtering to one of them would hide half the problem; merging them
-- without saying which would misrepresent it. `open_state` is carried through.
--
-- IT IS A `security_invoker` VIEW over `calls` and `reports`, so the call
-- policies decide the rows exactly as they do everywhere else. The SCREEN is
-- what is restricted to administrators (`mod:/missing-visit-reports`, below);
-- the view does not invent a second, different rule, which is how a screen and
-- its data come to disagree.
-- ===========================================================================
-- Dropped first: `create or replace view` can only APPEND a column, and this
-- definition inserts one in the middle. The view is new here, so nothing
-- depends on it and the drop is idempotent.
drop view if exists public.solved_without_report;
create view public.solved_without_report as
with latest as (
  -- THE LATEST ENTRY, not the latest visit date — the same ordering
  -- `sync_call_last_visit()` uses (0032), because this report is about what
  -- that function had to work with.
  select distinct on (r.ucn)
         r.ucn, r.visit_at, r.updated_at, r.manual_report, r.uid, r.engineer,
         count(*) over (partition by r.updated_at) as sharing
    from public.reports r
   order by r.ucn, r.updated_at desc nulls last, r.id desc
)
select
  c.ucn,
  c.call_number,
  c.reg_date,
  c.open_state,
  c.party_name,
  c.product_name,
  c.serial,
  c.state,
  c.last_visit_at,
  l.uid            as visit_uid,
  l.visit_at       as visit_date,
  l.updated_at     as visit_entry_date,
  l.sharing        as visits_sharing_entry_stamp,
  nullif(btrim(coalesce(l.manual_report, '')), '') as service_report,
  coalesce(nullif(btrim(coalesce(l.engineer, '')), ''), '') as visit_engineer,
  -- EVERY gap on the row, in the order they have to be fixed in.
  array_to_string(
    array_remove(array[
      case when l.ucn is null                                        then 'no visit at all' end,
      case when l.ucn is not null and l.visit_at is null             then 'no visit date' end,
      case when l.ucn is not null and l.sharing >= 25
             then 'entry date looks like an import stamp (' || l.sharing || ' visits share it)' end,
      case when l.ucn is not null
            and coalesce(btrim(l.manual_report), '') = ''            then 'no service report' end
    ], null), ' · ')                                                 as missing
from public.calls c
left join latest l on l.ucn = c.ucn
where coalesce(c.open_state, '') like 'Solved%'
  and (l.ucn is null
       or l.visit_at is null
       or l.sharing >= 25
       or coalesce(btrim(l.manual_report), '') = '');
alter view public.solved_without_report set (security_invoker = on);
grant select on public.solved_without_report to authenticated;
comment on view public.solved_without_report is
  'Calls reading Solved whose visit record is incomplete — no visit at all, no visit date, no visit entry date, or no service report. `missing` names every gap on the row. Administrators only, by the module key rather than by a rule of its own (0224).';

-- ---------------------------------------------------------------------------
-- THE KEY REACHES NOBODY WITHOUT THIS. `permsForRole()` is
-- `if (stored && stored.length) return stored;` — the code defaults apply ONLY
-- to a role whose stored set is EMPTY, and on a project in use every role has
-- a tuned row. So a new screen's key must be MERGED into `app_roles` or the
-- page is invisible to everybody with no error anywhere. 0195 and 0209 are the
-- pattern; this is the same shape.
--
-- ADMINISTRATORS ONLY: the three roles that see every module. MERGED, never
-- overwritten, and a role with ZERO permissions is left alone — an empty array
-- means "not configured" and writing one key into it turns the fallback off.
-- ---------------------------------------------------------------------------
do $$
declare n integer;
begin
  if to_regclass('public.app_roles') is null then return; end if;

  update public.app_roles ar
     set permissions = (
           select coalesce(jsonb_agg(distinct v), '[]'::jsonb)
             from (
               select jsonb_array_elements_text(ar.permissions) as v
               union
               select unnest(array['mod:/missing-visit-reports']) as v
             ) u
         ),
         updated_at = now()
   where jsonb_array_length(ar.permissions) > 0
     and ar.role in ('admin', 'technical_support', 'zoho_migration')
     and not (ar.permissions ? 'mod:/missing-visit-reports');
  get diagnostics n = row_count;
  raise notice '0224: % of 3 role(s) given mod:/missing-visit-reports', n;
end $$;

commit;
