-- ===========================================================================
-- RITHI CRM — Spare Requests: apply bundle
--
-- The spare-request workflow end to end: the approval chain (RM → Commercial
-- → NSM → Stores), the engineer receipt that closes it, the OR/RowNo
-- numbering (OR-YY/MM/NNN, restarting each month), and per-SPARE approvals —
-- the RM decides each line on its own, so one OR can go forward partly approved.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0006_spare_workflow.sql
--   0009_spare_receipt.sql
--   0011_spare_intake.sql
--   0012_spare_auto_approval.sql
--   0016_spare_line_approvals.sql
--   0017_spare_or_number_monthly.sql
--   0018_spare_or_number_padded.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.spare_requests') is null then
    missing := array_append(missing, 'the spare_requests table — 0001_init.sql');
  end if;
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.is_admin()') is null then
    missing := array_append(missing, 'is_admin() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.can_approve_spares()') is null then
    missing := array_append(missing, 'can_approve_spares() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0006_spare_workflow.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Spare approval workflow on spare_requests:
--   RM → Commercial → NSM → Stores(dispatch/DC).
-- Commercial & NSM auto-approve unless the item is AMC or OGP (item_status).
-- ===========================================================================

alter table public.spare_requests
  add column if not exists rm_approval        text default 'Pending',
  add column if not exists rm_by              text,
  add column if not exists rm_at              timestamptz,
  add column if not exists commercial_approval text default 'Pending',
  add column if not exists commercial_by      text,
  add column if not exists commercial_at      timestamptz,
  add column if not exists nsm_approval        text default 'Pending',
  add column if not exists nsm_by             text,
  add column if not exists nsm_at             timestamptz,
  add column if not exists stores_status       text default 'Pending',
  add column if not exists dc_number          text,
  add column if not exists dispatched_by      text,
  add column if not exists dispatched_at      timestamptz,
  add column if not exists stage              text default 'RM Approval';

-- Approvers update spare_requests (buttons are RBAC-gated in the app).
drop policy if exists sr_update on public.spare_requests;
create policy sr_update on public.spare_requests for update
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ------------------------------------------------------------------------
-- 0009_spare_receipt.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Spare request module — phase 3.
--   • Reject reasons captured at every approval stage.
--   • Dispatch details (courier / remarks) alongside the DC number.
--   • Engineer acknowledgement, closing the loop: Dispatched → Received.
--
-- Runs after 0008_rbac_enforcement.sql and extends the RBAC it installed:
-- the new receipt columns get their own stage in the guard, and the raiser
-- (who holds none of the approval permissions) is allowed to write them.
-- ===========================================================================

alter table public.spare_requests
  add column if not exists reject_reason     text,
  add column if not exists rejected_stage    text,
  add column if not exists courier           text,
  add column if not exists dispatch_remarks  text,
  add column if not exists received_by       text,
  add column if not exists received_at       timestamptz,
  add column if not exists receipt_remarks   text;

-- The register filters and sorts by workflow stage, so index it.
create index if not exists spare_requests_stage_idx      on public.spare_requests (stage);
create index if not exists spare_requests_created_at_idx on public.spare_requests (created_at desc);

-- ---------------------------------------------------------------------------
-- created_by was never populated: the app inserts spare_requests without it
-- and the column has no default, so it is NULL on every row. 0008's policies
-- test `created_by = auth.uid()`, which therefore never matches — that blocks
-- srl_insert (a non-admin raising a request could not write its lines) as well
-- as the acknowledgement added here. Defaulting it fixes both for new rows.
-- ---------------------------------------------------------------------------
alter table public.spare_requests alter column created_by set default auth.uid();

-- The raiser must be able to update their own request to acknowledge receipt,
-- and they hold none of the approval permissions. Identify them the same way
-- sr_read already does: by created_by, or by the engineer_email on the row.
create or replace function public.is_spare_requester(r public.spare_requests)
returns boolean language sql stable as $$
  select r.created_by = auth.uid()
      or (nullif(trim(r.engineer_email), '') is not null
          and lower(trim(r.engineer_email)) = lower(auth.email()));
$$;
grant execute on function public.is_spare_requester(public.spare_requests) to authenticated;

drop policy if exists sr_update on public.spare_requests;
create policy sr_update on public.spare_requests for update
  using (public.can_approve_spares() or public.is_spare_requester(spare_requests))
  with check (public.can_approve_spares() or public.is_spare_requester(spare_requests));

-- ---------------------------------------------------------------------------
-- Stage guard, extended. Keeps 0008's per-stage column rules and adds:
--   • the receipt columns, which need spare.receive AND being the raiser;
--   • courier / dispatch_remarks, which belong to the dispatch stage;
--   • reject_reason / rejected_stage, which only an approver may write;
--   • the Received stage transition, which the raiser may make.
-- ---------------------------------------------------------------------------
create or replace function public.spare_requests_stage_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  changed boolean;
begin
  if public.is_admin() then return new; end if;

  changed := new.rm_approval is distinct from old.rm_approval
          or new.rm_by       is distinct from old.rm_by
          or new.rm_at       is distinct from old.rm_at;
  if changed and not public.has_perm('spare.approve_rm') then
    raise exception 'RBAC: RM approval requires the spare.approve_rm permission';
  end if;

  changed := new.commercial_approval is distinct from old.commercial_approval
          or new.commercial_by       is distinct from old.commercial_by
          or new.commercial_at       is distinct from old.commercial_at;
  if changed and not public.has_perm('spare.approve_commercial') then
    raise exception 'RBAC: Commercial approval requires the spare.approve_commercial permission';
  end if;

  changed := new.nsm_approval is distinct from old.nsm_approval
          or new.nsm_by       is distinct from old.nsm_by
          or new.nsm_at       is distinct from old.nsm_at;
  if changed and not public.has_perm('spare.approve_nsm') then
    raise exception 'RBAC: NSM approval requires the spare.approve_nsm permission';
  end if;

  changed := new.stores_status    is distinct from old.stores_status
          or new.dc_number        is distinct from old.dc_number
          or new.dispatched_by    is distinct from old.dispatched_by
          or new.dispatched_at    is distinct from old.dispatched_at
          or new.courier          is distinct from old.courier
          or new.dispatch_remarks is distinct from old.dispatch_remarks;
  if changed and not public.has_perm('spare.dispatch') then
    raise exception 'RBAC: dispatch / DC requires the spare.dispatch permission';
  end if;

  -- A rejection reason is only meaningful from whoever rejected the request.
  changed := new.reject_reason  is distinct from old.reject_reason
          or new.rejected_stage is distinct from old.rejected_stage;
  if changed and not public.can_approve_spares() then
    raise exception 'RBAC: recording a rejection requires an approval permission';
  end if;

  -- Receipt: the engineer who raised the request acknowledges the parts.
  changed := new.received_by     is distinct from old.received_by
          or new.received_at     is distinct from old.received_at
          or new.receipt_remarks is distinct from old.receipt_remarks;
  if changed then
    if not public.has_perm('spare.receive') then
      raise exception 'RBAC: acknowledging receipt requires the spare.receive permission';
    end if;
    if not public.is_spare_requester(old) then
      raise exception 'RBAC: only the engineer who raised the request may acknowledge it';
    end if;
    if old.stores_status is null or old.stores_status !~* 'dispatch' then
      raise exception 'RBAC: a request can only be acknowledged after it is dispatched';
    end if;
  end if;

  -- The workflow stage moves as a side effect of an approval, or of the
  -- raiser acknowledging receipt.
  if new.stage is distinct from old.stage
     and not public.can_approve_spares()
     and not (new.stage = 'Received' and public.has_perm('spare.receive') and public.is_spare_requester(old)) then
    raise exception 'RBAC: advancing the approval stage requires an approval permission';
  end if;

  return new;
end $$;

drop trigger if exists spare_requests_stage_guard on public.spare_requests;
create trigger spare_requests_stage_guard
  before update on public.spare_requests
  for each row execute function public.spare_requests_stage_guard();

-- ---------------------------------------------------------------------------
-- has_perm() reads app_roles, and 0008's seed deliberately leaves an existing
-- role's permissions alone — so spare.receive, which did not exist then, is on
-- no role. Append it to the roles that raise or handle requests, without
-- disturbing any other permission an admin has since edited.
-- ---------------------------------------------------------------------------
update public.app_roles
   set permissions = coalesce(permissions, '[]'::jsonb) || '["spare.receive"]'::jsonb,
       updated_at  = now()
 where role in ('admin', 'engineer', 'rm', 'rgm', 'spare_coordinator')
   and not coalesce(permissions, '[]'::jsonb) ? 'spare.receive';

-- ------------------------------------------------------------------------
-- 0011_spare_intake.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Spare request intake — the register's own numbering and dates.
--   • OR NO: a running number per request, starting at OR47042.
--   • RowNo: the part's position within its request, restarting at 1 per OR.
--   • OR Req Date: today's date; TimeStamp is the existing created_at.
--   • Qty is at least 1, and a request carries at most 20 parts.
-- ===========================================================================

alter table public.spare_requests
  add column if not exists or_no       text,
  add column if not exists or_req_date date;

alter table public.spare_request_lines
  add column if not exists row_no int;

create unique index if not exists spare_requests_or_no_idx on public.spare_requests (or_no);
create index if not exists spare_request_lines_request_uid_idx on public.spare_request_lines (request_uid);

-- ---------------------------------------------------------------------------
-- OR numbers continue the sheet's series, which had reached OR47042.
-- ---------------------------------------------------------------------------
create sequence if not exists public.spare_or_no_seq as bigint start with 47042 minvalue 47042;

-- If rows were already imported, start the sequence past the highest OR number
-- present so a re-run never hands out one that is taken.
do $$
declare hi bigint;
begin
  select max((regexp_replace(or_no, '\D', '', 'g'))::bigint) into hi
    from public.spare_requests where or_no ~ '^OR\d+$';
  if hi is not null and hi >= 47042 then
    perform setval('public.spare_or_no_seq', hi + 1, false);
  end if;
end $$;

create or replace function public.spare_requests_assign_or_no()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.or_no is null or trim(new.or_no) = '' then
    new.or_no := 'OR' || nextval('public.spare_or_no_seq');
  end if;
  if new.or_req_date is null then
    new.or_req_date := current_date;
  end if;
  return new;
end $$;

drop trigger if exists spare_requests_assign_or_no on public.spare_requests;
create trigger spare_requests_assign_or_no
  before insert on public.spare_requests
  for each row execute function public.spare_requests_assign_or_no();

-- The OR number and its date identify the request downstream (DC, stores,
-- Tally), so they are assigned once and then fixed.
create or replace function public.spare_requests_number_immutable()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_admin() then return new; end if;
  if new.or_no is distinct from old.or_no then
    raise exception 'The OR number is assigned once and cannot be changed';
  end if;
  if new.or_req_date is distinct from old.or_req_date then
    raise exception 'The OR request date is assigned once and cannot be changed';
  end if;
  return new;
end $$;

drop trigger if exists spare_requests_number_immutable on public.spare_requests;
create trigger spare_requests_number_immutable
  before update on public.spare_requests
  for each row execute function public.spare_requests_number_immutable();

-- ---------------------------------------------------------------------------
-- RowNo restarts at 1 for each OR, and a request carries at most 20 parts.
-- ---------------------------------------------------------------------------
create or replace function public.spare_request_lines_assign_row_no()
returns trigger language plpgsql security definer set search_path = public as $$
declare next_no int;
begin
  if coalesce(new.qty, 0) < 1 then
    raise exception 'Quantity must be at least 1';
  end if;
  if new.row_no is null then
    select coalesce(max(row_no), 0) + 1 into next_no
      from public.spare_request_lines where request_uid = new.request_uid;
    new.row_no := next_no;
  end if;
  if new.row_no > 20 then
    raise exception 'A spare request may carry at most 20 parts';
  end if;
  return new;
end $$;

drop trigger if exists spare_request_lines_assign_row_no on public.spare_request_lines;
create trigger spare_request_lines_assign_row_no
  before insert on public.spare_request_lines
  for each row execute function public.spare_request_lines_assign_row_no();

-- Backfill anything already loaded, so old rows sort alongside new ones.
update public.spare_requests
   set or_req_date = created_at::date
 where or_req_date is null;

with numbered as (
  select id, row_number() over (partition by request_uid order by id) as rn
    from public.spare_request_lines where row_no is null
)
update public.spare_request_lines l
   set row_no = numbered.rn
  from numbered where numbered.id = l.id;

-- ---------------------------------------------------------------------------
-- A request is its parts: if the lines fail to insert, the client deletes the
-- header it just created rather than leaving a partial record (and a burnt OR
-- number) behind. No DELETE policy existed, so that cleanup silently did
-- nothing. Allow it only while the approval chain has not touched the request.
-- ---------------------------------------------------------------------------
drop policy if exists sr_delete on public.spare_requests;
create policy sr_delete on public.spare_requests for delete
  using (
    (public.is_admin() or public.is_spare_requester(spare_requests))
    and coalesce(stage, 'RM Approval') = 'RM Approval'
    and coalesce(rm_approval, 'Pending') = 'Pending'
    and received_at is null
  );

-- ------------------------------------------------------------------------
-- 0012_spare_auto_approval.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Fix: the RM's approval of a non-AMC/OGP item is refused by the stage guard.
--
-- The business rule is that Commercial and NSM only review AMC or OGP items;
-- for anything else they auto-approve. The app implements that by writing
-- commercial_approval / nsm_approval = 'Auto-Approved' in the SAME update that
-- records the RM's approval (src/lib/spareflow.ts, buildPatch).
--
-- 0008_rbac_enforcement.sql's guard sees those columns change and demands
-- spare.approve_commercial / spare.approve_nsm, which an RM does not hold — so
-- the whole update is rejected and the common path cannot be approved at all.
--
-- The guard is reissued here allowing exactly that case: the auto-approval
-- literal, written by someone who may approve at the RM stage, on an item that
-- is not AMC or OGP. A manual 'Approved' still needs the stage's own action.
-- ===========================================================================

create or replace function public.spare_needs_review(item_status text)
returns boolean language sql immutable as $$
  select coalesce(trim(item_status), '') ~* '^(amc|ogp)$';
$$;
grant execute on function public.spare_needs_review(text) to authenticated;

create or replace function public.spare_requests_stage_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  changed   boolean;
  auto_ok   boolean;
begin
  if public.is_admin() then return new; end if;

  -- Commercial and NSM auto-approve alongside the RM's approval when the item
  -- needs no review. Anyone who may approve at the RM stage may write that.
  auto_ok := not public.spare_needs_review(new.item_status)
             and public.has_perm('spare.approve_rm');

  changed := new.rm_approval is distinct from old.rm_approval
          or new.rm_by       is distinct from old.rm_by
          or new.rm_at       is distinct from old.rm_at;
  if changed and not public.has_perm('spare.approve_rm') then
    raise exception 'RBAC: RM approval requires the spare.approve_rm permission';
  end if;

  changed := new.commercial_approval is distinct from old.commercial_approval
          or new.commercial_by       is distinct from old.commercial_by
          or new.commercial_at       is distinct from old.commercial_at;
  if changed
     and not public.has_perm('spare.approve_commercial')
     and not (auto_ok and new.commercial_approval = 'Auto-Approved'
              and new.commercial_by is not distinct from old.commercial_by
              and new.commercial_at is not distinct from old.commercial_at) then
    raise exception 'RBAC: Commercial approval requires the spare.approve_commercial permission';
  end if;

  changed := new.nsm_approval is distinct from old.nsm_approval
          or new.nsm_by       is distinct from old.nsm_by
          or new.nsm_at       is distinct from old.nsm_at;
  if changed
     and not public.has_perm('spare.approve_nsm')
     and not (auto_ok and new.nsm_approval = 'Auto-Approved'
              and new.nsm_by is not distinct from old.nsm_by
              and new.nsm_at is not distinct from old.nsm_at) then
    raise exception 'RBAC: NSM approval requires the spare.approve_nsm permission';
  end if;

  changed := new.stores_status    is distinct from old.stores_status
          or new.dc_number        is distinct from old.dc_number
          or new.dispatched_by    is distinct from old.dispatched_by
          or new.dispatched_at    is distinct from old.dispatched_at
          or new.courier          is distinct from old.courier
          or new.dispatch_remarks is distinct from old.dispatch_remarks;
  if changed and not public.has_perm('spare.dispatch') then
    raise exception 'RBAC: dispatch / DC requires the spare.dispatch permission';
  end if;

  changed := new.reject_reason  is distinct from old.reject_reason
          or new.rejected_stage is distinct from old.rejected_stage;
  if changed and not public.can_approve_spares() then
    raise exception 'RBAC: recording a rejection requires an approval permission';
  end if;

  changed := new.received_by     is distinct from old.received_by
          or new.received_at     is distinct from old.received_at
          or new.receipt_remarks is distinct from old.receipt_remarks;
  if changed then
    if not public.has_perm('spare.receive') then
      raise exception 'RBAC: acknowledging receipt requires the spare.receive permission';
    end if;
    if not public.is_spare_requester(old) then
      raise exception 'RBAC: only the engineer who raised the request may acknowledge it';
    end if;
    if old.stores_status is null or old.stores_status !~* 'dispatch' then
      raise exception 'RBAC: a request can only be acknowledged after it is dispatched';
    end if;
  end if;

  if new.stage is distinct from old.stage
     and not public.can_approve_spares()
     and not (new.stage = 'Received' and public.has_perm('spare.receive') and public.is_spare_requester(old)) then
    raise exception 'RBAC: advancing the approval stage requires an approval permission';
  end if;

  return new;
end $$;

-- ------------------------------------------------------------------------
-- 0016_spare_line_approvals.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Spare approvals move from the REQUEST to the LINE.
--
-- The RM must decide each spare individually — a request for five parts may
-- warrant three of them — so the approval state belongs on spare_request_lines,
-- not on the request header. The later stages (Commercial, NSM, Stores,
-- receipt) also live on the line, which is what lets them be actioned either
-- per spare or, by updating every open line of a request at once, per OR.
--
-- The request header keeps stage/status as a ROLL-UP of its lines, maintained
-- by trigger, so existing reads and filters stay meaningful. Nothing writes
-- those columns directly any more.
-- ===========================================================================

alter table public.spare_request_lines
  add column if not exists rm_by               text,
  add column if not exists rm_at               timestamptz,
  add column if not exists commercial_approval text default 'Pending',
  add column if not exists commercial_by       text,
  add column if not exists commercial_at       timestamptz,
  add column if not exists nsm_approval        text default 'Pending',
  add column if not exists nsm_by              text,
  add column if not exists nsm_at              timestamptz,
  add column if not exists dc_number           text,
  add column if not exists courier             text,
  add column if not exists dispatch_remarks    text,
  add column if not exists dispatched_by       text,
  add column if not exists dispatched_at       timestamptz,
  add column if not exists received_by         text,
  add column if not exists received_at         timestamptz,
  add column if not exists receipt_remarks     text,
  add column if not exists reject_reason       text,
  add column if not exists rejected_stage      text,
  add column if not exists stage               text default 'RM Approval';

-- Everything below writes data. The RBAC guard installed at the end of this
-- migration is dropped first: these are data migrations, not somebody
-- approving spares, and they must not be judged against whoever is running
-- them. In the Supabase SQL Editor auth.uid() is NULL, so is_admin() is false
-- and every stage check would refuse. Recreating the guard at the end also
-- makes this migration safe to re-run.
drop trigger if exists spare_request_lines_guard on public.spare_request_lines;

-- rm_approval / stores_status / status already exist on the line (0001) but
-- were never used; normalise them (and the column defaults) to the header's
-- vocabulary, so new lines need no normalising on a later re-run.
alter table public.spare_request_lines alter column rm_approval   set default 'Pending';
alter table public.spare_request_lines alter column stores_status set default 'Pending';
update public.spare_request_lines set rm_approval   = 'Pending' where coalesce(rm_approval, '') = '';
update public.spare_request_lines set stores_status = 'Pending' where coalesce(stores_status, '') = '';

-- ---------------------------------------------------------------------------
-- Carry each existing request's decisions down onto its lines, so requests
-- already part-way through the chain keep their state.
-- ---------------------------------------------------------------------------
update public.spare_request_lines l
   set rm_approval         = coalesce(nullif(r.rm_approval, ''), l.rm_approval),
       rm_by               = coalesce(l.rm_by, r.rm_by),
       rm_at               = coalesce(l.rm_at, r.rm_at),
       commercial_approval = coalesce(nullif(r.commercial_approval, ''), l.commercial_approval),
       commercial_by       = coalesce(l.commercial_by, r.commercial_by),
       commercial_at       = coalesce(l.commercial_at, r.commercial_at),
       nsm_approval        = coalesce(nullif(r.nsm_approval, ''), l.nsm_approval),
       nsm_by              = coalesce(l.nsm_by, r.nsm_by),
       nsm_at              = coalesce(l.nsm_at, r.nsm_at),
       stores_status       = coalesce(nullif(r.stores_status, ''), l.stores_status),
       dc_number           = coalesce(l.dc_number, r.dc_number),
       courier             = coalesce(l.courier, r.courier),
       dispatch_remarks    = coalesce(l.dispatch_remarks, r.dispatch_remarks),
       dispatched_by       = coalesce(l.dispatched_by, r.dispatched_by),
       dispatched_at       = coalesce(l.dispatched_at, r.dispatched_at),
       received_by         = coalesce(l.received_by, r.received_by),
       received_at         = coalesce(l.received_at, r.received_at),
       receipt_remarks     = coalesce(l.receipt_remarks, r.receipt_remarks),
       reject_reason       = coalesce(l.reject_reason, r.reject_reason),
       rejected_stage      = coalesce(l.rejected_stage, r.rejected_stage),
       stage               = coalesce(nullif(r.stage, ''), l.stage)
  from public.spare_requests r
 where r.uid = l.request_uid
   and l.rm_at is null;   -- only lines never decided on their own

-- ---------------------------------------------------------------------------
-- One line's stage — the same rule the app applies (src/lib/spareflow.ts).
-- ---------------------------------------------------------------------------
create or replace function public.spare_line_stage(
  rm text, commercial text, nsm text, stores text, received timestamptz, item_status text
) returns text language sql immutable as $$
  select case
    when rm ~* 'reject' or commercial ~* 'reject' or nsm ~* 'reject' then 'Rejected'
    when received is not null                                        then 'Received'
    when stores ~* 'dispatch'                                        then 'Dispatched'
    when rm !~* 'approv|auto'                                        then 'RM Approval'
    when public.spare_needs_review(item_status)
     and commercial !~* 'approv|auto'                                then 'Commercial'
    when public.spare_needs_review(item_status)
     and nsm !~* 'approv|auto'                                       then 'NSM'
    else 'Stores'
  end;
$$;
grant execute on function public.spare_line_stage(text, text, text, text, timestamptz, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Keep each line's own stage column current.
-- ---------------------------------------------------------------------------
create or replace function public.spare_request_lines_set_stage()
returns trigger language plpgsql security definer set search_path = public as $$
declare item text;
begin
  select r.item_status into item from public.spare_requests r where r.uid = new.request_uid;
  new.stage := public.spare_line_stage(
    coalesce(new.rm_approval, 'Pending'), coalesce(new.commercial_approval, 'Pending'),
    coalesce(new.nsm_approval, 'Pending'), coalesce(new.stores_status, 'Pending'),
    new.received_at, item);
  new.status := new.stage;
  return new;
end $$;

drop trigger if exists spare_request_lines_set_stage on public.spare_request_lines;
create trigger spare_request_lines_set_stage
  before insert or update on public.spare_request_lines
  for each row execute function public.spare_request_lines_set_stage();

-- ---------------------------------------------------------------------------
-- Roll the lines up onto the request: the least-advanced stage among the lines
-- still alive, or Rejected when every line was rejected.
-- ---------------------------------------------------------------------------
create or replace function public.spare_request_rollup(p_uid text)
returns void language plpgsql security definer set search_path = public as $$
declare roll text;
begin
  select case
           when count(*) = 0                              then 'RM Approval'
           when count(*) filter (where stage <> 'Rejected') = 0 then 'Rejected'
           else min(case stage
                      when 'RM Approval' then 1 when 'Commercial' then 2
                      when 'NSM'         then 3 when 'Stores'     then 4
                      when 'Dispatched'  then 5 when 'Received'   then 6
                    end) filter (where stage <> 'Rejected')::text
         end
    into roll
    from public.spare_request_lines where request_uid = p_uid;

  roll := coalesce(case roll
            when '1' then 'RM Approval' when '2' then 'Commercial'
            when '3' then 'NSM'         when '4' then 'Stores'
            when '5' then 'Dispatched'  when '6' then 'Received'
            else roll end, 'RM Approval');

  -- Written by this function only; the header guard below allows it via a flag.
  perform set_config('app.spare_rollup', '1', true);
  update public.spare_requests
     set stage  = roll,
         status = case when roll = 'Stores' then 'Awaiting Dispatch' else roll end
   where uid = p_uid and (stage is distinct from roll);
  perform set_config('app.spare_rollup', '', true);
end $$;

create or replace function public.spare_request_lines_rollup()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.spare_request_rollup(coalesce(new.request_uid, old.request_uid));
  return null;
end $$;

drop trigger if exists spare_request_lines_rollup on public.spare_request_lines;
create trigger spare_request_lines_rollup
  after insert or update or delete on public.spare_request_lines
  for each row execute function public.spare_request_lines_rollup();

-- ---------------------------------------------------------------------------
-- The per-stage guard moves to the line. Same rules as 0012 held on the
-- header: each stage's columns may only change if the actor holds that stage's
-- action; Commercial/NSM auto-approve alongside the RM on a non-AMC item; the
-- receipt needs spare.receive, the raiser, and a dispatched line.
-- ---------------------------------------------------------------------------
create or replace function public.spare_request_lines_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  changed boolean;
  auto_ok boolean;
  req     public.spare_requests;
begin
  if public.is_admin() then return new; end if;
  select * into req from public.spare_requests where uid = new.request_uid;

  auto_ok := not public.spare_needs_review(req.item_status)
             and public.has_perm('spare.approve_rm');

  changed := new.rm_approval is distinct from old.rm_approval
          or new.rm_by       is distinct from old.rm_by
          or new.rm_at       is distinct from old.rm_at;
  if changed and not public.has_perm('spare.approve_rm') then
    raise exception 'RBAC: RM approval requires the spare.approve_rm permission';
  end if;

  changed := new.commercial_approval is distinct from old.commercial_approval
          or new.commercial_by       is distinct from old.commercial_by
          or new.commercial_at       is distinct from old.commercial_at;
  if changed
     and not public.has_perm('spare.approve_commercial')
     and not (auto_ok and new.commercial_approval = 'Auto-Approved'
              and new.commercial_by is not distinct from old.commercial_by) then
    raise exception 'RBAC: Commercial approval requires the spare.approve_commercial permission';
  end if;

  changed := new.nsm_approval is distinct from old.nsm_approval
          or new.nsm_by       is distinct from old.nsm_by
          or new.nsm_at       is distinct from old.nsm_at;
  if changed
     and not public.has_perm('spare.approve_nsm')
     and not (auto_ok and new.nsm_approval = 'Auto-Approved'
              and new.nsm_by is not distinct from old.nsm_by) then
    raise exception 'RBAC: NSM approval requires the spare.approve_nsm permission';
  end if;

  changed := new.stores_status    is distinct from old.stores_status
          or new.dc_number        is distinct from old.dc_number
          or new.dispatched_by    is distinct from old.dispatched_by
          or new.dispatched_at    is distinct from old.dispatched_at
          or new.courier          is distinct from old.courier
          or new.dispatch_remarks is distinct from old.dispatch_remarks;
  if changed and not public.has_perm('spare.dispatch') then
    raise exception 'RBAC: dispatch / DC requires the spare.dispatch permission';
  end if;

  changed := new.reject_reason  is distinct from old.reject_reason
          or new.rejected_stage is distinct from old.rejected_stage;
  if changed and not public.can_approve_spares() then
    raise exception 'RBAC: recording a rejection requires an approval permission';
  end if;

  changed := new.received_by     is distinct from old.received_by
          or new.received_at     is distinct from old.received_at
          or new.receipt_remarks is distinct from old.receipt_remarks;
  if changed then
    if not public.has_perm('spare.receive') then
      raise exception 'RBAC: acknowledging receipt requires the spare.receive permission';
    end if;
    if not public.is_spare_requester(req) then
      raise exception 'RBAC: only the engineer who raised the request may acknowledge it';
    end if;
    if old.stores_status is null or old.stores_status !~* 'dispatch' then
      raise exception 'RBAC: a spare can only be acknowledged after it is dispatched';
    end if;
  end if;

  -- The part and quantity are the request; they are fixed once submitted.
  if (new.part is distinct from old.part or new.qty is distinct from old.qty)
     and not public.is_spare_requester(req) then
    raise exception 'RBAC: only the engineer who raised the request may change its parts';
  end if;

  return new;
end $$;

drop trigger if exists spare_request_lines_guard on public.spare_request_lines;
create trigger spare_request_lines_guard
  before update on public.spare_request_lines
  for each row execute function public.spare_request_lines_guard();

-- ---------------------------------------------------------------------------
-- The header no longer carries decisions. Its stage/status change only through
-- the roll-up; its approval columns are legacy and frozen for non-admins.
-- ---------------------------------------------------------------------------
create or replace function public.spare_requests_stage_guard()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_admin() then return new; end if;
  if coalesce(current_setting('app.spare_rollup', true), '') = '1' then return new; end if;

  if new.stage  is distinct from old.stage
  or new.status is distinct from old.status
  or new.rm_approval         is distinct from old.rm_approval
  or new.commercial_approval is distinct from old.commercial_approval
  or new.nsm_approval        is distinct from old.nsm_approval
  or new.stores_status       is distinct from old.stores_status
  or new.received_at         is distinct from old.received_at then
    raise exception 'Spare approvals are recorded per spare — update spare_request_lines, not the request';
  end if;
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- Approvers already update lines; the raiser must too, to acknowledge receipt.
-- ---------------------------------------------------------------------------
drop policy if exists srl_update on public.spare_request_lines;
create policy srl_update on public.spare_request_lines for update
  using (
    public.can_approve_spares()
    or exists (select 1 from public.spare_requests r
                where r.uid = spare_request_lines.request_uid and public.is_spare_requester(r))
  )
  with check (
    public.can_approve_spares()
    or exists (select 1 from public.spare_requests r
                where r.uid = spare_request_lines.request_uid and public.is_spare_requester(r))
  );

-- Bring every existing request's header into line with its lines.
do $$
declare u text;
begin
  for u in select uid from public.spare_requests loop
    perform public.spare_request_rollup(u);
  end loop;
end $$;

-- ------------------------------------------------------------------------
-- 0017_spare_or_number_monthly.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- OR numbers become OR-YY/MM/N, restarting at 1 every month.
--
-- 0011 issued a single running series (OR47042…) continuing the sheet's. The
-- required format is per-month instead: OR-26/08/1, OR-26/08/2, … and the
-- first request of September is OR-26/09/1.
--
-- Numbers already issued are NOT rewritten — they are quoted on DCs and in
-- Tally, so the old series stays as history and the new format starts here.
-- ===========================================================================

-- One counter per YY/MM period. Written only by next_spare_or_no().
create table if not exists public.spare_or_counters (
  period  text primary key,          -- 'YY/MM', e.g. '26/08'
  last_no integer not null default 0
);
alter table public.spare_or_counters enable row level security;  -- definer-only

-- Hand out the next number for a month. The upsert is atomic, so two requests
-- submitted at the same moment cannot take the same number.
create or replace function public.next_spare_or_no(p_on date default current_date)
returns text language plpgsql security definer set search_path = public as $$
declare
  p text := to_char(p_on, 'YY/MM');
  n integer;
begin
  insert into public.spare_or_counters (period, last_no) values (p, 1)
  on conflict (period) do update set last_no = public.spare_or_counters.last_no + 1
  returning last_no into n;
  return 'OR-' || p || '/' || n;
end $$;
grant execute on function public.next_spare_or_no(date) to authenticated;

-- If this month already has numbers in the new format (a re-run, or a partial
-- rollout), continue past the highest rather than colliding with it.
insert into public.spare_or_counters (period, last_no)
select to_char(coalesce(or_req_date, created_at::date), 'YY/MM'),
       max((regexp_replace(or_no, '^OR-\d\d/\d\d/', ''))::integer)
  from public.spare_requests
 where or_no ~ '^OR-\d\d/\d\d/\d+$'
 group by 1
on conflict (period) do update
  set last_no = greatest(public.spare_or_counters.last_no, excluded.last_no);

create or replace function public.spare_requests_assign_or_no()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.or_req_date is null then
    new.or_req_date := current_date;
  end if;
  if new.or_no is null or trim(new.or_no) = '' then
    -- Numbered in the month the request is raised in.
    new.or_no := public.next_spare_or_no(new.or_req_date);
  end if;
  return new;
end $$;

-- The old single running series is no longer used by anything.
drop sequence if exists public.spare_or_no_seq;

-- ------------------------------------------------------------------------
-- 0018_spare_or_number_padded.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- OR numbers pad the counter to three digits: OR-26/08/001.
--
-- 0017 wrote the counter bare (OR-26/08/1), which sorts wrongly as text once a
-- month passes nine requests — OR-26/08/10 lands before OR-26/08/2 in the
-- register and in CSV exports. Three digits sorts correctly to 999 a month.
--
-- Past 999 the number simply grows (OR-26/08/1000) and text ordering breaks
-- again at that point; no month is expected to come close.
-- ===========================================================================

create or replace function public.next_spare_or_no(p_on date default current_date)
returns text language plpgsql security definer set search_path = public as $$
declare
  p text := to_char(p_on, 'YY/MM');
  n integer;
begin
  insert into public.spare_or_counters (period, last_no) values (p, 1)
  on conflict (period) do update set last_no = public.spare_or_counters.last_no + 1
  returning last_no into n;
  return 'OR-' || p || '/' || lpad(n::text, 3, '0');
end $$;

-- ---------------------------------------------------------------------------
-- Restate the few numbers 0017 issued unpadded. This is the same number in the
-- required format, not a renumbering: OR-26/08/1 becomes OR-26/08/001, same
-- month, same position in the series. The unpadded form was only ever live
-- between 0017 and this migration.
--
-- The immutability trigger is dropped first: it refuses any or_no change from
-- a non-admin, and in the Supabase SQL Editor auth.uid() is NULL so is_admin()
-- is false. It is recreated below, which also makes this safe to re-run.
-- ---------------------------------------------------------------------------
drop trigger if exists spare_requests_number_immutable on public.spare_requests;

update public.spare_requests r
   set or_no = 'OR-' || substring(or_no from 4 for 5) || '/'
               || lpad(substring(or_no from 10), 3, '0')
 where or_no ~ '^OR-\d\d/\d\d/\d{1,2}$'
   -- never write over a number that already exists in the padded form
   and not exists (
     select 1 from public.spare_requests x
      where x.or_no = 'OR-' || substring(r.or_no from 4 for 5) || '/'
                      || lpad(substring(r.or_no from 10), 3, '0')
        and x.uid <> r.uid);

create trigger spare_requests_number_immutable
  before update on public.spare_requests
  for each row execute function public.spare_requests_number_immutable();

-- Re-seed the counters from the padded numbers, so a re-run cannot hand out
-- one that is taken (0017's seeding only matched the unpadded form).
insert into public.spare_or_counters (period, last_no)
select to_char(coalesce(or_req_date, created_at::date), 'YY/MM'),
       max((regexp_replace(or_no, '^OR-\d\d/\d\d/', ''))::integer)
  from public.spare_requests
 where or_no ~ '^OR-\d\d/\d\d/\d+$'
 group by 1
on conflict (period) do update
  set last_no = greatest(public.spare_or_counters.last_no, excluded.last_no);

commit;
