-- ===========================================================================
-- RITHI CRM — Tracker (the shared activity list): apply bundle
--
-- tracker_items --- the in-app backlog: what is being worked on, who it is
-- with, and where it has got to. ONE permission (mod:/tracker) grants both
-- the page and the right to add and edit, because everyone who can see it
-- can change it. Granted to ADMIN only here; anyone else is added by hand
-- on Roles & Permissions.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0143_tracker.sql
--   0144_tracker_seed_backlog.sql
--   0146_tracker_air_liquide_id.sql
--   0150_tracker_sync_backlog.sql
--   0157_tracker_sync_0909.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regprocedure('public.has_perm(text)') is null then
    missing := array_append(missing, 'has_perm() — 0008_rbac_enforcement.sql (apply bundle: rbac)');
  end if;
  if to_regprocedure('public.visible_engineer_names()') is null then
    missing := array_append(missing, 'visible_engineer_names() — 0004_user_directory.sql (apply bundle: user_directory)');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0143_tracker.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE TRACKER — a shared list of what is being worked on.
--
-- The user, 2026-09-08: "add a tracker page under admin to track activities.
-- something very similar to backlog.. shared between me and a few other. all who
-- have access should be able add, edit".
--
-- SO IT IS ONE PERMISSION, NOT TWO. `mod:/tracker` grants the page AND the right
-- to add and edit on it -- "all who have access should be able to add, edit" is
-- the whole access model, and splitting it into a view right and an edit right
-- would invent a distinction the user did not ask for and then require two ticks
-- to undo. Sharing it with somebody is one tick in Roles & Permissions.
--
-- Nothing is granted to any role here except ADMIN. A tracker that arrived
-- already visible to the whole company would be the opposite of "shared between
-- me and a few other" -- the few are chosen, not defaulted.
--
-- NOTHING IS EVER DELETED BY ACCIDENT, and nothing is hidden either. An item is
-- CLOSED (status Done or Dropped) and stays on the list; the page filters it out
-- of the default view. A shared list people delete from is one nobody trusts,
-- because the thing you remember agreeing is simply not there any more and there
-- is no way to tell whether it was done or dropped. Deleting is still possible
-- and is a deliberate act on the row.
--
-- WHO TOUCHED IT LAST IS THE POINT OF A SHARED LIST. `updated_by` and
-- `updated_at` are stamped by a trigger, not by the client -- so they cannot be
-- forgotten, and cannot be set to somebody else. `app_user_names` (0068) turns
-- the id into a name for the screen.
--
-- FREE TEXT WHERE THE BACKLOG HAS PROSE. `status` and `area` are plain text with
-- a CHECK only on status: a tracker whose categories have to be migrated before
-- somebody can file a thought is a tracker people keep in a spreadsheet instead.
-- ===========================================================================

create table if not exists public.tracker_items (
  id          bigint generated always as identity primary key,
  title       text not null,
  detail      text not null default '',
  -- OPEN is the default because an item somebody just typed is open by
  -- definition, and making them choose is a step that adds nothing.
  status      text not null default 'Open'
              check (status in ('Open', 'In progress', 'Blocked', 'Done', 'Dropped')),
  -- WHO IT IS WITH -- free text, because it is as often "a decision" or a
  -- customer as it is a person on this system.
  owner       text not null default '',
  area        text not null default '',      -- Calls, Spares, Objectives, Data …
  due_date    date,
  -- Hand ordering, so the list can be arranged the way the people using it
  -- think about it rather than by whatever they happened to type first.
  sort_order  integer not null default 0,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_by  uuid,
  updated_at  timestamptz not null default now()
);

create index if not exists tracker_items_open_idx
  on public.tracker_items (status, sort_order, id);

alter table public.tracker_items enable row level security;

-- ONE PERMISSION FOR BOTH. `for all` covers select, insert, update and delete;
-- `using` gates the rows a reader sees and `with check` the rows a writer may
-- leave behind, and both ask the same question.
drop policy if exists tracker_rw on public.tracker_items;
create policy tracker_rw on public.tracker_items for all
  using (public.has_perm('mod:/tracker'))
  with check (public.has_perm('mod:/tracker'));

grant select, insert, update, delete on public.tracker_items to authenticated;

-- ---------------------------------------------------------------------------
-- WHO, AND WHEN -- stamped here so a client cannot forget it or fake it.
-- ---------------------------------------------------------------------------
create or replace function public.tracker_items_stamp()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.updated_at := now();
  if auth.uid() is not null then new.updated_by := auth.uid(); end if;
  if tg_op = 'INSERT' then
    new.created_at := now();
    if auth.uid() is not null then new.created_by := auth.uid(); end if;
  else
    -- An edit cannot rewrite who raised it, or when.
    new.created_by := old.created_by;
    new.created_at := old.created_at;
  end if;
  return new;
end $$;
drop trigger if exists zz_tracker_items_stamp on public.tracker_items;
create trigger zz_tracker_items_stamp before insert or update on public.tracker_items
  for each row execute function public.tracker_items_stamp();

-- ---------------------------------------------------------------------------
-- THE LIST, WITH NAMES. A shared tracker showing UUIDs would be unreadable, and
-- every consumer resolving them itself is how two screens end up disagreeing
-- about who did something.
--
-- SECURITY INVOKER, so the policy above is what decides who sees it -- not the
-- view's owner. This project has been bitten three times by a view that read as
-- its owner (0040, 0050, 0057) and a shared list is exactly where that would go
-- unnoticed.
-- ---------------------------------------------------------------------------
drop view if exists public.tracker_list;
create view public.tracker_list as
  select t.*,
         coalesce(cu.name, '') as created_by_name,
         coalesce(uu.name, '') as updated_by_name,
         (t.status in ('Done', 'Dropped')) as is_closed
    from public.tracker_items t
    left join public.app_user_names cu on cu.id = t.created_by
    left join public.app_user_names uu on uu.id = t.updated_by;
alter view public.tracker_list set (security_invoker = on);
grant select on public.tracker_list to authenticated;

comment on table public.tracker_items is
  'A shared list of what is being worked on -- the in-app backlog. One permission (mod:/tracker) grants both the page and the right to add and edit, because "all who have access should be able to add, edit" is the access model. Nothing is auto-deleted: an item is Done or Dropped and stays, because a shared list people delete from is one nobody trusts.';

-- ---------------------------------------------------------------------------
-- ADMINS ONLY, TO BEGIN WITH. Everyone else is added by hand on Roles &
-- Permissions -- "a few other" is a choice somebody makes, not a default.
--
-- MERGED, never overwritten: an administrator may have tuned the role already.
-- ---------------------------------------------------------------------------
update public.app_roles ar
   set permissions = (
         select coalesce(jsonb_agg(distinct v), '[]'::jsonb)
           from (
             select jsonb_array_elements_text(ar.permissions) as v
             union
             select 'mod:/tracker' as v
           ) u
       ),
       updated_at = now()
 where ar.role = 'admin'
   and not (ar.permissions ? 'mod:/tracker');

-- ------------------------------------------------------------------------
-- 0144_tracker_seed_backlog.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE BACKLOG'S OPEN ITEMS, ON THE TRACKER.
--
-- The user, 2026-09-08: "Add all backlog Items to Tracker".
--
-- Every item from `docs/BACKLOG.md`'s OPEN ITEMS index, as at the day the
-- Tracker shipped. Seeding it in SQL rather than by hand is the only way the
-- rows reach the live database at all -- and it means the list arrives the same
-- on every project, rather than depending on who typed it in.
--
-- ONLY WHAT IS OPEN. The backlog is 2,000 lines and most of it is the record of
-- decisions already made -- reasoning, warnings, what was applied when. That
-- belongs where it is. What moves here is the part with something still to do:
-- copying the rest would bury the fifteen live items under two hundred settled
-- ones, and a tracker nobody can scan is a tracker nobody reads.
--
-- SO THE TWO ARE NOT THE SAME LIST AND SHOULD NOT BECOME ONE. The backlog keeps
-- the reasoning; the tracker keeps what is being worked on now. An item finished
-- here does not delete its entry there.
--
-- `owner` IS WHO IT IS WITH, not who will do it -- "Rithi Admin", "Decision",
-- "Claude". That is the question a shared list is actually asked ("what is
-- waiting on me?"), and it is the backlog index's own grouping.
--
-- IT SAYS "RITHI ADMIN", NOT "YOU" (the user, 2026-09-08: "Replace all 'You' to
-- Rithi Admin in the Tracker"). On a list one person keeps, "You" is clear; on a
-- SHARED one it is the one word that means somebody different to every reader --
-- so the rename is what makes the owner column mean anything at all. The block
-- below renames rows that are already out there, because the seed only inserts
-- items it has not seen and would otherwise leave the old wording in place.
--
-- IDEMPOTENT BY TITLE. The bundles are replayed one at a time and re-run freely,
-- so every insert is guarded: running this twice does not give anybody a second
-- copy of the same task, and an item somebody has since EDITED or CLOSED is left
-- exactly as they left it.
-- ===========================================================================

do $seed$
declare
  seeded int := 0;
  r      record;
begin
  if to_regclass('public.tracker_items') is null then
    raise notice 'tracker_items is missing -- run tracker.sql first';
    return;
  end if;

  -- The rename, for rows already on somebody's tracker. Narrow on purpose: only
  -- the exact word, and only in the column it was wrong in.
  update public.tracker_items set owner = 'Rithi Admin', updated_at = now()
   where btrim(owner) = 'You';

  for r in
    select * from (values
      -- ---- waiting on the user ------------------------------------------
      (10, 'The PM count is short',
           '7,029 rows in pm_calls where two years at 10,000/yr should be ~20,000 — about a third. Whatever loaded it stopped early or was filtered. Find out BEFORE nine years of history load through the same path, or the backfill silently loses two thirds of itself.',
           'Rithi Admin', 'Data'),
      (20, 'PM rows measure ~2x field-call rows',
           '2,088 bytes/row against field_calls'' 1,124, for tables with IDENTICAL columns (the 0040 split). Either PM complaint text really is twice as long, or pm_calls is carrying bloat. Across 150,000 calls that is 170 MB vs 310 MB of rows — 140 MB on a 500 MB allowance.',
           'Rithi Admin', 'Storage'),
      (30, 'handstock_period.closed_through — is a period closed?',
           'While it is NULL, handstock_cutoff() is -infinity and EVERY row of spare_issue_history + spare_consumption_history (68 MB) still feeds live hand stock. Nothing there is safe to move until a period is closed. Hand stock is derived, never stored, so removing source rows changes balances with no error and no warning.',
           'Rithi Admin', 'Spares'),
      (40, 'What six AppSheet columns held',
           'CALL DETAILS, VISIT REMARKS, CHANGE PRODUCT?, SEND EMAIL FOR DEFECTIVE SPARE, SL NO(T), Complaint. They are in the DCCR export as blank columns so WRR-2026 keeps its shape. Two sample rows from the old sheet would settle it. Three are near-duplicates of columns that ARE exported, which is where a wrong guess would go unnoticed.',
           'Rithi Admin', 'Reliability'),
      (50, 'Four objectives still typed, and the CPX rule',
           'FFR field failures, PM Calls, Installation call, b.Customer feedback have no formula yet. public.feedback exists but nothing says how a score is derived from it. Also the CPX failure rule, which was deferred.',
           'Rithi Admin', 'Objectives'),
      (60, 'Call Update and Cancelled Calls — the legacy files',
           'Should update status, complaint details and allocated-to on EXISTING calls. Needs an update-only import mode: an upsert on ucn would INSERT a stub call for any UCN not in the register. Calls also live in three tables, so it must route by looking the UCN up rather than trusting the picker; and cancellation should go through cancel_call(), which checks the permission and insists on a reason. Waiting on: the files (or their headers), and whether a blank cell clears a field or leaves it.',
           'Rithi Admin', 'Data'),

      -- ---- waiting on a decision -----------------------------------------
      (70, 'Supabase Pro, or split across projects?',
           'Nine years of history is ~300 MB of rows and ~1.25 GB with this project''s indexing. The free tier cannot hold it even split three ways. Pro is 8 GB for about $25/mo and keeps everything joinable, RLS working, and the apply bundles meaningful. Splitting a validated quality system across databases nobody can join costs more than the subscription.',
           'Decision', 'Storage'),
      (80, 'REINDEX the fat tables',
           'Index bloat is real here: record_audit holds 8 MB of indexes over 792 kB of rows. Likely 30–60 MB back for no behaviour change and no risk. reindex index concurrently does not block writes.',
           'Decision', 'Storage'),

      -- ---- waiting on me -------------------------------------------------
      (90, 'The reliability export itself',
           'reliability_wrr (WRR-2026 columns 1–14) and DCCR_EXPORT_COLUMNS (15–67) are both ready and both verified against the workbook. Nothing yet WRITES the file. src/lib/xlsx.ts already makes multi-sheet workbooks.',
           'Claude', 'Reliability'),
      (100, 'has_perm() returns NULL with no signed-in user',
           'my_extra_perms() returns NULL, so has_perm() does, so `if not has_perm(...)` never fires and execution falls through into the write. Fixed in the two functions 0139 touched; 15 OTHER MIGRATIONS still use the bare pattern. Latent rather than exploitable — execute is granted to `authenticated` only — but that is a second lock, not a reason to leave the first open.',
           'Claude', 'Security'),

      -- ---- long-standing --------------------------------------------------
      (110, 'Audit Mode rules', 'Carried in the backlog since before this round.', '', 'Compliance'),
      (120, 'The security migration (D-2 / D-3 / D-4)', 'Carried in the backlog since before this round.', '', 'Security'),
      (130, 'A CI workflow', 'Nothing runs the check scripts or the SQL suites automatically; every round is verified by hand.', '', 'Ops'),
      (140, 'Two data uploads still outstanding',
            'The 77 missing yearly consumptions (delete + re-upload the four files per _yearly_consumption_check.sql, to 39,801 total with 12,015 in 2024), and the Ownership Transfer upload.',
            'Rithi Admin', 'Data'),
      (150, 'engineer_stock needs security_invoker',
            'Carried in the backlog: a view over RLS-protected tables that does not apply RLS to the reader.', 'Claude', 'Security')
    ) as t(ord, title, detail, owner, area)
  loop
    if not exists (select 1 from public.tracker_items i where i.title = r.title) then
      insert into public.tracker_items (title, detail, owner, area, status, sort_order)
           values (r.title, r.detail, r.owner, r.area, 'Open', r.ord);
      seeded := seeded + 1;
    end if;
  end loop;

  raise notice 'Tracker: % backlog item(s) added (% already there)',
    seeded, 15 - seeded;
end $seed$;

-- ------------------------------------------------------------------------
-- 0146_tracker_air_liquide_id.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- ONE TRACKER ITEM, ADDED BY SQL RATHER THAN BY HAND.
--
-- The user, 2026-09-08: "Add - Collect Engineer's Air Liquide ID , Map it in
-- the User Master and then Inform the Rithi Admin - Assign it to Devika".
--
-- WHY A MIGRATION FOR ONE ROW. The Tracker is a live table nobody can write to
-- from here -- the sandbox has no route to the database, and applying SQL is
-- the user's own step by design. A seeded row travels with the bundle instead,
-- so it arrives the same on every project rather than depending on who typed it
-- in. It is a row somebody could equally add on the page in twenty seconds;
-- this way it is also in the record.
--
-- IDEMPOTENT BY TITLE, like 0144. Running the bundle twice does not give
-- anybody a second copy, and an item somebody has since edited or closed is
-- left exactly as they left it.
-- ===========================================================================

do $seed$
declare
  seeded int := 0;
begin
  if to_regclass('public.tracker_items') is null then
    raise notice 'tracker_items is missing -- run tracker.sql first';
    return;
  end if;

  if not exists (
    select 1 from public.tracker_items i
     where i.title = 'Collect every engineer''s Air Liquide ID'
  ) then
    insert into public.tracker_items (title, detail, owner, area, status, sort_order)
    values (
      'Collect every engineer''s Air Liquide ID',
      'Collect the Air Liquide ID from each engineer, map it against their row in User Master, and tell the Rithi Admin once it is done. The mapping is what lets a person be recognised across both systems; until it exists the two directories can only be matched by name, which is exactly the join that goes wrong quietly.',
      'Devika',
      'Data',
      'Open',
      -- ABOVE the seeded backlog (which starts at 10). It was asked for
      -- directly and has a named owner, which the backlog items mostly do not.
      5
    );
    seeded := 1;
  end if;

  raise notice 'Tracker: % item added (Air Liquide ID)', seeded;
end $seed$;

-- ------------------------------------------------------------------------
-- 0150_tracker_sync_backlog.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE TRACKER CATCHES UP WITH THE BACKLOG.
--
-- The user, 2026-09-08: "Update the Tracker as per backlog."
--
-- 0144 seeded the fifteen items open when the Tracker shipped. A day of work
-- has happened since: the 13485 review raised its own, three decisions were
-- PARKED at the user's direction, and Indoor Service went from an unanswered
-- question to a written plan. This adds what is open now and was not there
-- then.
--
-- ADDITIVE, AND IDEMPOTENT BY TITLE. Nothing is closed, renamed or deleted
-- here. An item somebody has since edited, re-owned or marked Done is left
-- exactly as they left it, and running the bundle twice adds nothing -- the
-- same rule 0144 follows, and the reason a seed can live in a bundle that is
-- replayed freely.
--
-- WHY NOT CLOSE THE ONES THAT ARE DONE. Because "done" is a judgement the
-- people using the list make, not one a migration should make for them: a row
-- closed by SQL is a row somebody has to re-open to argue with. The backlog
-- records what shipped; the Tracker records what those people are working on,
-- and the two are deliberately not the same list.
-- ===========================================================================

do $seed$
declare
  seeded int := 0;
  r      record;
begin
  if to_regclass('public.tracker_items') is null then
    raise notice 'tracker_items is missing -- run tracker.sql first';
    return;
  end if;

  for r in
    select * from (values
      -- ---- parked decisions (the user, 2026-09-08: "Park it in Backlog") ----
      (200, 'DECISION: Frequent Failure — the complaint condition, and old answers',
            'The rule is settled and written down: two or more failures INCLUDING the call under review, within a month, same equipment or the same part in the same machine, window and threshold editable in Admin Config. Two things block the build. (1) Does the same-equipment path still require a matching complaint? The rule of 2026-09-06 said yes; the written procedure does not mention it. (2) Review 2 auto-answers on a schedule (0124), so a new rule re-bases judgements already recorded — leave them as answered, or re-open them? Either way a quality record is being restated.',
            'Decision', 'DCCR'),
      (210, 'DECISION: ANNEXURE A — CMC''s bucket, and two missing call fields',
            'The SLA cannot express the procedure. sla_rules holds ONE target_hours per key; ANNEXURE A is a cover x problem-criticality x spare-availability matrix. Criticality and spare availability do not exist as fields on a call, so capturing them is a change to call registration rather than to a rules table. And CMC is a live cover type (WGP/OGP/CMC/AMC) that ANNEXURE A does not mention. Until then breach highlighting measures against targets the procedure does not set: closure = 5 days where it says 3, closure_spare_noncover = 10 where it says 15, and nothing at all for the four OGP rows.',
            'Decision', 'SLA'),
      (220, 'DECISION: Indoor Service — five questions before Phase 1',
            'The plan is written and phased (docs/INDOOR_SERVICE_PLAN.md). Five things to settle: does Central Service hold its own spare stock; must QC be done by somebody other than the person who did the work; does the SLA clock keep running while a machine is on the bench; the job-number series (IND26-0001?); and who may transfer a call to Indoor — Hotline only, as the procedure says, or managers too. Phase 1 stands alone and is what finally makes the Indoor Service heading appear, since a nav group with no pages renders as nothing.',
            'Decision', 'Indoor Service'),

      -- ---- the 13485 review ------------------------------------------------
      (230, 'Post-service verification against acceptance criteria (SR-006)',
            'The largest gap in the servicing requirements. §7.5.4 asks that it is verified that product requirements are met after servicing; "Solved" is a CALL outcome, not a statement that the device performs to specification. The Indoor procedure §4.5.6 already requires a quality check on completion — so the process exists and the RECORD lives outside this system. A per-product checklist of parameter, expected value and pass/fail, on the visit that closes a call.',
            'Claude', 'Quality'),
      (240, 'A measurement is not tied to a calibrated instrument (SR-020)',
            '§7.6. No instrument register, no calibration due dates, and a service report does not record WHICH instrument produced a reading — so a measurement does not evidence conformity, and an instrument later found out of calibration cannot be traced to the records it touched. Only worth building after SR-006 exists.',
            'Claude', 'Quality'),
      (250, 'The complaint determination is not recorded (SR-027)',
            'Cheapest real gain in the whole review, and now load-bearing: the field call register IS the complaint register by the decision of 2026-09-08, so a field marking WHICH calls are complaints is what makes the population producible. Without it the register says either that every field call is a complaint (untrue, and it inflates the rate) or that none is. One controlled field and a reason, on the Daily Call Review that already runs daily — plus SR-039, the recorded handoff to the system that holds CAPA, since §7.5.4(b) does not end at a system boundary.',
            'Claude', 'Quality'),
      (260, 'A complaint that never becomes a call has nowhere to live (SR-038)',
            'The exposure the boundary decision creates. If the field call register is the complaint register, a complaint arriving by any other route — a customer emailing Commercial about labelling, a distributor report on a device already replaced — is recorded nowhere. Either every complaint enters as a call, or the complaint register is elsewhere and this system feeds it. What cannot stand is the middle.',
            'Decision', 'Quality'),
      (270, 'Is any servicing subcontracted?',
            '§7.5.4 says "the organization OR ITS SUPPLIER". If any servicing is subcontracted, those records sit outside the daily analysis entirely and the gap is invisible from inside RITHI. Worth confirming either way — a no closes SR-035/036 permanently.',
            'Rithi Admin', 'Quality')
    ) as t(ord, title, detail, owner, area)
  loop
    if not exists (select 1 from public.tracker_items i where i.title = r.title) then
      insert into public.tracker_items (title, detail, owner, area, status, sort_order)
           values (r.title, r.detail, r.owner, r.area, 'Open', r.ord);
      seeded := seeded + 1;
    end if;
  end loop;

  raise notice 'Tracker: % item(s) added from the backlog (% already there)',
    seeded, 8 - seeded;
end $seed$;

-- ------------------------------------------------------------------------
-- 0157_tracker_sync_0909.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- THE TRACKER CATCHES UP — the points open at the end of 2026-09-09.
--
-- The user: "then list the Pending points and update the tracker."
--
-- ADDITIVE AND IDEMPOTENT BY TITLE, like 0144 and 0150. Nothing is closed,
-- renamed or deleted: an item somebody has edited, re-owned or marked Done is
-- left exactly as they left it, and running the bundle twice adds nothing.
--
-- "Done" stays a judgement the people using the list make. A row closed by SQL
-- is a row somebody has to re-open to argue with -- and the two lists are
-- deliberately different: the backlog records what shipped and why, the Tracker
-- records what is being worked on.
--
-- WHAT IS NOT HERE: everything already seeded by 0144 and 0150 (the parked
-- decisions, the 13485 findings). This adds only what became open since, or
-- what was open all along and had never been written down.
--
-- ONE ITEM WAS REMOVED BEFORE THIS FILE EVER RAN (2026-09-09): "Confirm the
-- super-admin revocation actually took". The user pasted the _status.sql output
-- the same evening and row 118 read `yes`, so the question was answered before
-- the seed could ask it. Seeding an answered item as Open would put a job on
-- somebody's list that is already done -- and closing it here in SQL would break
-- this file's own rule that Done is the reader's judgement. So it is simply not
-- seeded. (If an earlier copy of 0157 had already run somewhere, the row exists
-- and is Open; tick it.)
-- ===========================================================================

do $seed$
declare
  seeded int := 0;
  total  int := 0;
  r      record;
begin
  if to_regclass('public.tracker_items') is null then
    raise notice 'tracker_items is missing -- run tracker.sql first';
    return;
  end if;

  for r in
    select * from (values
      -- ---- verification the user can close in a minute ---------------------
      (310, 'Assign the Zoho Migration role to a login',
            'The role exists and is a read-only clone of Technical Support, but nobody holds it. It is in the User Master role dropdown. Kept separate from Technical Support on purpose: it ends when the migration does, so revoking it is one tick and leaves the support login alone.',
            'Rithi Admin', 'Access'),

      -- ---- parked, with the reason it is parked ---------------------------
      (320, 'Un-park the auto-apply pipeline (one character)',
            'CI/CD to apply migrations is BUILT and merged but parked. It failed on an unencoded "@" in the database password -- psql read the tail of the password as part of the hostname, so it never reached the database. Percent-encode it (@ -> %40) in the SUPABASE_DB_URL secret, then Actions -> Apply database migrations -> mode baseline with baseline_through set to the last migration really applied, then mode apply. WARNING: a fragment of the password reached a PUBLIC Actions log before the scrubber was fixed -- reset the database password and delete those runs when picking this up.',
            'Rithi Admin', 'Infrastructure'),

      -- ---- design settled, not built --------------------------------------
      (330, 'Indoor Service: build Phase 1, now the activities are settled',
            'Vignesh supplied the activity types on 2026-09-09 and the plan now carries six with their fields (docs/INDOOR_SERVICE_PLAN.md). Phase 1 is the register, the page, the nav group and the permissions -- it stands alone, since DEMO units alone justify it and it needs nothing from the call side. Four new questions are open at the end of that file, the sharpest being whether a salvaged part re-enters stock under its own code; if it does not, its condition grade is decoration.',
            'Claude', 'Indoor Service'),
      (340, 'DECISION: who may condemn a unit, and where a salvaged part goes',
            'From the Indoor activity work. Scrapping CUSTOMER property in particular cannot be an engineer''s own decision. And a harvested part entering stock under its normal code is indistinguishable from new -- the register already holds a refurbished part under its own code (URS-027), and salvage should do the same or the condition grade means nothing.',
            'Decision', 'Indoor Service'),

      -- ---- open data questions --------------------------------------------
      (350, 'Party spellings: run the tidy-up, or leave it',
            'A party spelled two ways showed no products, because products carried CAPITALS while the party row was Title Case. The register is CORRECT without any SQL -- the lookups match case-insensitively as of v0.9.174. _party_name_normalise.sql is an optional tidy-up (dry run by default) that aligns the stored spellings so exports and groupings agree too, and separately lists products whose party has no row at all.',
            'Rithi Admin', 'Data'),
      (360, 'The spare_bulk_approval suite emits an unlabelled error',
            'Pre-existing, and reproduces identically against main''s own migrations, so it is not from any recent change -- but by this project''s convention every error a suite prints should be one labelled "expect ERROR", and this one is not. "Nothing selected" at line 135, where the fixture''s BA-R2 lines appear not to exist.',
            'Claude', 'Testing')
    ) as t(ord, title, detail, owner, area)
  loop
    total := total + 1;
    if not exists (select 1 from public.tracker_items i where i.title = r.title) then
      insert into public.tracker_items (title, detail, owner, area, status, sort_order)
           values (r.title, r.detail, r.owner, r.area, 'Open', r.ord);
      seeded := seeded + 1;
    end if;
  end loop;

  raise notice 'Tracker: % of % item(s) added (% already there)', seeded, total, total - seeded;
end $seed$;

commit;
