-- ===========================================================================
-- RITHI CRM — User Directory: apply bundle
--
-- The engineer directory (User Master) and the reporting-tree helpers that
-- call and spare visibility are scoped by, including the delivery address a
-- parcel is sent to.
-- 
-- Also `app_user_names` --- id -> display name and nothing else --- so the
-- tables can show WHO created a row instead of a raw UUID. Readable by any
-- signed-in user, which discloses no more than the directory itself.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0004_user_directory.sql
--   0029_engineer_address.sql
--   0068_app_user_names.sql
--   0092_visible_engineers_by_name.sql
--   0212_visible_engineers_no_blank_match.sql
--   0257_directory_rename_carries_the_team.sql
--   0259_directory_rename_carries_the_records.sql
--   0267_rename_carries_adjustments.sql
--   0346_rename_carries_pending_indoor_dc.sql
--   0408_user_tags.sql
--   0122_user_directory_replay_tail.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0004_user_directory.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- User Master → user_directory: the engineer/manager directory (names +
-- reporting hierarchy) that drives who-sees-what. Separate from auth logins
-- (profiles): a person is scoped by matching their login email to a directory
-- row, then by the RM/RGM tree (by name). Admins (profiles.role='admin') see all.
-- ===========================================================================

create table if not exists public.user_directory (
  id                 bigint generated always as identity primary key,
  name               text not null,               -- User Name (matches "Call Allocated To")
  email              text default '',
  gmail              text default '',
  designation        text default '',
  reporting_manager  text default '',             -- RM name
  regional_manager   text default '',             -- RGM name
  region             text default '',
  validity           boolean not null default true,
  extra              jsonb not null default '{}'
);
create index if not exists user_directory_email_idx on public.user_directory (lower(email));
create index if not exists user_directory_gmail_idx on public.user_directory (lower(gmail));
create index if not exists user_directory_name_idx  on public.user_directory (lower(name));

alter table public.user_directory enable row level security;
drop policy if exists ud_read on public.user_directory;
create policy ud_read on public.user_directory for select using (auth.role() = 'authenticated');
drop policy if exists ud_admin_write on public.user_directory;
create policy ud_admin_write on public.user_directory for all using (public.is_admin()) with check (public.is_admin());

-- The signed-in user's directory name (by login email or gmail).
create or replace function public.my_dir_name()
returns text language sql stable security definer set search_path = public as $$
  select name from public.user_directory
   where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
   limit 1;
$$;

-- Names the current user may see: their own + everyone in their reporting
-- sub-tree (recursive over reporting_manager / regional_manager, by name).
create or replace function public.visible_engineer_names()
returns setof text language sql stable security definer set search_path = public as $$
  with recursive me as (
    select name from public.user_directory
     where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
  ),
  tree as (
    select d.name from public.user_directory d where d.name in (select name from me)
    union
    select c.name from public.user_directory c
      join tree t
        on lower(c.reporting_manager) = lower(t.name)
        or lower(c.regional_manager)  = lower(t.name)
  )
  select name from tree where coalesce(name,'') <> '';
$$;

-- can_see_call() already uses visible_engineer_names(), so call scoping now
-- follows the directory automatically (admins still bypass via is_admin()).

-- ------------------------------------------------------------------------
-- 0029_engineer_address.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- An engineer's delivery address, on the User Master.
--
-- The Declaration form that travels with the parcel ("TO WHOMSOEVER IT MAY
-- CONCERN") addresses it to the engineer. The User Master is where that
-- belongs — its sheet already has ADDRESS / CITY / STATE / Contact No columns,
-- and the User Master screen already showed City, State and Contact — but
-- user_directory never carried them, so on Supabase those columns were blank
-- and the form had nothing to read.
--
-- The four join the directory row, beside the name every other module already
-- refers to an engineer by, so one address serves every future document.
--
-- WHO MAY WRITE THEM is a separate migration (0030_engineer_address_write),
-- because its policy calls has_perm(), which the RBAC module defines and which
-- applies after this one. The columns themselves belong here, with the rest of
-- the User Master.
-- ===========================================================================

alter table public.user_directory
  add column if not exists address text default '',
  add column if not exists city    text default '',
  add column if not exists state   text default '',
  add column if not exists phone   text default '';

-- A directory imported before these were columns put them in `extra` (the
-- in-app importer kept every unmapped sheet column there). Lift them across,
-- so an existing deployment does not have to re-import to address a parcel.
--
-- The write guard is dropped first when it exists: this is a data migration,
-- not somebody editing the directory, and auth.uid() is NULL in the SQL
-- editor, so the guard would refuse it. It is put back below — and on a first
-- run there is nothing to put back, since 0030 has not created it yet.
drop trigger if exists user_directory_address_guard on public.user_directory;

update public.user_directory u
   set address = coalesce(nullif(btrim(u.address), ''),
                          nullif(btrim(u.extra ->> 'ADDRESS'), ''),
                          nullif(btrim(u.extra ->> 'Address'), ''), ''),
       city    = coalesce(nullif(btrim(u.city), ''),
                          nullif(btrim(u.extra ->> 'CITY'), ''),
                          nullif(btrim(u.extra ->> 'City'), ''), ''),
       state   = coalesce(nullif(btrim(u.state), ''),
                          nullif(btrim(u.extra ->> 'STATE'), ''),
                          nullif(btrim(u.extra ->> 'State'), ''), ''),
       phone   = coalesce(nullif(btrim(u.phone), ''),
                          nullif(btrim(u.extra ->> 'Contact  No'), ''),
                          nullif(btrim(u.extra ->> 'Contact No'), ''),
                          nullif(btrim(u.extra ->> 'Contact'), ''), '')
 where u.extra <> '{}'::jsonb;

do $$
begin
  if to_regprocedure('public.user_directory_address_guard()') is not null then
    create trigger user_directory_address_guard
      before update on public.user_directory
      for each row execute function public.user_directory_address_guard();
  end if;
end $$;

-- ------------------------------------------------------------------------
-- 0068_app_user_names.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- Who is `created_by`?
--
-- Every quality record stamps `auth.uid()` into created_by / recorded_by /
-- reported_by, and the tables show that raw UUID: Material Returns reads
-- "6680c358-d798-41d0-8f1d-fd543a1c96c5" where it should read "Rithi Admin".
-- The name lives in `profiles`, but its read policy is
--   id = auth.uid() or is_admin() or has_perm('users.manage')
-- so an engineer can only ever resolve their own id — which is why the app
-- cannot do the lookup client-side today.
--
-- `app_user_names` is the narrowest thing that fixes it: id -> display name,
-- and nothing else. No email, no role, no manager, no permissions. Every
-- signed-in user may read it, which discloses no more than `user_directory`
-- (0004) already does — that lists everyone's name to any authenticated user.
--
-- READ-ONLY BY CONSTRUCTION. The RLS bypass lives in a SECURITY DEFINER
-- function and the view merely selects from it, which makes the view
-- non-auto-updatable: no INSERT / UPDATE / DELETE can be routed through it into
-- `profiles`, whatever privileges Supabase's default grants hand out. A plain
-- `select ... from profiles` view would have been auto-updatable and, running
-- as its owner, would have let any signed-in user rewrite or delete every
-- profile row straight past the policy above. The grants below are belt to that
-- braces, not the mechanism.
-- ===========================================================================

create or replace function public.app_user_names_rows()
returns table (id uuid, name text)
language sql stable security definer set search_path = public as $$
  select p.id, coalesce(nullif(trim(p.full_name), ''), p.email, '')
    from public.profiles p;
$$;
-- EXECUTE is checked against the CALLER even inside a view that runs as its
-- owner (owner rights cover table access, not function execute), so the reader
-- needs it. It hands out exactly what the view does — id and name — so this is
-- the same disclosure, not a wider one. anon gets neither.
revoke all on function public.app_user_names_rows() from public, anon;
grant execute on function public.app_user_names_rows() to authenticated;

create or replace view public.app_user_names as
  select id, name from public.app_user_names_rows();

revoke all on public.app_user_names from public, anon, authenticated;
grant select on public.app_user_names to authenticated;

-- ------------------------------------------------------------------------
-- 0092_visible_engineers_by_name.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A REPORTING MANAGER WHO SEES NOTHING, WHILE THE SCREEN SAYS "15 engineers".
--
-- Two implementations of one rule, disagreeing:
--
--   * the CLIENT finds the signed-in person in the User Master by their email,
--     their gmail OR their username, then walks the reporting tree — which is
--     how the header can say "Team view · 15 engineers";
--   * `visible_engineer_names()` matches on email or gmail and NOTHING ELSE.
--     A User Master row whose address has gone stale (or who signs in with a
--     different one) resolves to no row, so the tree is empty and the database
--     returns no calls at all. The screen names a team it cannot read.
--
-- So the lookup falls back to the person's NAME, from their own profile — the
-- name the User Master is keyed on everywhere else in this system. It is a
-- FALLBACK, not a widening: when the address matches, nothing changes, and the
-- name is only consulted when it resolves to no row at all.
-- ===========================================================================

create or replace function public.visible_engineer_names()
returns setof text language sql stable security definer set search_path = public as $$
  with recursive me as (
    select name from public.user_directory
     where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
  ),
  -- Only when the address finds nobody: the name on the caller's own profile.
  me_by_name as (
    select d.name from public.user_directory d
      join public.profiles p on p.id = auth.uid()
     where not exists (select 1 from me)
       and lower(btrim(d.name)) = lower(btrim(coalesce(p.full_name, '')))
       and btrim(coalesce(p.full_name, '')) <> ''
  ),
  root as (
    select name from me
    union
    select name from me_by_name
  ),
  tree as (
    select d.name from public.user_directory d where d.name in (select name from root)
    union
    select c.name from public.user_directory c
      join tree t
        on lower(c.reporting_manager) = lower(t.name)
        or lower(c.regional_manager)  = lower(t.name)
  )
  select name from tree where coalesce(name,'') <> '';
$$;

-- ------------------------------------------------------------------------
-- 0212_visible_engineers_no_blank_match.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A BLANK NAME IS NOT A MANAGER, AND MUST NOT MATCH ONE.
--
-- Reported from use (2026-09-18): "Why is a Regional Manager able to see
-- everyone's call and every spare request?"
--
-- `visible_engineer_names()` walks the directory DOWNWARDS from the caller —
-- everyone whose reporting_manager or regional_manager is the caller, then
-- everyone under them. The walk matched on name equality with nothing
-- excluding the EMPTY STRING from either side. So when the caller's own row in
-- `user_directory` has a blank `name` — which is what a partial import, a
-- trimmed cell or a directory row keyed only by email leaves — the recursion
-- asks for everyone whose manager is '' and gets every row that has no manager
-- recorded.
--
-- MEASURED, not reasoned about. A regional manager with three of his own and
-- five strangers, run before and after:
--
--   name present : ENG ONE, ENG TWO, ENG THREE, HARSH RM      <- correct
--   name blank   : ENG TWO, ENG THREE, STRANGER A, STRANGER B <- wrong BOTH ways
--
-- Note the second line carefully: it is not "sees everyone", it is worse than
-- that to diagnose. Two strangers are pulled IN, and one of his own team is
-- pushed OUT — because the root no longer matches the people who name him.
-- Nobody looking at that list could tell it was a fault rather than a region.
--
-- THE FIX IS ONE CONDITION, AND IT ONLY EVER NARROWS. A tree node with a blank
-- name stops recursing. A caller whose directory row has no name now sees no
-- team at all, which is the honest answer: the directory does not say who they
-- are, so it cannot say who reports to them. They still see their own calls
-- through the other branches of the read policy, which match on user id and
-- email rather than on name.
--
-- The comparison itself is left EXACTLY as it was. Adding btrim() to both
-- sides would also make ' HARSH RM ' match 'HARSH RM', and that is a WIDENING
-- — more rows visible, not fewer. It may well be wanted, but it is a different
-- decision from closing a leak and does not belong in the same change.
-- ===========================================================================
create or replace function public.visible_engineer_names()
returns setof text
language sql
stable
security definer
set search_path to 'public'
as $$
  with recursive me as (
    select name from public.user_directory
     where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
  ),
  -- Only when the address finds nobody: the name on the caller's own profile.
  me_by_name as (
    select d.name from public.user_directory d
      join public.profiles p on p.id = auth.uid()
     where not exists (select 1 from me)
       and lower(btrim(d.name)) = lower(btrim(coalesce(p.full_name, '')))
       and btrim(coalesce(p.full_name, '')) <> ''
  ),
  root as (
    select name from me
    union
    select name from me_by_name
  ),
  tree as (
    select d.name from public.user_directory d where d.name in (select name from root)
    union
    select c.name from public.user_directory c
      join tree t
        -- THE GUARD. Without it, '' = '' and every unmanaged row joins the team.
        on btrim(coalesce(t.name, '')) <> ''
       and (lower(c.reporting_manager) = lower(t.name)
         or lower(c.regional_manager)  = lower(t.name))
  )
  select name from tree where coalesce(name,'') <> '';
$$;

-- ------------------------------------------------------------------------
-- 0257_directory_rename_carries_the_team.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- CORRECTING A MANAGER'S NAME NO LONGER EMPTIES THEIR TEAM (finding 23).
--
-- The reporting tree is built from NAMES: `user_directory.reporting_manager`
-- and `.regional_manager` hold a manager's name, and `visible_engineer_names()`
-- matches them against `name`, case-insensitively. Nothing carried a change of
-- that name, so correcting a spelling on User Master left every engineer
-- pointing at a name nobody holds any more. Measured: the Reporting Manager
-- saw 3 people before one edit and 1 after — themselves — and lost every
-- call, spare request, visit and review their team's names scope, with no
-- error anywhere.
--
-- THE USER'S DECISION (2026-09-30): "Carry the rename". When a directory
-- row's name changes, every row naming the OLD name as its Reporting or
-- Regional Manager is updated to the NEW name in the same statement.
--
-- THREE LIMITS, each on purpose:
--
--   1. A BLANK OLD NAME CARRIES NOTHING. Naming somebody who had no name would
--      otherwise rewrite every row with no manager recorded — the blank-name
--      trap 0212 closed on the read side.
--   2. IF ANOTHER ROW STILL CARRIES THE OLD NAME, NOTHING IS CARRIED. Two
--      directory rows with one name are two people the tree already cannot
--      tell apart; the rows naming it still resolve to the one who kept it,
--      and moving them to the renamed person would be a guess.
--   3. A CHANGE OF CASE ONLY CARRIES NOTHING. The tree compares with lower(),
--      so "ravi kumar" -> "Ravi Kumar" breaks nothing and rewriting the team
--      would be writes for no reason.
--
-- IT MATCHES EXACTLY AS THE TREE DOES — lower(), no trimming. A btrim() here
-- would also rewrite a row naming ' Ravi ', which the tree does NOT count as
-- Ravi's today, and so WIDEN a team; this migration only keeps one.
--
-- THE RECORDS filed under the old name — calls, requests, spares,
-- consumption, hand stock — are 0259's, a second trigger: the user first chose
-- to leave them, then (same day, once told that call visibility is by name
-- too) "Rename existing records".
--
-- SECURITY INVOKER. Only an ADMINISTRATOR can change a name at all —
-- `user_directory_address_guard` refuses anybody else any column but the
-- address — and an administrator may write every row, so the cascade can never
-- be partly refused. Running as the caller also stamps sys_updated_by with the
-- person who renamed.
-- ===========================================================================

create or replace function public.user_directory_carry_rename()
returns trigger language plpgsql set search_path = public as $$
begin
  if btrim(coalesce(old.name, '')) = ''
     or lower(old.name) = lower(coalesce(new.name, '')) then
    return null;
  end if;
  if exists (select 1 from public.user_directory d
              where d.id <> new.id and lower(d.name) = lower(old.name)) then
    return null;
  end if;

  update public.user_directory d
     set reporting_manager = new.name
   where d.id <> new.id
     and lower(d.reporting_manager) = lower(old.name);

  update public.user_directory d
     set regional_manager = new.name
   where d.id <> new.id
     and lower(d.regional_manager) = lower(old.name);

  return null;
end $$;

comment on function public.user_directory_carry_rename() is
  'When a User Master name changes, rows naming the old name as Reporting or Regional Manager follow it (finding 23). Not when the old name was blank, is still held by another row, or only its case changed.';

drop trigger if exists user_directory_carry_rename on public.user_directory;
create trigger user_directory_carry_rename
  after update of name on public.user_directory
  for each row execute function public.user_directory_carry_rename();

-- ------------------------------------------------------------------------
-- 0259_directory_rename_carries_the_records.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A RENAME ALSO CARRIES THE PERSON'S RECORDS (finding 23, second half).
--
-- 0257 moves the TEAM: the rows that name a renamed person as their manager.
-- It left work already filed under the old name where it was, and that is not
-- only hand stock. Who may SEE a call is decided by the allottee's NAME
-- (`calls_scoped_read`: lower(trim(allocated_to)) in visible_engineer_names()),
-- and so is a spare request, a consumption line, a stock transfer and the rest
-- -- so after a rename the person, and their manager, stopped seeing
-- everything allotted to the old spelling, and their hand stock split into two
-- balances.
--
-- THE USER'S DECISION (2026-09-30): "Rename existing records".
--
-- WHAT MOVES — every column that decides whose a record IS, matched exactly as
-- its own read policy matches it (lower(btrim()) on both sides):
--
--   calls ............ field_calls / installation_calls / pm_calls.allocated_to
--   requests ......... call_requests.engineer, pending_registrations.engineer
--   spares ........... spare_requests.engineer, spare_dispatches.engineer
--   consumption ...... spare_consumption.engineer, spare_consumption_history.engineer
--   hand stock ....... handstock_opening.engineer, spare_issue_history.engineer,
--                      material_returns.engineer,
--                      stock_transfers.from_engineer / .to_engineer
--   who looks after .. parties.service_engineer, products.service_engineer
--
-- The last two are not history but POINTERS: a new call's Allocated To is
-- filled from the customer's Service Engineer, so a stale name there would
-- allot every new call to a name nobody can see — the same fault again.
--
-- WHAT DOES NOT MOVE, on purpose: who DID something — rm_by, dispatched_by,
-- received_by, recorded_by, a visit report's engineer, a feedback's engineer,
-- the sale's engineer, and spare_request_engineer_log (a log of changes of
-- engineer, which a rename must not rewrite). Those are signatures on a
-- record, and nothing's visibility or stock is decided by them.
--
-- THE SAME THREE LIMITS AS 0257: nothing moves when the old name was blank,
-- when only its case or surrounding space changed (every reader compares
-- lower(btrim())), or when another User Master row still carries the old name
-- — two people with one name, whose records cannot be told apart here.
--
-- GUARDS. Four triggers refuse or react to exactly this change: a consumption
-- line's engineer cannot change, a dispatched request's engineer cannot
-- change, an answered call request is frozen, and a changed allottee sends
-- "Call allotted to you". Each is taught to recognise THIS rename (0260,
-- 0261, 0262) by a TICKET filed here, in the same pattern as rename_part()
-- (0196): a row keyed on the transaction, in a table with row-level security
-- on, no policy and no grants, so only this definer function can write one.
-- A set_config flag would be forgeable by anybody who can update a row.
-- Every other guard still runs; the renamer is an administrator (only an
-- administrator can change a name — user_directory_address_guard), which is
-- what those guards already let through.
--
-- EACH TABLE IS GUARDED BY to_regclass() and updated by dynamic SQL, so a
-- project missing a module still renames what it has. The audit triggers on
-- the quality tables record every row moved.
-- ===========================================================================

create table if not exists public.engineer_rename_ticket (
  txid     bigint primary key,
  old_key  text not null,
  new_name text not null,
  at       timestamptz not null default now()
);
alter table public.engineer_rename_ticket enable row level security;
revoke all on public.engineer_rename_ticket from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.engineer_rename_ticket from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on public.engineer_rename_ticket from anon';
  end if;
end $$;
-- THE FIVE SYSTEM COLUMNS (0244), like every other table. Where 0244 has
-- already run -- the live project, a build in migration order -- they are
-- attached here; on a fresh apply of the bundles, `sys_columns` runs last and
-- attaches them to every table then.
do $$ begin
  if to_regprocedure('public.sys_columns_attach(regclass)') is not null then
    perform public.sys_columns_attach('public.engineer_rename_ticket'::regclass);
  end if;
end $$;

comment on table public.engineer_rename_ticket is
  'The capability that lets a User Master rename move the records filed under the old name past the guards that refuse a change of engineer (0259). RLS on with NO policy and no grants: only the definer-owned rename trigger writes one, keyed on its own transaction.';

-- Is THIS transaction renaming `p_old` to `p_new`? Asked by the guards. It
-- answers only about the caller's own transaction, so it discloses nothing.
create or replace function public.engineer_rename_in_progress(p_old text, p_new text)
returns boolean language plpgsql stable security definer set search_path = public as $$
begin
  return exists (
    select 1 from public.engineer_rename_ticket t
     where t.txid = txid_current()
       and t.old_key = lower(btrim(coalesce(p_old, '')))
       and t.new_name = coalesce(p_new, ''));
end $$;
revoke execute on function public.engineer_rename_in_progress(text, text) from public, anon;
grant  execute on function public.engineer_rename_in_progress(text, text) to authenticated;

create or replace function public.user_directory_carry_rename_records()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  old_key text := lower(btrim(coalesce(old.name, '')));
  new_nm  text := btrim(coalesce(new.name, ''));
  target  record;
begin
  if old_key = '' or new_nm = '' or old_key = lower(new_nm) then
    return null;
  end if;
  if exists (select 1 from public.user_directory d
              where d.id <> new.id and lower(btrim(d.name)) = old_key) then
    return null;
  end if;

  insert into public.engineer_rename_ticket (txid, old_key, new_name)
  values (txid_current(), old_key, new_nm)
  on conflict (txid) do update set old_key = excluded.old_key,
                                   new_name = excluded.new_name, at = now();

  for target in
    select * from (values
      ('field_calls', 'allocated_to'), ('installation_calls', 'allocated_to'), ('pm_calls', 'allocated_to'),
      ('call_requests', 'engineer'), ('pending_registrations', 'engineer'),
      ('spare_requests', 'engineer'), ('spare_dispatches', 'engineer'),
      ('spare_consumption', 'engineer'), ('spare_consumption_history', 'engineer'),
      ('handstock_opening', 'engineer'), ('spare_issue_history', 'engineer'),
      ('material_returns', 'engineer'),
      ('stock_transfers', 'from_engineer'), ('stock_transfers', 'to_engineer'),
      ('parties', 'service_engineer'), ('products', 'service_engineer')
    ) v(tbl, col)
  loop
    if to_regclass('public.' || target.tbl) is not null
       and exists (select 1 from information_schema.columns c
                    where c.table_schema = 'public' and c.table_name = target.tbl
                      and c.column_name = target.col) then
      execute format('update public.%I set %I = $1 where lower(btrim(%I)) = $2',
                     target.tbl, target.col, target.col)
        using new_nm, old_key;
    end if;
  end loop;

  delete from public.engineer_rename_ticket where txid = txid_current();
  return null;
end $$;
revoke execute on function public.user_directory_carry_rename_records() from public, anon, authenticated;

comment on function public.user_directory_carry_rename_records() is
  'When a User Master name changes, the records filed under the old name -- calls allotted to it, requests, spares, consumption, hand stock, and the Party Master / Product Database service engineer -- follow it (0259, finding 23). Not when the old name was blank, only its case or spacing changed, or another row still holds it.';

drop trigger if exists user_directory_carry_rename_records on public.user_directory;
create trigger user_directory_carry_rename_records
  after update of name on public.user_directory
  for each row execute function public.user_directory_carry_rename_records();

-- ------------------------------------------------------------------------
-- 0267_rename_carries_adjustments.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- A USER MASTER RENAME CARRIES THE HAND STOCK ADJUSTMENTS TOO.
--
-- 0259 (finding 23) moves every record filed under a person's old name to the
-- new one when their User Master name is corrected -- calls, requests, spares,
-- consumption, hand stock. 0266 adds a table filed by engineer name,
-- `handstock_adjustments`; without joining that list, an engineer whose name
-- was corrected would keep their stock but lose their adjustments, and the
-- balance would split in two. The function below is 0259's VERBATIM with that
-- one table added to the list. The table's absence is tolerated exactly as
-- 0259 tolerates any other (to_regclass), so this can run before 0266.
-- ===========================================================================

create or replace function public.user_directory_carry_rename_records()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  old_key text := lower(btrim(coalesce(old.name, '')));
  new_nm  text := btrim(coalesce(new.name, ''));
  target  record;
begin
  if old_key = '' or new_nm = '' or old_key = lower(new_nm) then
    return null;
  end if;
  if exists (select 1 from public.user_directory d
              where d.id <> new.id and lower(btrim(d.name)) = old_key) then
    return null;
  end if;

  insert into public.engineer_rename_ticket (txid, old_key, new_name)
  values (txid_current(), old_key, new_nm)
  on conflict (txid) do update set old_key = excluded.old_key,
                                   new_name = excluded.new_name, at = now();

  for target in
    select * from (values
      ('field_calls', 'allocated_to'), ('installation_calls', 'allocated_to'), ('pm_calls', 'allocated_to'),
      ('call_requests', 'engineer'), ('pending_registrations', 'engineer'),
      ('spare_requests', 'engineer'), ('spare_dispatches', 'engineer'),
      ('spare_consumption', 'engineer'), ('spare_consumption_history', 'engineer'),
      ('handstock_opening', 'engineer'), ('spare_issue_history', 'engineer'),
      ('material_returns', 'engineer'), ('handstock_adjustments', 'engineer'),
      ('stock_transfers', 'from_engineer'), ('stock_transfers', 'to_engineer'),
      ('parties', 'service_engineer'), ('products', 'service_engineer')
    ) v(tbl, col)
  loop
    if to_regclass('public.' || target.tbl) is not null
       and exists (select 1 from information_schema.columns c
                    where c.table_schema = 'public' and c.table_name = target.tbl
                      and c.column_name = target.col) then
      execute format('update public.%I set %I = $1 where lower(btrim(%I)) = $2',
                     target.tbl, target.col, target.col)
        using new_nm, old_key;
    end if;
  end loop;

  delete from public.engineer_rename_ticket where txid = txid_current();
  return null;
end $$;
revoke execute on function public.user_directory_carry_rename_records() from public, anon, authenticated;

-- ------------------------------------------------------------------------
-- 0346_rename_carries_pending_indoor_dc.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- 0346 — A USER MASTER RENAME CARRIES THE INDOOR DCs WAITING FOR THAT PERSON
--        (second re-review, 2026-10-03: D-144)
--
-- user_directory_carry_rename_records() (0259, 0267) moves every record filed
-- under a person's old name to the new one. indoor_dcs.authorised_by_name was
-- not on its list, and it is how an Indoor DC finds its approver (0327:
-- indoor_dc_may_approve, the read policy and approve_indoor_dc all match it).
-- Measured: after the authoriser was renamed they saw 0 DCs and could not reach
-- the one naming them, which stayed Pending approval with its units held.
--
-- ONLY A PENDING DC MOVES. On an approved, rejected or "issued before
-- approval" DC the name is what the printed document says authorised it, and
-- re-printing it must say the same thing.
--
-- The function below is 0267's VERBATIM with that one statement added, read
-- from a database built from every migration. Same module (user_directory),
-- after 0267, so a replay of user_directory.sql ends on this definition.
-- ===========================================================================

create or replace function public.user_directory_carry_rename_records()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  old_key text := lower(btrim(coalesce(old.name, '')));
  new_nm  text := btrim(coalesce(new.name, ''));
  target  record;
begin
  if old_key = '' or new_nm = '' or old_key = lower(new_nm) then
    return null;
  end if;
  if exists (select 1 from public.user_directory d
              where d.id <> new.id and lower(btrim(d.name)) = old_key) then
    return null;
  end if;

  insert into public.engineer_rename_ticket (txid, old_key, new_name)
  values (txid_current(), old_key, new_nm)
  on conflict (txid) do update set old_key = excluded.old_key,
                                   new_name = excluded.new_name, at = now();

  for target in
    select * from (values
      ('field_calls', 'allocated_to'), ('installation_calls', 'allocated_to'), ('pm_calls', 'allocated_to'),
      ('call_requests', 'engineer'), ('pending_registrations', 'engineer'),
      ('spare_requests', 'engineer'), ('spare_dispatches', 'engineer'),
      ('spare_consumption', 'engineer'), ('spare_consumption_history', 'engineer'),
      ('handstock_opening', 'engineer'), ('spare_issue_history', 'engineer'),
      ('material_returns', 'engineer'), ('handstock_adjustments', 'engineer'),
      ('stock_transfers', 'from_engineer'), ('stock_transfers', 'to_engineer'),
      ('parties', 'service_engineer'), ('products', 'service_engineer')
    ) v(tbl, col)
  loop
    if to_regclass('public.' || target.tbl) is not null
       and exists (select 1 from information_schema.columns c
                    where c.table_schema = 'public' and c.table_name = target.tbl
                      and c.column_name = target.col) then
      execute format('update public.%I set %I = $1 where lower(btrim(%I)) = $2',
                     target.tbl, target.col, target.col)
        using new_nm, old_key;
    end if;
  end loop;

  -- An Indoor DC still WAITING for its authoriser follows the rename (D-144):
  -- the approver finds the DC by this name, so without it the DC stays Pending
  -- approval with its units held and nobody able to reach it. A DC already
  -- approved, rejected or issued before approval keeps the name it was printed
  -- with -- who authorised a document is history, as dispatched_by is (0259).
  if to_regclass('public.indoor_dcs') is not null then
    update public.indoor_dcs set authorised_by_name = new_nm
     where lower(btrim(authorised_by_name)) = old_key
       and approval_status = 'Pending approval';
  end if;

  delete from public.engineer_rename_ticket where txid = txid_current();
  return null;
end $$;
revoke execute on function public.user_directory_carry_rename_records() from public, anon, authenticated;

-- ------------------------------------------------------------------------
-- 0408_user_tags.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- 0408 -- TAGS ON THE USER MASTER (the user, 2026-10-10: "in User Master, Add
-- provision for Tags..").
--
-- Asked and answered:
--   * What for: "I need to add People to list in FFR - CAPA Responsibility".
--     A person tagged "CAPA Responsibility" is offered in that picker on the
--     Field Failure Register, beside "No closed in FFR".
--   * Values: FREE TEXT, several per person. No master list.
--   * Where: the person's form, a table column, a filter at the top and a
--     bulk add / remove.
--
-- A text[] on `user_directory`, read by everyone signed in like the rest of
-- the row -- a tag is not private. Written under the directory's own policies
-- (users.manage.details); nothing new is granted.
--
-- TIDIED IN THE DATABASE so every writer -- the table edit, the form, the bulk
-- action, an import -- stores the same shape: each tag trimmed, blanks
-- dropped, and a tag repeated in another case kept ONCE, in the spelling that
-- came first. A free-text tag typed "CAPA responsibility" and "CAPA
-- Responsibility" on one person is one tag, not two. Case is otherwise kept as
-- typed, and comparing is done case-blind by whoever reads it.
-- ===========================================================================

alter table public.user_directory add column if not exists tags text[] not null default '{}';
create index if not exists user_directory_tags_idx on public.user_directory using gin (tags);

create or replace function public.user_directory_tags_tidy()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.tags := coalesce((
    select array_agg(t order by first_at)
      from (select distinct on (lower(btrim(x))) btrim(x) as t, ord as first_at
              from unnest(coalesce(new.tags, '{}'::text[])) with ordinality u(x, ord)
             where btrim(coalesce(x, '')) <> ''
             order by lower(btrim(x)), ord) s), '{}'::text[]);
  return new;
end $$;

drop trigger if exists user_directory_tags_tidy on public.user_directory;
create trigger user_directory_tags_tidy
  before insert or update of tags on public.user_directory
  for each row execute function public.user_directory_tags_tidy();

comment on column public.user_directory.tags is
  'Free-text tags, several per person (0408). "CAPA Responsibility" puts the person on the Field Failure Register''s CAPA Responsibility list. Trimmed, blanks dropped, one per spelling case-blind.';

-- ------------------------------------------------------------------------
-- 0122_user_directory_replay_tail.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- user_directory.sql must leave the directory's policies where the schema
-- leaves them.
--
-- 0004 creates `ud_admin_write` — FOR ALL, using is_admin() — and 0008 DROPS
-- it, because rbac replaced it with the narrower ud_read / ud_write pair plus
-- 0030's address rule for dispatch. Since rbac runs after user_directory, a
-- database built from all.sql has no ud_admin_write, which is the intended
-- state; but replaying user_directory.sql on its own put it back, and policies
-- are OR'd, so the narrowing went away with no error and no warning.
--
-- Dropping it again here is 0008's word, applied last. On a fresh apply the
-- policy has just been created a few statements above and is dropped again
-- immediately, which is exactly what all.sql does anyway.
-- ===========================================================================

drop policy if exists ud_admin_write on public.user_directory;

commit;
