-- ===========================================================================
-- RITHI CRM — User Directory: apply bundle
--
-- The engineer directory and the reporting-tree helpers that call and
-- spare visibility are scoped by.
--
-- GENERATED by scripts/build-apply-bundles.mjs — do not edit by hand.
-- Edit the migrations below and re-run the generator.
--
-- Carries, in order:
--   0004_user_directory.sql
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
-- ===========================================================================

-- Stop with a readable list rather than a cryptic error partway through.
do $$
declare missing text[] := '{}';
begin
  if to_regclass('public.profiles') is null then
    missing := array_append(missing, 'the profiles table — 0001_init.sql');
  end if;
  if array_length(missing, 1) is not null then
    raise exception E'Apply these first, then re-run this bundle:\n  - %',
      array_to_string(missing, E'\n  - ');
  end if;
end $$;


begin;

-- ------------------------------------------------------------------------
-- 0004_user_directory.sql
-- ------------------------------------------------------------------------

-- ===========================================================================
-- User Master → user_directory: the engineer/manager directory (names +
-- reporting hierarchy) that drives who-sees-what. Separate from auth logins
-- (profiles): a person is scoped by matching their login email to a directory
-- row, then by the RM/RGM tree (by name). Admins (profiles.role='admin') see all.
-- ===========================================================================

create table if not exists public.user_directory (
  id                 bigint generated always as identity primary key,
  name               text not null,               -- User Name (matches "Call Allocated To")
  email              text default '',
  gmail              text default '',
  designation        text default '',
  reporting_manager  text default '',             -- RM name
  regional_manager   text default '',             -- RGM name
  region             text default '',
  validity           boolean not null default true,
  extra              jsonb not null default '{}'
);
create index if not exists user_directory_email_idx on public.user_directory (lower(email));
create index if not exists user_directory_gmail_idx on public.user_directory (lower(gmail));
create index if not exists user_directory_name_idx  on public.user_directory (lower(name));

alter table public.user_directory enable row level security;
drop policy if exists ud_read on public.user_directory;
create policy ud_read on public.user_directory for select using (auth.role() = 'authenticated');
drop policy if exists ud_admin_write on public.user_directory;
create policy ud_admin_write on public.user_directory for all using (public.is_admin()) with check (public.is_admin());

-- The signed-in user's directory name (by login email or gmail).
create or replace function public.my_dir_name()
returns text language sql stable security definer set search_path = public as $$
  select name from public.user_directory
   where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
   limit 1;
$$;

-- Names the current user may see: their own + everyone in their reporting
-- sub-tree (recursive over reporting_manager / regional_manager, by name).
create or replace function public.visible_engineer_names()
returns setof text language sql stable security definer set search_path = public as $$
  with recursive me as (
    select name from public.user_directory
     where lower(email) = lower(auth.email()) or lower(gmail) = lower(auth.email())
  ),
  tree as (
    select d.name from public.user_directory d where d.name in (select name from me)
    union
    select c.name from public.user_directory c
      join tree t
        on lower(c.reporting_manager) = lower(t.name)
        or lower(c.regional_manager)  = lower(t.name)
  )
  select name from tree where coalesce(name,'') <> '';
$$;

-- can_see_call() already uses visible_engineer_names(), so call scoping now
-- follows the directory automatically (admins still bypass via is_admin()).

commit;
