-- ---------------------------------------------------------------------------
-- 0014 — Master value lists as their own maintained tables.
--
-- Each master ("200 All Masters" in the workbook: Call Type, Standard
-- Complaint, Call Pending Reason, Call Cancel Reason, Feedback, Spare Approval
-- Reason) becomes a list that admins add to and remove from in the app. The
-- rows still live in `masters` — one store the dropdown reader already knows —
-- and `master_lists` is the registry that gives each list its own table: its
-- label, what one row is called, and any extra columns that list carries
-- (Spare Approval Reason has Stage + Status, kept in `masters.extra`).
--
-- Writes are already gated by masters.edit (0008_rbac_enforcement.sql).
-- ---------------------------------------------------------------------------

-- Provenance columns, as the workbook carries them.
alter table public.masters add column if not exists added_on date;
alter table public.masters add column if not exists added_by text default '';

-- Standard Complaint arrived under two names; settle on `complaint`
-- (listMaster() already reads them as one) so the list has a single table.
update public.masters set name = 'complaint' where name = 'standardComplaint';

-- One row per value per list — a re-seed or a double-tap on Add is a no-op.
-- The Stage discriminator keeps the same reason on two approval stages.
delete from public.masters a
 using public.masters b
 where a.name = b.name
   and a.value = b.value
   and coalesce(a.extra->>'stage','') = coalesce(b.extra->>'stage','')
   and a.id > b.id;
create unique index if not exists masters_name_value_idx
  on public.masters (name, value, (coalesce(extra->>'stage','')));

-- The registry: which lists exist, and what a row of each looks like.
create table if not exists public.master_lists (
  key         text primary key,
  label       text not null,
  value_label text not null default 'Value',
  -- [{ "key": "stage", "label": "Stage" }, ...] — extra columns in masters.extra
  columns     jsonb not null default '[]',
  sort_order  int  not null default 100,
  active      boolean not null default true,
  updated_at  timestamptz not null default now()
);
alter table public.master_lists enable row level security;
drop policy if exists master_lists_read on public.master_lists;
create policy master_lists_read on public.master_lists for select
  using (auth.role() = 'authenticated');
drop policy if exists master_lists_write on public.master_lists;
create policy master_lists_write on public.master_lists for all
  using (public.has_perm('masters.edit')) with check (public.has_perm('masters.edit'));

insert into public.master_lists (key, label, value_label, columns, sort_order) values
  ('calltype', 'Call Type', 'Call Type', '[]'::jsonb, 10),
  ('complaint', 'Standard Complaint', 'Complaint Name', '[]'::jsonb, 20),
  ('pendingreason', 'Call Pending Reason', 'Reason', '[]'::jsonb, 30),
  ('cancelreason', 'Call Cancel Reason', 'Reason', '[]'::jsonb, 40),
  ('feedbackrating', 'Feedback Rating', 'Rating', '[]'::jsonb, 50),
  ('orapproval', 'Spare Approval Reason', 'Reason', '[{"key": "stage", "label": "Stage"}, {"key": "status", "label": "Status"}]'::jsonb, 60)
on conflict (key) do update set
  label = excluded.label, value_label = excluded.value_label,
  columns = excluded.columns, sort_order = excluded.sort_order, updated_at = now();

-- The workbook's values, so a fresh project starts with the real lists.
-- Anything an admin has since added or removed is left alone.
insert into public.masters (name, value, extra, added_on, added_by) values
  ('calltype', 'FIELD', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'INSTALLATION CALL', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'P M VISIT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'SW UPGRADATION', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'FSCA', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'DEMO', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'FIELD & P M VISIT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('calltype', 'FSCA & P M VISIT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('complaint', '0 NURSE CALL- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '1 OBSTRUCTED INSPIRATORY/ EXPIRATORY BREATHING TUBE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '1 PRESSURE GRAPH DISPLAY GOES TO –VE DURING EXPIRATION - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '1 PRESSURE IN EXCESS. - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '1 STANDBY MODE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '1 STANDY MODE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '10 BATTERY LOW. BATTERY WILL SOON BE EXHAUSTED. - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '10 EFLOW SENSOR FAIL - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '10 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '10 PPEAK >> P HIGH - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '10 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '100 EXCESSIVE INTERNAL BATTERY TEMPERATURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '100 LEFT LOUDSPEAKER INOPERANT. CONTACT THE TECHNICAL DEPARTMENT - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '101 BACKLIGHT FAILURE\NCONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '101 EXCESSIVE INTERCHANGEABLE BATTERY TEMPERATURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '102 EXCESSIVE PCB SUPPLY TEMPERATURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '102 VTI HIGH - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '103 INTERNAL BATTERY ERROR DETECTED- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '103 INVERSE I/E RATIO - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '104 100% FIO2, 2 MINUTES - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '104 INTERCHANGEABLE BATTERY ERROR DETECTED- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '105 INTERNAL BATTERY DEFECTIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '105 LOW INFLATION FLOW IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '106 INTERCHANGEABLE BATTERY DEFECTIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '106 SUSTAINED EXHALATION IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '107 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '107 NEBULIZATION IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '108 EXTERNAL PRESSURE CURVE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '108 TELE-INSPIRATORY OCCLUSION IN PROGRESS- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '109 TELE-EXPIRATORY OCCLUSION IN PROGRESS- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '11 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '11 PATIENT DISCONNECT - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '11 PEEP GREATER THAN SET PEEP + 5 CMH?O - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '11 PRESSURE SENSOR FAIL - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '110 100% 02 TIME > 3 MIN- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '110 APPARATUS IN STAND-BY MODE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '111 HIGH TURBINE TEMPERATURE VENTILATION COULD STOP.- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '111 MINOR FAILURE DETECTED. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '112 02 SENSOR DISABLED. USE AN EXTERNAL O2 MONITOR.- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '112 REPLACE OXYGEN SENSOR SOON - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '113 ADJUST EXPIRATORY TRIGGER - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '113 SLIGHT PATIENT CIRCUIT LEAK DETECTED DURING AUTOMATIC TESTS- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '114 RCSTATS MEASUREMENT IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '114 REBREATHING DETECTED- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '115 DC INPUT VOLTAGE ABOVE 30 V- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '115 P0.1 MEASUREMENT IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '116 MEASUREMENT OF RECRUITMENT IN PROGRESS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 APNEA - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 HIGH PRESSURE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 REAL O2% COMES ONLY 40% – 50% - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '12 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '13 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '13 HIGH PEEP - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '13 PATIENT DISCONNECTION - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '13 RUN FULL SELF- TESTS - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '13 SCREEN FAILURE CHECK THE VENTILATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 PRESSURE SENSOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 RUN LEAK TESTS - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 SCREEN FAILURE CHECK THE VENTILATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 SETTINGS INOPERATIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '14 WRONG EXPIRED VT DISPLAY - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 ALARM THRESHOLDS INOPERATIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 LOW MINUTE VOLUME - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 LOW PRESSURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 PSIMV MODE ONLY APNEA - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '15 SCREEN FAILURE CHECK THE VENTILATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 HIGH PRESSURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 HIGH RESPIRATORY RATE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 INCORRECT SETTINGS - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 LOW VMI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '16 RR DISPLAY LESS THAN 1 - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '17 CAN’T CHANGE PARAMETERS VALUES ALONE - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '17 INCORRECT SETTINGS - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '17 LOW VME- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '17 OXYGEN SUPPLY FAILURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '17 PPEAK >> PHIGH - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '18 AIR SUPPLY FAILURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '18 EXPIRED VT BECOMES 00 DURING TRIGGERING - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '18 INCORRECT ALARM SETTINGS - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '18 LOW FREQUENCY- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '18 PPLAT HIGH - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '19 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '19 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '19 LOW FIO? - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '19 LOW MVI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '19 PEEP GREATER THAN SET PEEP + 5 CMH2O - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 AUTO TRIGGER - WITH PEEP CONDITION - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 EXPIRATION BLOCKED - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 EXPIRATORY BRANCH MIGHT BE OBSTRUCTED - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 PARTIALLY OBSTRUCTED. EXPIRATORY BRANCH - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 SWITCHING OFF THE UNIT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '2 VENTILATOR SHUTDOWN- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 APNEA VENTILATION - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 DELIVERED GASES TOO HOT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 HIGH FIO? - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 LOW MVE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '20 SET PARAMETERS VALUES SUDDENLY DISPLAY ABRUPTLY - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 APNEA - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 HIGH MINUTE VOLUME - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 LOW FREQUENCY - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 O2 SUPPLY PRESSURE TOO LOW - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 PEEP GREATER THAN PEEP SET- POINT + 5 CMH2O- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '21 WRITE DEFAULT DISPLAY - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 ALL DISPLAY BLANKS - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 BATTERY LOW. CONNECT TO EXTERNAL SUPPLY - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 HIGH FREQUENCY- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 O2 SUPPLY PRESSURE TOO HIGH - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 PERFORM V MAINTENANCE CALIBRATIONS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '22 SAFETY VENTILATION RECOMMEND SWITCHING VENTILATOR- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 DELIVERED GASES TOO HOT - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 HIGH VMI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 LOW /HIGH INSPIRED VT - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 PERFORM M MAINTENANCE CALIBRATIONS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '23 VENTILATOR SAFETY SYSTEM IN- OPERANT. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '24 - 25 RUN FULL SELF-TESTS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '24 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '24 HIGH VME- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '24 PEEP GREATER THAN SET PEEP + 5CMH2O - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '24 SOFTWARE VERSIONS NOT COMPATIBLE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '25 FIO2 LOW- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '25 HIGH RESPIRATORY RATE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '25 LOST CONNECTION IN STAND-BY. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '26 FIO2 HIGH- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '26 HIGH MVI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '26 LOST CONNECTION IN VENTILATION. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '26 RUN LEAK TESTS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '27 COOLING FAN FAILURE. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '27 HIGH MVE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '27 LOW MINUTE VOLUME - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '28 BATTERIES EMPTY CONNECT AC POWER- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '28 HIGH RESPIRATORY RATE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '28 LOW FIO2 - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '28 LOW VTE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '29 BATTERIES NEARLY DISCHARGED CONNECT AC POWER- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '29 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '29 HIGH FIO2 - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '29 HIGH VTE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '29 INSPIRATORY HOT-WIRE FLOW SENSOR FAILURE REPLACE THE SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 EXPIRATORY BRANCH MIGHT BE OBSTRUCTED- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 EXPIRATORY VALVE FAILURE. CHECK APPARATUS ASSEMBLY. - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 O2% DISPLAY SHOWS LESS THAN 100% AT ONLY O2 SUPPLY CONDITION - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 PROGRAM 1 ACTIVATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '3 VENTILATOR IN- OPERANT. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '30 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '30 FAILURE, CONNECT TO EXTERNAL SOURCE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '30 INSPIRATORY HOT-WIRE FLOW SENSOR INOPERANT CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '30 LOW RESPIRATORY RATE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '31 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '31 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '31 INTERNAL BATTERY IN-OPERANT - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '31 INTERNAL BATTERY INOPERATIVE CONNECT AC POWER- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '31 INTERNAL FLOW SENSOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '32 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '32 INTERNAL BATTERY DISCHARGED CONNECT AC POWER- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '32 OXYGEN SUPPLY FAILURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '32 STOP OF VENTILATION REQUESTED…. RETURN IN STAND- BY - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '33 AIR SUPPLY FAILURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '33 APNEA VENTILATION- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '33 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '33 INTERNAL BATTERY UNAVAILABLE CHECK BATTERY- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '33 VENTILATOR OPERATES FROM INTERNAL BATTERY - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '34 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '34 FAILURE, CONNECT TO EXTERNAL SOURCE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '34 HIGH PRESSURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '34 VENTILATOR RECEPTION FAILURE. CONTACT AFTER- SALES - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '35 FAILURE, CONNECT TO EXTERNAL SOURCE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '35 MONITOR RECEPTION FAILURE. CONTACT AFTER- SALES - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '35 RIGHT LOUDSPEAKER IN- OPERANT. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '36 APNEA VENTILATION - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '36 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '36 FIO2 MEASUREMENT INOP. - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '36 LEFT LOUDSPEAKER IN-OPERANT. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '37 100% FIO?, 2 MINUTES - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '37 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '37 INTERNAL BATTERY UNAVAILABLE CHECK BATTERY- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '37 LOW FIO2 - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '37 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '38 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '38 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '38 HIGH FIO2 - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '38 NEBULIZATION FUNCTION ACTIVATED - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '38 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '39 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '39 EXPIRATORY HOT-WIRE FLOW SENSOR FAILURE REPLACE SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '39 PATIENT CIRCUIT LEAK DETECTED DURING AUTOMATIC TESTS- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '39 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '39 STAND BY - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 AIR AND OXYGEN SUPPLY FAILURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 HANGING AT SET PARAMETERS - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 PROGRAM 2 ACTIVATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 UNIT OUT OF SERVICE USE A BACK-UP VENTILATOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '4 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '40 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '40 EXPIRATORY HOT-WIRE FLOW SENSOR INOPERANT CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '40 INSPIRATORY PAUSE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '40 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '41 DELIVERED GASES TOO HOT - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '41 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '41 EXPIRATORY HOT-WIRE FLOW SENSOR CALIBRATION IMPOSSIBLE CHECK THE SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '41 EXPIRATORY PAUSE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '41 PATIENT CIRCUIT LEAK DETECTED DURING AUTOMATIC TESTS - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '42 ADJUST APNEA VENTILATION PARAMETERS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '42 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '42 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '42 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '43 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '43 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '43 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '43 SET ALARMS THRESHOLDS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '44 ADJUST VENTILATION PARAMETERS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '44 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '44 NO EXP FLOW RATE MEASUREMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '44 SAFETY VENTILATION SWITCH VENTILATOR RECOMMENDED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '45 1/2 LOST ADMINISTRATOR CONFIGURATION - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '45 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '45 FIO2 MEASUREMENT INOPERATIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '45 SPEAKER FAILURE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '46 2/2 LOST ADMINISTRATOR CONFIGURATION - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '46 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '46 EXPIRATORY FLOW MEASUREMENT INOPERATIVE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '47 FIO2 SENSOR INOPERATIVE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '47 HIGH MINUTE VOLUME - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '48 BATTERY LOW. RECONNECT TO EXTERNAL SUPPLY (ACKNOWLEDGEABLE ALARM) - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '48 ERROR DETECTED CONTACT TECHNICAL SUPPORT- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '48 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '48 LOW VTI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '49 LOW VTE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '49 RESTART THE AUTOMATIC TESTS - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '49 SCREEN FAILURE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '49 VENTILATOR SAFETY SYSTEM INOPERANT CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 BATTERY EMPTY. IMMINENT EXTENSION - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 HANGING AT PATIENT PARAMETERS - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 PROGRAM 1 BOOST ACTIVATION- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 UNIT OUT OF SERVICE USE A BACK-UP VENTILATOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '5 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '50 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '50 LOW VTI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '50 MONITOR SAFETY SYSTEM INOPERANT CONTACT TECH. SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '51 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '51 EXTERNAL MONITOR COMMUNICATION - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '51 HIGH VTI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '51 LOW VTE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '52 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '52 HIGH VTE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '52 SOFTWARE VERSIONS NOT COMPATIBLE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '53 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '53 FIO2 MEASUREMENT INOPERATIVE - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '53 HIGH VTI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '53 LOST CONNECT. IN STAND- BY. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '54 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '54 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '54 HIGH VTE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '54 LOST CONNECTION IN VENTILATION. CONTACT TECH. SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '55 COOLING FAN FAILURE. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '55 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '55 SPEAKER FAILURE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '56 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '56 HIGH PRESSURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '56 MIXER MANAGEMENT INOPERANT. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '56 SPEAKER FAILURE VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '57 EXPIRATORY FLOW MEASUREMENT INOPERATIVE - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '57 INTERNAL BATTERY NEARLY DISCHARGED - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '57 LOW VTE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '57 LOW VTI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '58 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '58 HIGH PRESSURE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '58 HIGH VTE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '58 LOW VTE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '59 HIGH VTI - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '59 LOW FREQUENCY- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '59 LOW VTI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 EXPIRATORY BRANCH POTENTIALLY OBSTRUCTED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 PEEP PROBLEM - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 POWER SUPPLY RECEPTION FAILURE. CONTACT TECHNICAL SERVICE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 UNIT OUT OF SERVICE USE A BACK-UP VENTILATOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '6 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '60 LOW VTE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '60 VTI < VT MINI INCREASE PS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '61 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '61 LOW FREQUENCY - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '61 PATIENT DEMAND HIGHER THAN SET PEAK FLOW - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '62 HIGH VTI- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '62 LOW VTI - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '63 HIGH VTE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '63 LIMIT PS REACHED - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '64 HIGH FREQUENCY- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '64 HIGH VTI - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '64 LIMIT PI REACHED - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '65 ADJUSTED VT LOWER THAN NEB. VOLUME - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '65 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '65 HIGH VTE - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '66 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '66 HIGH FREQUENCY - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '66 LOW RESPIRATORY RATE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '67 BATTERY CHARGER FAILURE. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '67 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '67 NON-CRITICAL ERROR VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '67 OPERATING ON INTERNAL BATTERY- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '68 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '68 INTERNAL BATTERY INOPERANT - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '68 NON-CRITICAL ERROR VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '69 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '69 SCHEDULE REPLACEMENT OF FIO2 SENSOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '69 STOP OF VENTILATION REQUESTED… RETURN IN STAND-BY - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '69 VENTILATOR OPERATES FROM INTERNAL BATTERY - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 NO OUTPUT FROM INSPIRATION LIMB - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 PATIENT DISCONNECTION - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 UNIT OUT OF SERVICE USE A BACK-UP VENTILATOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '7 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '70 CO2 MEASUREMENT INOPERANT - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '70 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '70 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '70 VENTILATOR OPERATES FROM EXTERNAL BATTERY - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '71 CO2 SENSOR INOPERANT\NREPLACE SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '71 FIO2 SENSOR TO BE REPLACED SOON - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '71 SCREEN LOCKED- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '72 CO2 APNEA - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '72 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '72 NON-CRITICAL ERROR VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '72 UNIT IN STAND-BY MODE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '73 CHECK THE ADAPTER OF THE CO2 SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '73 SCREEN INVERSION- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '73 SCREEN LOCKED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '74 CLINICIAN SCREEN- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '74 REPLACE THE ADAPTER OF THE CO2 SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '74 UNIT OUT OF SERVICE USE A BACK-UP VENTILATOR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '75 ALARM CLOCK ACTIVATED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '75 CALIBRATE THE CO2 SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '75 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '76 CO2 APNEA- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '76 CO2 CONCENTRATION OUT OF RANGE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '76 UNIT ON STAND-BY- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '77 CHECK THE ADAPTER OF THE IRMA (CO2) PROBE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '77 HIGH FICO2 - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '77 SCREEN UPSIDE DOWN- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '78 LOW ETCO2 - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '78 REPLACE THE ADAPTER OF THE IRMA(CO2) PROBE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '78 UNIT INOPERATIVE USE A BACK UP VENTILATOR- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '79 CO2 CONCENTRATION OUT OF TOLERANCE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '79 HIGH ETCO2 - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '79 NON-CRITICAL ERROR VENTILATION EFFECTIVE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 LOW PRESSURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 NO NEBULIZER OUTPUT - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 PATIENT DISCONNECTION- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '8 VENTILATOR INOP. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '80 CALIBRATE THE IRMA PROBE(CO2)- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '80 TEMPERATURE MEASUREMENT FAILURE\REPLACE CO2 SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '80 TURBINE TEMPERATURE TOO HIGH VENTILATION MAY SHUT DOWN.- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '81 ATMOSPHERIC PRESSURE MEASUREMENT FAILURE\REPLACE CO2 SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '81 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '81 IRMA(CO2) PROBE ERROR- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '81 LOW MINUTE VOLUME ALARM DISABLED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '82 CO2 MEASUREMENT INOPERATIVE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '82 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '82 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '82 IMPOSSIBLE SETTINGS. REFINE ADJUSTMENTS - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '83 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '83 EXPI. FLOW SENSOR CALIBRATION IMPOSSIBLE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '83 IRMA(CO2)PROBE: INTERNAL TEMPERATURE OUT OF TOLERANCE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '83 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '84 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '84 IRMA(CO2)PROBE: AMBIENT PRESSURE OUT OF TOLERANCE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '84 PATIENT DISCONNECTION: REDUCED SENSITIVITY- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '84 VENTILATOR OPERATES FROM INTERNAL BATTERY (ACKNOWLEDGEABLE ALARM) - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '85 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '85 ETCO2 HIGH- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '85 LOW MVI ALARM THRESHOLD DEACTIVATED- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '85 VENTILATOR OPERATES FROM EXTERNAL BATTERY (ACKNOWLEDGEABLE ALARM) - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '86 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '86 ETCO2 LOW- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '86 HIGH PRESSURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '86 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '87 LOW PRESSURE- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '87 PATIENT DEMAND HIGHER THAN SET PEAK FLOW - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '88 EXPI. FLOW SENSOR INHIBITED. USE EXTERNAL FLOW SENSOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '89 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '89 FIO2 SENSOR TO BE SOON REPLACED - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '89 O2 SENSOR INHIBITED. USE EXTERNAL O2 MONITOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '89 PATIENT ALARM INHIBITED, 2 MIN- T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 AIR AND OXYGEN SUPPLY FAILURE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 ERROR DETECTED CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 HIGH PRESSURE - ORI-G', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 HIGH PRESSURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 IFLOW SENSOR FAIL - ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '9 VENTILATION INTERRUPTED USE ANOTHER VENTILATOR - T50', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '90 BATTERY MAINTENANCE CONTACT THE TECH. DEPARTMENT- T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '90 CO2 SENSOR INHIBITED. USE EXTERNAL CO2 MONITOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '90 HIGH O2 SUPPLY PRESSURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '91 DID YOU START THE AUTOMATIC TESTS WITH THE NEBULIZER - T75', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '91 ZERO O2 SUPPLY PRESSURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '92 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '93 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '93 MINOR FAILURE DETECTED. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '94 LOW O2 SUPPLY PRESSURE- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '94 MINOR FAILURE DETECTED. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '95 MINOR FAILURE DETECTED. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '95 O2 MAXIMUM FOR 2 MIN- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '96 CONNECT CLINISOFT - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '96 LOW-PRESSURE O2- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '97 CONNECT VITAL SIGNS MONITOR - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '97 ERROR DETECTED CONTACT THE TECHNICAL DEPARTMENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '98 INTERNAL BATTERY ABSENT- T60', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '98 MINOR FAILURE DETECTED. CONTACT TECHNICAL SERVICE - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', '99 RIGHT LOUDSPEAKER INOPERANT. CONTACT THE TECHNICAL DEPARTMENT - EXT-XT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'ACCESSORY ISSUE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'ALARM ISSUE- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'AUTO TEST FAIL- HO/ORI/EO150', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'AUTOMATICALLY RESTARTING', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'BATTERY BACK UP ISSUE- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Battery Replacement13sep17', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'BREAKAGE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'BURNING ISSUE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Burnt Smell or Smoke', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'CABINET BROKEN / DAMAGE', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'CALIBRATION', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'CLINICAL ISSUE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'CUSTOMIZED SETTINGS LOST', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Dead', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'DISPLAY ISSUE- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Display Problem', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Fio2 % problem', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'FiO2 measurement inoperative', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'FIO2 STICKER MISSING', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'FIO2 VARIATION- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'HANGING- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'INSTALLATION CALL', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'LEAK/NOISE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Low Pressure', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'LOW PRESSURE- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'Mixer assemply', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'NEW COMPLAINT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'NO EXPIRATION- HO/ORI/ANA', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'NO OUTPUT PRESSURE-ASU,CPX', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'NO VENTILATION- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'O2 failure', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'ON/OFF SWITCH PROBLEM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'PEEP PROBLEM- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'PEEP VARIATIONS-COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'PERFORM INTERACTIVE TEST', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'SCHEDULED PM VISIT', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'PM Call', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'SETTING ISSUE- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'SOFTWARE UPGRADATION', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'SUDDENLY SWITCH OFF- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'TOUCH SCREEN NOT FUNCTIONING- COM', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'UNIT TRANSFER', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'UPGRADATION', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'VTE PROBLEM- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'VTI PROBLEM- HO/ORI', '{}'::jsonb, '2022-05-13'::date, 'Admin'),
  ('complaint', 'ENCODER KNOB ISSUE', '{}'::jsonb, '2022-09-22'::date, 'Devika'),
  ('complaint', '1 Obstructed Inspiratory/ Expiratory Breathing Tube-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '5 Pressure sensor inoperant-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '6 Pressure sensor inoperant-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '7 Ventilator in-operant. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '9 Air and oxygen supply failure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '10 Battery empty. Imminent extension-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '11 Power supply reception failure. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '12 Patient disconnection-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '13 Pressure sensor inoperant-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '14 Low pressure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '15 High pressure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '17 High Pplat-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '20 Apnea-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '23 Run full self-tests-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '26 Low minute volume-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '27 High respiratory rate-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '31 Oxygen supply failure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '32 Air supply failure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '46 High minute volume-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '47 Battery low. Connect to external supply-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '52 Lost connection in stand-by. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '53 Lost connection in ventilation. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '54 Cooling fan failure. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '56 Low VTe-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '57 High VTe-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '62 PEEP High-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '63 PI Limit Reached-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '64 PEEP Low-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '65 Low respiratory rate-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '67 Internal battery in-operant-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '68 Stop of ventilation requested…Return in Stand-by-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '83 Ventilator operates from internal battery-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '85 High pressure-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '100 Right loudspeaker in-operant. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '99 Left loudspeaker in-operant. Contact technical service-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '88 O2 sensor deactivated. Use external O2 monitor.-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '106 Nebulization function activated-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '109 Stand by-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '113 pPeak Upper Threshold >60-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '107 Inspiratory Hold-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '102 Expiratory Hold-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('complaint', '108 Demonstration Software-VEGA', '{}'::jsonb, '2023-01-11'::date, 'Devika'),
  ('pendingreason', 'CRISIS-ENGINEER UNABLE TO ATTEND', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'CUSTOMER SITE NOT READY', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'ENGINEER NOT AVAILABLE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MACHINE NOT AVAILABLE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MACHINE SENT TO INDOOR SERVICE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MACHINE UNDER OBSERVATION', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MACHINE UNDER PROCESS', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MACHINE WORKING UNDER CONSTRAINST', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'SPARES NOT AVAILABLE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'SPARES RECEIVED IN DEFECTIVE CONDITION', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'UNABLE TO REPORT IN WINMAX', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'VENTILATOR ON PATIENT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WAITING FOR CUSTOMER SIGNATURE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WAITING FOR ESTIMATION APPROVAL', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WAITING FOR PAYMENT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WAITING FOR REPLACEMENT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WAITING FOR TECHNICAL SUPPORT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'SERVICE COMPLETED AT INDOOR SERVICE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'WORK IN PROGRESS', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('pendingreason', 'MORE THAN LIFETIME SERVICE', '{}'::jsonb, '2022-11-01'::date, 'Devika'),
  ('pendingreason', 'MONTH END CALLS', '{}'::jsonb, '2023-06-21'::date, 'Devika'),
  ('cancelreason', 'ALTERNATE SERVICE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'CRISIS-ENGINEER UNABLE TO ATTEND', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'CUSTOMER DECISION BUY BACK', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Customer donated.', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'CUSTOMER NOT APPROVED THE ESTIMATE', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Customer returned the equipment.', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Demo unit PM call generated', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'For Training Purpose', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Machine Not Installed, Wrong PM call generated', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Order Cancelled', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'PM CALL GENERATED DEMO EQUIPMENT', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'PM CALLS CANCELLED ON 18 Nov 2017', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'PM calls created dealer name', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Product transfer purpose call created', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'SCHEDULE CALL CREATED FROM DEALER NAME', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'UNABLE TO REPORT IN WINMAX', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'WRONG CALL REGISTRATION', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Wrong PM Calls created (Sale invoice cancelled)', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'WRONG PM CALLS CREATED (SOFTWARE ISSUE)', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Wrong sl.no. entered', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Wrong supply', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Wrong supply (Dealer)', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Wrongly entered dealer name.', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Customer Denied', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('cancelreason', 'Repeated Calls-Software Issue', '{}'::jsonb, '2022-11-19'::date, 'Devika'),
  ('cancelreason', 'INSTALLATION IS NOT COMPLETED', '{}'::jsonb, '2023-09-01'::date, 'Admin'),
  ('cancelreason', 'PRODUCT TRANSFERRED TO DIFFERENT PARTY', '{}'::jsonb, '2023-09-21'::date, 'Admin'),
  ('feedbackrating', 'Excellent', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('feedbackrating', 'Good', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('feedbackrating', 'Average', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('feedbackrating', 'Poor', '{}'::jsonb, '2022-06-09'::date, 'Admin'),
  ('orapproval', 'KOL CUSTOMER', '{"stage": "NSM", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Approved', '{"stage": "RM", "status": "Approved"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Wrong Spare', '{"stage": "RM", "status": "Rejected"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Duplicate Request', '{"stage": "RM", "status": "Rejected"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'LONG PENDING', '{"stage": "NSM", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'ENGINEER ASSURANCE', '{"stage": "NSM", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'PAYMENT RECEIVED', '{"stage": "NSM", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'APPROVED FOR TESTING PURPOSE', '{"stage": "NSM", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Under CMC', '{"stage": "ADMIN", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Under WGP', '{"stage": "ADMIN", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Under AMC', '{"stage": "ADMIN", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'Direct PO', '{"stage": "ADMIN", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN'),
  ('orapproval', 'OGP', '{"stage": "ADMIN", "status": "Cleared for Stores Processing"}'::jsonb, '2023-09-30'::date, 'RITHI ADMIN')
on conflict do nothing;
